### ISSUE TITLE
Local keys now contain special characters

### ISSUE THREAD

**Issue by lukrs** [make-all/tuya-local#1065] opened 2023-09-05 18:02 UTC
Hi, 

Try readding a device to SmartLife app, local key changes, and now you get things like "?G|u1~>bnS&;)H!U" for localKey.
Rospogrigio/localtuya, the alternative to tuya-local has already fixed the problem, but the tuya-local is better, and this should be fixed.

**Comment by bartczar** [comment] 2023-09-05 19:23
How is it a problem?
Can it be that due to that bug I cannot add my new Bresser 7 in 1 weather station (it is being detected as 28% temp/humidity sensor).

**Comment by MattJeanes** [comment] 2023-09-05 19:44
Yeah just ran into this myself after setting up a new device, we're seeing characters like `)` `?` `+` `_` etc and I can no longer get Tuya Local to add the device, it returns the error 'Unable to connect to your device with those details. It could be an intermittent issue, or they may be incorrect.'

The `python -m tinytuya wizard` is working as expected on my PC on the same network and is how I found this new special characters local key

**Comment by bartczar** [comment] 2023-09-05 19:50
Well: I was able to successfully add wifi light bulb (also with local key containing special chars), but I cannot add bresser weather station (as above): it is detected as different device.

**Comment by make-all** [comment] 2023-09-05 21:32
This is a duplicate of #890.  All we have so far is speculation, no hard evidence of the bug, though this does go further in testing localtuya and tinytuya,.  It is not clear though where the "special characters" are causing an issue, or which specific characters are problematic.

You say that "localtuya has fixed the issue" - can you point to a commit, as this might give some clues where to look in this integration.

**Comment by bartczar** [comment] 2023-09-06 05:30
Just to note that In my case it was something else and now I have added bresser weather station without problem.

**Comment by lukrs** [comment] 2023-09-06 08:01
couldn't find the commit

**Comment by make-all** [comment] 2023-09-06 08:14
The Homebridge change is to their validation logic, as they previously enforced local keys being hex characters only.  Currently the only enforcement we have is that they are a string.  If this bug exists, I think it will be more subtle than that, and most likely in the web entry side in home-assistant/frontend since tinytuya seems to have been verified as able to work now, as I've reviewed all the data paths for local_key and there is nowhere that would be corrupting or limiting it inside the integration itself.

**Comment by lukrs** [comment] 2023-09-06 08:18
Ok, then it is in home assistant frontend. LocalTuya works through homeassistant frontend. Where should we pursue the issue?

**Comment by make-all** [comment] 2023-09-06 08:58
It is just a theory of the most likely source of encoding issues for now,  Before pursuing it, we need to gather some info.

Adding logging of the local_key to config_flow.py, where it is received from the front end should show whether it is corrupted already when we receive it, and how.  If it is OK there, then adding logging elsewhere (where it is read from the config during startup, where it is sent to tinytuya) will be needed to pinpoint where it is happening.

**Comment by make-all** [comment] 2023-09-06 09:43
The key `?G|u1~>bnS&;)H!U` seems to be received from the HA frontend OK.  So more logging in various locations will be needed.  The problem is, I do not have a device that has this key format, so I cannot check many code paths myself.

**Comment by MattJeanes** [comment] 2023-09-06 09:47
In my case, resetting a device to onboard it again in the Tuya app regenerated the key with the new special characters. As the device was already in Tuya it seemed to pick that up and reconnect it without losing any data.

If there's anything I can try to help debug this please let me know, I'd be happy to make manual tweaks to the integration files or use a experimental version etc

**Comment by pullaf** [comment] 2023-09-06 14:21
I just got a Rojeco pet feeder and I was migrating from localtuya to this since that one didn't support it, but now I can't add the device probably due to the key
I managed to re-add an older device that I had on localtuya as it still had the old key, but I'd really love to use the pet feeder too, let me know how I can help

**Comment by jonaseymour** [comment] 2023-09-07 02:18
First time using tuya-local coming from localtuya. Set up a new device fine in localTuya with a localkey including special characters. Tried the same device details in tuya-local and got the same 'Unable to connect to your device with those details. It could be an intermittent issue, or they may be incorrect.' error above.

So I thought that this was the cause...

However... I tried setting up an older device without special characters in its local key and got the same message. So I'm not convinced it's a special character issue.
For reference I'm running:
` Home Assistant 2023.9.0
Supervisor 2023.08.3
Operating System 10.5
Frontend 20230906.1 - latest `
if that helps

**Comment by pullaf** [comment] 2023-09-07 07:17
> First time using tuya-local coming from localtuya. Set up a new device fine in localTuya with a localkey including special characters. Tried the same device details in tuya-local and got the same 'Unable to connect to your device with those details. It could be an intermittent issue, or they may be incorrect.' error above.
> 
> So I thought that this was the cause...
> 
> However... I tried setting up an older device without special characters in its local key and got the same message. So I'm not convinced it's a special character issue. For reference I'm running: ` Home Assistant 2023.9.0` `Supervisor 2023.08.3` `Operating System 10.5` `Frontend 20230906.1 - latest` if that helps

I too got an error at first when adding an old device, but it worked after a couple tries, without ever having to re-roll the key
Still can't add the new one though

**Comment by make-all** [comment] 2023-09-07 09:50
Judging by the number of responses saying their problem turned out to be something else, I think the assumption that a bug exists related to "special characters" may have been made too hastily.

I suggest everyone having issues to go through the posts on #522 and see if any of the previous experiences resolving connectivity issues there can help your case.

**Comment by MattJeanes** [comment] 2023-09-07 10:24
I've pulled the debug logs and this is what I'm seeing, it looks like it can talk to it on some protocol versions but is getting weird responses from it, not sure if there's anything useful that you can see in there:

[tuya-debug.txt](https://github.com/make-all/tuya-local/files/12547582/tuya-debug.txt)

**Comment by pullaf** [comment] 2023-09-07 10:28
Ok, by testing all protocol versions I managed to add the new device, I think 3.5 is what did the trick, not sure why 'auto' wasn't working
So it wasn't a key problem after all?

**Comment by make-all** [comment] 2023-09-07 11:45
"Auto" protocol version is just a trial and error process.  The problem is that incorrect protocol versions can trigger bugs inside the devices that cause them to go offline for some time, so the correct protocol version can fail due to the device not being ready when it is tried, leading to it not being detected.

**Comment by louispires** [comment] 2023-09-09 13:57
Also just ran into this, had added a device a long time ago which had this `local_key: 29c2d5e6af64f28e`

I then moved it to a new Wi-fi by removing and re-adding to Smart Life, open up Tuya Cloud and retrieve the local_key and surprise it now looks like this: `local_key: o:qQJ1W~A+(B+3uB`

I know this device is version 3.3, which I've tried, including every other protocol but none of them work.

I also cycled the local_key a couple more times, but still fails to connect.

![image](https://github.com/make-all/tuya-local/assets/8841644/46c93083-9dfb-48df-97a7-d07ae1ad9b01)

**Comment by louispires** [comment] 2023-09-09 14:18
> Also just ran into this, had added a device a long time ago which had this `local_key: 29c2d5e6af64f28e`
> 
> I then moved it to a new Wi-fi by removing and re-adding to Smart Life, open up Tuya Cloud and retrieve the local_key and surprise it now looks like this: `local_key: o:qQJ1W~A+(B+3uB`
> 
> I know this device is version 3.3, which I've tried, including every other protocol but none of them work.
> 
> I also cycled the local_key a couple more times, but still fails to connect.
> 

Got it fixed now, I was simply trying to Configure an already added entity where it allows me to change the Local_Key and the supposedly update the device.

This did not work at all.

Once I deleted the device and went to add a new device, it immediately worked.

Thus, the issue is probably not with the special characters, but the updating/changing of an already linked device.

**Comment by make-all** [comment] 2023-09-09 15:01
OK, that makes sense. Until now it hadn't occurred to me that all the issues were with reconfiguring existing devices, and not adding new ones.

This has the same root cause as issue #968 in that case.

**Comment by MattJeanes** [comment] 2023-09-09 15:18
Yep, that was it for me too - needed to fully remove the device and re-add it. I was also unable to add it back using the auto protocol but cycling through them manually worked for me.

**Comment by rafal98** [comment] 2023-09-13 19:20
I confirm, same story: adding "wifi dual meter", it works ! But I force a static DHCP and change IP, then click to "configure" : it never connect again :-( But python minituya can connect  !!
So, thankfully I find this thread ! So I remove Tuya Local integration, add it again, add device with the right IP, and it works ! :-)

**Comment by make-all** [comment] 2023-09-13 22:13
I don't think you need to remove the integration, just the device.

**Comment by make-all** [comment] 2023-09-26 00:24
The issue causing the reconfigure not to work may have been fixed in 2023.9.1 (#1110)

**Closed** 2023-10-11 13:54 UTC

**Comment by f22raptorroland** [comment] 2024-11-28 14:52
I have the same issue with "JH PCIe pro+ computer switch" from devices
The key is: **5u#LRvU+-iZl3yxw**

Is is working from tuya App
Can also ping it if I SSH into HA

I'm configuring via a VPN, but will try to get a new key when I get home
Also tried with localtuya. I get this exact* same  async_step_configure_device... output:
https://github.com/rospogrigio/localtuya/issues/1426

Let me know if I can help with the debugging somehow.

**Comment by Lexx178** [comment] 2024-12-08 20:16
I also had a similar problem and thought it was because of the symbols in the key. 
During testing and diagnostics, I deleted localtuya and rebooted the server. 
After that, the device was added without any issues.

Here is what was in the logs when the device wouldn't add.
I don't fully understand the meaning of these lines yet, but maybe they can help you.

Many strings with:

2024-12-08 22:29:48.293 WARNING (MainThread) [custom_components.localtuya.common] Missing device configuration for device_id xxxxxxxxxxxxxx
2024-12-08 22:29:50.369 WARNING (MainThread) [custom_components.localtuya.common] Missing device configuration for device_id yyyyyyyyyyyyyy


And some of this:

 <details>
<summary>click this to view 100 strings Log</summary>

2024-12-08 21:55:51.219 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to walk with args ('/config/custom_components/tuya_local/devices',) inside the event loop by custom integration 'tuya_local' at custom_components/tuya_local/helpers/device_config.py, line 1010: for path, dirs, files in walk(_CONFIG_DIR): (offender: /config/custom_components/tuya_local/helpers/device_config.py, line 1010: for path, dirs, files in walk(_CONFIG_DIR):), please create a bug report at https://github.com/make-all/tuya-local/issues
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#walk
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 227, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 213, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 154, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 708, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 679, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 2027, in _run_once
    handle._run()
  File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py", line 480, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_app.py", line 569, in _handle
    return await handler(request)
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 86, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
    return await func(self, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 222, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
    return await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 122, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in async_configure
    result = await self._async_configure(flow_id, user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 414, in _async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 517, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
  File "/config/custom_components/tuya_local/config_flow.py", line 328, in async_step_local
    return await self.async_step_select_type()
  File "/config/custom_components/tuya_local/config_flow.py", line 366, in async_step_select_type
    async for type in self.device.async_possible_types():
  File "/config/custom_components/tuya_local/device.py", line 395, in async_possible_types
    for matched in await self._hass.async_add_executor_job(
  File "/config/custom_components/tuya_local/helpers/device_config.py", line 1018, in possible_matches
    for cfg in available_configs():
  File "/config/custom_components/tuya_local/helpers/device_config.py", line 1010, in available_configs
    for path, dirs, files in walk(_CONFIG_DIR):
	
	
	2024-12-08 21:55:56.538 WARNING (MainThread) [custom_components.tuya_local.config_flow] Device matches beca_bht002_thermostat_c with quality of 100%. DPS: {"updated_at": 1733684151.0238016, "1": true, "2": 58, "3": 57, "4": "1", "5": false, "6": false, "102": 57, "104": true}
2024-12-08 21:55:56.538 WARNING (MainThread) [custom_components.tuya_local.config_flow] Include the previous log messages with any new device request to https://github.com/make-all/tuya-local/issues/


2024-12-08 22:28:48.509 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to import_module with args ('.climate', 'custom_components.localtuya') inside the event loop by custom integration 'localtuya' at custom_components/localtuya/config_flow.py, line 200: return import_module("." + platform, integration_module).flow_schema(dps_strings) (offender: /config/custom_components/localtuya/config_flow.py, line 200: return import_module("." + platform, integration_module).flow_schema(dps_strings)), please create a bug report at https://github.com/rospogrigio/localtuya/issues
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 227, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 213, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 154, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 708, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 679, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 2027, in _run_once
    handle._run()
  File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py", line 559, in start
    task = asyncio.Task(coro, loop=loop, eager_start=True)
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py", line 480, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_app.py", line 569, in _handle
    return await handler(request)
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 86, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
    return await func(self, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 285, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
    return await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 122, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in async_configure
    result = await self._async_configure(flow_id, user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 414, in _async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 517, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
  File "/config/custom_components/localtuya/config_flow.py", line 676, in async_step_pick_entity_type
    return await self.async_step_configure_entity()
  File "/config/custom_components/localtuya/config_flow.py", line 782, in async_step_configure_entity
    schema = platform_schema(self.selected_platform, available_dps)
  File "/config/custom_components/localtuya/config_flow.py", line 194, in platform_schema
    return vol.Schema(schema).extend(flow_schema(platform, dps_strings))
  File "/config/custom_components/localtuya/config_flow.py", line 200, in flow_schema
    return import_module("." + platform, integration_module).flow_schema(dps_strings)

</details>
