### ISSUE TITLE
`TypeError: object Future can't be used in 'await' expression`

### ISSUE THREAD

**Issue by felipecrs** [make-all/tuya-local#1939] opened 2024-05-22 18:02 UTC
Tuya Local 2024.5.2
Home Assistant 2024.5.4

I found this in my logs:

```
2024-05-22 14:56:02.468 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/tuya_local/device.py", line 170, in async_stop
    await self._refresh_task
TypeError: object Future can't be used in 'await' expression
2024-05-22 14:56:02.476 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/tuya_local/device.py", line 170, in async_stop
    await self._refresh_task
TypeError: object Future can't be used in 'await' expression
2024-05-22 14:56:02.487 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/tuya_local/device.py", line 170, in async_stop
    await self._refresh_task
TypeError: object Future can't be used in 'await' expression
```

I think it happens when I attempt to restart Home Assistant, but not very sure.

**Comment by make-all** [comment] 2024-05-22 22:43
Duplicate of #1888

**Closed by make-all** 2024-05-22 22:43 UTC
