### ISSUE TITLE
Detected blocking call to sleep inside the event loop

### ISSUE THREAD

**Issue by johnnycochran** [make-all/tuya-local#482] opened 2023-03-01 21:57 UTC
The following warning is persistent with every restart of HA. It's not clear to me what stability issues are being caused, if any.  

Logger: homeassistant.util.async_
Source: util/async_.py:159
First occurred: 2:37:19 PM (8 occurrences)
Last logged: 3:28:49 PM

Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom integration author for tuya_local doing blocking calls at custom_components/tuya_local/device.py, line 65: self._api = tinytuya.Device(dev_id, address, local_key)

<img width="658" alt="Screen Shot 2023-03-01 at 3 38 46 PM" src="https://user-images.githubusercontent.com/38549554/222273402-b9304dc5-b2d1-47f0-ae66-1653ab6cbe54.png">

**Comment by make-all** [comment] 2023-03-01 22:18
Duplicate of #407.  You can avoid this by setting the IP address.

**Closed by make-all** 2023-03-01 22:18 UTC
Labels: bug
