### ISSUE TITLE
Blocking call during startup

### ISSUE THREAD

**Issue by jaamulberry** [make-all/tuya-local#724] opened 2023-05-18 01:02 UTC
Logger: homeassistant.util.async_
Source: util/async_.py:159
First occurred: 8:57:15 PM (1 occurrences)
Last logged: 8:57:15 PM

Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom integration author for tuya_local doing blocking calls at custom_components/tuya_local/device.py, line 78: self._api = tinytuya.Device(dev_id, address, local_key)

HomeAssisstant Supervisor: 2023.5.3
Supervisor: 2023.04.1

Running on Raspberry Pi 4 8G on Debian

**Comment by make-all** [comment] 2023-05-18 01:33
Duplicate of #407

**Closed by make-all** 2023-05-18 01:33 UTC
