### ISSUE TITLE
entities geting unavailable

### ISSUE THREAD

**Issue by rkarolek** [make-all/tuya-local#619] opened 2023-04-16 07:51 UTC
hello, 
i have problem with my lights (LED Nymphea/Moderna 36W Spectrum SMART, LED Algine R&S Spectrum SMART) both stay unavailable but only in tuya-local integration, both are available over tuya integration all time w/o any problems so its not problem with wifi or interferences from other devices

additionaly when i ty reload integration it takes long long time (about 5 minuts), after reload integration or after restart HA all works well, but only for short time (ususally dome hours)

any idea?

**Comment by make-all** [comment] 2023-04-16 10:37
Duplicate of #618, and posted as a discussion without necessary log info for a bug report.

**Closed by make-all** 2023-04-16 10:37 UTC
Labels: bug
