### ISSUE TITLE
Inkbird Wifi ITC-308 Status Unknown

### ISSUE THREAD

**Issue by kramttocs** [make-all/tuya-local#1230] opened 2023-10-31 12:44 UTC
![image](https://github.com/make-all/tuya-local/assets/11565750/1e152e4c-8cf5-42f2-afdc-bf35c593a092)

It appears to be working correctly and the current temp is correct but the status is always 'unknown'.
This used to show correctly (after you added it) but it's been awhile since I've looked at this device so I can't be sure when it stopped.

**Comment by kramttocs** [comment] 2023-10-31 18:12
[tuya_local-6544712d8d1db6f52aa439894df208cc-Wellhouse Temperature Outlet-a19f6be1cb5100dded5b61bc35284751.json.txt](https://github.com/make-all/tuya-local/files/13220059/tuya_local-6544712d8d1db6f52aa439894df208cc-Wellhouse.Temperature.Outlet-a19f6be1cb5100dded5b61bc35284751.json.txt)

Here you go. Thanks!

**Comment by make-all** [comment] 2023-11-01 02:23
Duplicate of #1144. 

The handling of devices that do not report hvac_mode was changed in 2023.10.1 to report None instead of Auto, to try to get rid of an empty dropdown in the new climate UI.

Since this was not effective, and caused other issues as you are seeing, it has already been reverted in the main branch.

**Closed by make-all** 2023-11-01 02:23 UTC
