### ISSUE TITLE
Warning in Log: Detected blocking call to sleep inside the event loop by custom integration 'tuya_local' 

### ISSUE THREAD

**Issue by HolliDolli** [make-all/tuya-local#1251] opened 2023-11-04 12:17 UTC
Hello, got this warning from tuya_local, and do as advised. :-)

Logger: homeassistant.util.async_
Source: util/async_.py:140
First occurred: 12:48:19 PM (4 occurrences)
Last logged: 12:48:32 PM

Detected blocking call to sleep inside the event loop by custom integration 'tuya_local' at custom_components/tuya_local/device.py, line 77: self._api = tinytuya.Device(dev_id, address, local_key), please create a bug report at https://github.com/make-all/tuya-local/issues

**Describe the bug**
I see no direct connection, but one of my tuya-devices(ledvance light) turns sometimes unavailable.
the device is still fully functional via ledvance-app, but unavailable in HA.
Its not a problem for me, because i have a workaround (switch hole group via ledvance-app/automation, when one device changes state)

**To Reproduce**
I dont know.

**Expected behavior**
I think a warning is ok. :-)

**Additional context**
you dont need to solve this, but i want to let you know.
Maybe i can be helpful for you.

If the bug involves a device, then please include device diagnostics from
Settings / Devices & Services / Tuya Local (your device) / "1 device"

[tuya_local-fb396f02672d04aabc504d8bda39fca0-GW-AL1u-87bb822330e99c9c6b3553c0fdd36a15.json.txt](https://github.com/make-all/tuya-local/files/13256612/tuya_local-fb396f02672d04aabc504d8bda39fca0-GW-AL1u-87bb822330e99c9c6b3553c0fdd36a15.json.txt)

Please check if there are messages from Tuya Local in the Home
Assistant log (Settings / System / Logs), and include those too.
only the message from above.

![image](https://github.com/make-all/tuya-local/assets/115486571/e97d3431-f082-4ec5-9b74-8bf5bbf45d71)

BTW: hanks for your work. Highly appreciated.

**Comment by make-all** [comment] 2023-11-04 12:31
Duplicate of #407

**Closed by make-all** 2023-11-04 12:31 UTC
Labels: bug

**Comment by HolliDolli** [comment] 2023-11-04 15:08
Thank you. Changed ip-setting. That looks good. HolgerAm 04.11.2023 um 13:31 schrieb Jason Rumney ***@***.***>:﻿
Duplicate of #407
