### ISSUE TITLE
Can't connect WiFi device 

### ISSUE THREAD

**Issue by abdess47** [make-all/tuya-local#1298] opened 2023-11-13 20:26 UTC
I can't add the device in local tuya.
I got error message :

Detected blocking call to sleep inside the event loop by custom integration 'tuya_local' at custom_components/tuya_local/device.py, line 77: self._api = tinytuya.Device(dev_id, address, local_key), please create a bug report at https://github.com/make-all/tuya-local/issues

Here's the response of Iot platform
I delete sensible information.
{
  "result": [
    {
      "active_time": 1689901633,
      "category": "aqcz",
      "create_time": 1673532722,
      "custom_name": "Borne voiture (mesure conso)",
      "icon": "smart/icon/bay16111967609110m8U/f38a67283ad104867f4ca70eb9817f4e.jpg",
      "id": "delete info",
      "ip": "delete info",
      "is_online": true,
      "lat": "delete info",
      "local_key": "delete info",
      "lon": "3.6600",
      "model": "PJ-1103",
      "name": "WiFi Digital Meter",
      "product_id": "djfep9s6s3b2qk89",
      "product_name": "WiFi Digital Meter",
      "sub": false,
      "time_zone": "+02:00",
      "update_time": 1699785890,
      "uuid": "492e1ca0960adf7a"
    }
  ],
  "success": true,
  "t": 1699906336460,
  "tid": "f0cf7f29826011eeab249a6504bbc951"
}

**Comment by make-all** [comment] 2023-11-13 23:00
Duplicate of #407 and possibly combined with #408

**Closed by make-all** 2023-11-13 23:00 UTC
Labels: bug
