### ISSUE TITLE
Blocking call to sleep inside the event lopp - HASS Core update 2024.4.4

### ISSUE THREAD

**Issue by arkixana** [make-all/tuya-local#1849] opened 2024-04-24 17:52 UTC
After updating Home Assistant Core to 2024.4.4, I received the following bug:

**Describe the bug**

Registrador: homeassistant.util.async_
Fuente: util/async_.py:160
Ocurrió por primera vez: 19:43:05 (1 ocurrencias)
Último inicio de sesión: 19:43:05

Detected blocking call to sleep inside the event loop by custom integration 'tuya_local' at custom_components/tuya_local/device.py, line 77: self._api = tinytuya.Device(dev_id, address, local_key), please create a bug report at https://github.com/make-all/tuya-local/issues

**Comment by make-all** [comment] 2024-04-24 21:13
Duplicate of #407

**Closed by make-all** 2024-04-24 21:13 UTC
