### ISSUE TITLE
local.climate.TuyaLocalClimate Bug HA 2024.3

### ISSUE THREAD

**Issue by Kaeybe** [make-all/tuya-local#1734] opened 2024-03-10 21:51 UTC
Hello,
After updating HomeAssistant, this warning appeared

Registratore: homeassistant.components.climate
Fonte: components/climate/__init__.py:361
integration: Climatizzatore ([documentazione](https://www.home-assistant.io/integrations/climate), [problemi](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+climate%22))
Prima occorrenza: 22:30:01 (1 occorrenze)
Ultima registrazione: 22:30:01

Entity None (<class 'custom_components.tuya_local.climate.TuyaLocalClimate'>) implements HVACMode(s): off, heat and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/make-all/tuya-local/issues

**Comment by make-all** [comment] 2024-03-10 22:17
Duplicate of #1597 which was fixed in tuya-local 2024.3.1, you must still be on an older version.

**Closed by make-all** 2024-03-10 22:17 UTC

**Comment by Kaeybe** [comment] 2024-03-10 22:25
I have 2024.3.1 version

**Comment by make-all** [comment] 2024-03-11 04:26
Which device is this for? There are some devices that do not support TURN_OFF and TURN_ON, but the underlying climate implementation in tuya-local needs to implement those functions for the devices that do support them.

The way HA has chosen to spam the logs with instructions to file bugs reports against integrations is a bit rude really.

**Comment by Kaeybe** [comment] 2024-03-11 04:38
I'm sorry, I didn't mean to disturb. I thought it would be useful write this bug, my device is a Klarstein Bornholm Smart heater

**Comment by make-all** [comment] 2024-03-11 10:45
I'm not sure which config that would be, but both Klarstein heater configs look like they should result in TURN_OFF and TURN_ON being explicitly supported.

Maybe the device diagnostics can show what the problem is (Settings/Devices&Services/Tuya local [...Devices]/[your device]/Download Diagnostics)

**Comment by AnthonyBe** [comment] 2024-04-26 00:55
I'm also still seeing this warning logged with HA 2024.4.4 and integration v2024.3.2
`2024-04-26 10:42:17.215 WARNING (MainThread) [homeassistant.components.climate] Entity None (<class 'custom_components.tuya_local.climate.TuyaLocalClimate'>) implements HVACMode(s): off, heat_cool, cool, heat and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/make-all/tuya-local/issues`

I have a Madimack Elite V3 Pool heat pump.

Device diagnostics attached. Please let me know if you need anything else to further investigate.
[config_entry-tuya_local-d034ef92878d07fe82ac2895d3fca661.json](https://github.com/make-all/tuya-local/files/15123765/config_entry-tuya_local-d034ef92878d07fe82ac2895d3fca661.json)

**Comment by make-all** [comment] 2024-04-26 02:02
Nothing further is needed. The message is a false message which the HA devs have indicated they have no intention of fixing, so an ugly workaround has been installed which will be in the next release of this integration.
