### ISSUE TITLE
Problem bht8000

### ISSUE THREAD

**Issue by dany85free** [make-all/tuya-local#1632] opened 2024-02-08 19:52 UTC
Logger: homeassistant.components.climate
Source: components/climate/__init__.py:354
Integration: Climatizzatore (documentation, issues)
First occurred: 20:46:14 (3 occurrences)
Last logged: 20:46:14

Entity None (<class 'custom_components.tuya_local.climate.TuyaLocalClimate'>) does not set ClimateEntityFeature.TURN_OFF but implements the turn_off method. Please create a bug report at https://github.com/make-all/tuya-local/issues
Entity None (<class 'custom_components.tuya_local.climate.TuyaLocalClimate'>) does not set ClimateEntityFeature.TURN_ON but implements the turn_on method. Please create a bug report at https://github.com/make-all/tuya-local/issues
Entity None (<class 'custom_components.tuya_local.climate.TuyaLocalClimate'>) implements HVACMode(s): off, auto, heat and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/make-all/tuya-local/issues

**Comment by make-all** [comment] 2024-02-09 00:56
What is the actual problem you are experiencing?

**Comment by make-all** [comment] 2024-02-09 03:06
I think this is just a duplicate of #1597, and there is no actual problem here, just a deprecation warning for a change that first appeared in HA 2024.2 released yesterday, and not actually affecting anything until HA 2025.1.

**Closed by make-all** 2024-02-09 03:06 UTC

**Comment by TeddyLafrite** [comment] 2024-02-10 12:48
Hi
Same here with NEDIS heater : 

> Logger: homeassistant.components.climate
> Source: components/climate/__init__.py:354
> Integration: Thermostat (documentation, issues)
> First occurred: 13:45:25 (9 occurrences)
> Last logged: 13:45:25
> 
> Entity None (<class 'custom_components.tuya_local.climate.TuyaLocalClimate'>) does not set ClimateEntityFeature.TURN_OFF but implements the turn_off method. Please create a bug report at https://github.com/make-all/tuya-local/issues
> Entity None (<class 'custom_components.tuya_local.climate.TuyaLocalClimate'>) does not set ClimateEntityFeature.TURN_ON but implements the turn_on method. Please create a bug report at https://github.com/make-all/tuya-local/issues
> Entity None (<class 'custom_components.tuya_local.climate.TuyaLocalClimate'>) implements HVACMode(s): heat, off and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/make-all/tuya-local/issues
