### ISSUE TITLE
Request support for ev charger

### ISSUE THREAD

**Issue by laszlocom** [make-all/tuya-local#1947] opened 2024-05-25 15:41 UTC
{
  "result": {
    "properties": [
      {
        "code": "work_state",
        "custom_name": "",
        "dp_id": 3,
        "time": 1716547753101,
        "value": "charger_free"
      },
      {
        "code": "fault",
        "custom_name": "",
        "dp_id": 10,
        "time": 1716557313999,
        "value": 0
      },
      {
        "code": "alarm_set_1",
        "custom_name": "",
        "dp_id": 11,
        "time": 1716557312406
      },
      {
        "code": "alarm_set_2",
        "custom_name": "",
        "dp_id": 12,
        "time": 1716557312406
      },
      {
        "code": "work_mode",
        "custom_name": "",
        "dp_id": 14,
        "time": 1716547753101,
        "value": "charge_now"
      },
      {
        "code": "balance_energy",
        "custom_name": "",
        "dp_id": 15,
        "time": 1716547753101,
        "value": 0
      },
      {
        "code": "clear_energy",
        "custom_name": "",
        "dp_id": 16,
        "time": 1716547753101,
        "value": false
      },
      {
        "code": "switch",
        "custom_name": "",
        "dp_id": 18,
        "time": 1716547753101,
        "value": false
      },
      {
        "code": "system_version",
        "custom_name": "",
        "dp_id": 23,
        "time": 1716547753101,
        "value": ""
      },
      {
        "code": "charge_energy_once",
        "custom_name": "",
        "dp_id": 25,
        "time": 1716547753101,
        "value": 1
      },
      {
        "code": "online_state",
        "custom_name": "",
        "dp_id": 27,
        "time": 1716547753101,
        "value": "online"
      },
      {
        "code": "DeviceState",
        "custom_name": "",
        "dp_id": 101,
        "time": 1716557314032,
        "value": "no_connet"
      },
      {
        "code": "A_Voltage",
        "custom_name": "",
        "dp_id": 102,
        "time": 1716561049249,
        "value": 427
      },
      {
        "code": "B_Voltage",
        "custom_name": "",
        "dp_id": 103,
        "time": 1716547753101,
        "value": 0
      },
      {
        "code": "C_Voltage",
        "custom_name": "",
        "dp_id": 104,
        "time": 1716547753101,
        "value": 0
      },
      {
        "code": "A_Current",
        "custom_name": "",
        "dp_id": 105,
        "time": 1716557316013,
        "value": 0
      },
      {
        "code": "B_Current",
        "custom_name": "",
        "dp_id": 106,
        "time": 1716547753101,
        "value": 0
      },
      {
        "code": "C_Current",
        "custom_name": "",
        "dp_id": 107,
        "time": 1716547753101,
        "value": 0
      },
      {
        "code": "PhaseFlag",
        "custom_name": "",
        "dp_id": 108,
        "time": 1716547753101,
        "value": "Single_phase"
      },
      {
        "code": "DeviceKw",
        "custom_name": "",
        "dp_id": 109,
        "time": 1716557315024,
        "value": 0
      },
      {
        "code": "DeviceTemp",
        "custom_name": "",
        "dp_id": 110,
        "time": 1716561014664,
        "value": 545
      },
      {
        "code": "DeviceTemp2",
        "custom_name": "",
        "dp_id": 111,
        "time": 1716547753101,
        "value": -300
      },
      {
        "code": "DeviceKwh",
        "custom_name": "",
        "dp_id": 112,
        "time": 1716557314997,
        "value": 0
      },
      {
        "code": "DeviceMaxSetA",
        "custom_name": "",
        "dp_id": 113,
        "time": 1716557317257,
        "value": "Max16A"
      },
      {
        "code": "Set16A",
        "custom_name": "",
        "dp_id": 114,
        "time": 1716557313689,
        "value": 16
      },
      {
        "code": "Set32A",
        "custom_name": "",
        "dp_id": 115,
        "time": 1716557313791,
        "value": 16
      },
      {
        "code": "Set40A",
        "custom_name": "",
        "dp_id": 116,
        "time": 1716557313859,
        "value": 16
      },
      {
        "code": "Set50A",
        "custom_name": "",
        "dp_id": 117,
        "time": 1716557313886,
        "value": 16
      },
      {
        "code": "SetDelayTime",
        "custom_name": "",
        "dp_id": 118,
        "time": 1716557313915,
        "value": 0
      },
      {
        "code": "SetDefineTime",
        "custom_name": "",
        "dp_id": 119,
        "time": 1716557313946,
        "value": 0
      },
      {
        "code": "Ctime",
        "custom_name": "",
        "dp_id": 120,
        "time": 1716551755498,
        "value": 10
      },
      {
        "code": "CTime2",
        "custom_name": "",
        "dp_id": 121,
        "time": 1716547753101,
        "value": 0
      },
      {
        "code": "IDVerificationSet",
        "custom_name": "",
        "dp_id": 122,
        "time": 1716547753101,
        "value": false
      },
      {
        "code": "RFID",
        "custom_name": "",
        "dp_id": 123,
        "time": 1716547753101,
        "value": false
      },
      {
        "code": "ChargingOperation",
        "custom_name": "",
        "dp_id": 124,
        "time": 1716557313965,
        "value": "WaitOperation"
      }
    ]
  },
  "success": true,
  "t": 1716651560070,
  "tid": "f3de8a581aac11ef89139a1bd412573b"
}

https://vi.aliexpress.com/item/1005006671757991.html?spm=a2g0o.order_list.order_list_main.11.6d341802HQVnFh&gatewayAdapt=glo2vnm

![IMG_8891](https://github.com/make-all/tuya-local/assets/118111747/33ad7608-e899-4e8f-9c5e-0a68ad9e2ab6)
![IMG_8890](https://github.com/make-all/tuya-local/assets/118111747/c8a21c53-9b84-4821-857a-8936370615f9)

**Comment by make-all** [comment] 2024-05-26 02:16
Duplicate of #1944 with no additional information filled in from the template.

**Closed by make-all** 2024-05-26 02:16 UTC
