### ISSUE TITLE
delete in Tuya app, not possible to add again

### ISSUE THREAD

**Issue by ErikSiemens** [make-all/tuya-local#450] opened 2023-02-22 06:28 UTC
**Describe the bug**
I was thinking that I could use devices without Tuya app. I deleted a device, fond out it dit not work anymore. Re added the the divice in Tuya app. Still not working in Tuya local. Deleted in Tuya local.
When I try to add it again, Tuya local says its still there and can not be added. But it is not there.
 
**To Reproduce**
See above

**Expected behavior**
possibel to add after remove

**Additional context**

If the bug involves a device, then please include device diagnostics from
did it with a dual switch

Please check if there are messages from Tuya Local in the Home
Assistant log (Settings / System / Logs), and include those too.
Device is gone

**Comment by YuriiMaiboroda** [comment] 2023-02-22 09:17
When a device is readded to an account, a new localkey is generated for it each time. You need to specify a new localkey for the device in the tuya local.

**Comment by YuriiMaiboroda** [comment] 2023-02-22 09:24
Maybe if you block the device from accessing the Internet (for example, a restriction on the router at the mac-address) and delete the device using the mobile Internet... Maybe in this case, the device will not know that it has been removed.
But I wouldn't recommend doing that.

**Comment by make-all** [comment] 2023-02-24 08:42
It is difficult to debug such an issue without log messages, but as Yurii has already said, the local key will be reassigned when you add the device to the app again, so that may be the cause if you have not updated the key in Tuya Local.

As you have experienced, removing the device from the app causes the device to re-enter pairing mode.  It may be possible to remove it from the app in a way that the device cannot detect that it has been removed, or maybe the device will be informed by the cloud anyway.  Blocking access to the cloud has mixed results, some users find it works, others find that their device stops responding after some time.  To free yourself from the Tuya cloud, you really need to reflash the devices with Tasmota/ESPHome/OpenBK or there is a tuya cloudcutter project which effectively stops devices from communicating with the cloud by corrupting the cloud security keys, but use this at your own risk as once corrupted there is no uncorrupting them if the device decides to stop responding until it connects to the cloud in future.

**Comment by ErikSiemens** [comment] 2023-02-24 17:36
I was hoping someone Would way;
-delete the file xxx.yaml or 
-delete the folowing text in file xxx.yaml

???

**Comment by YuriiMaiboroda** [comment] 2023-02-24 18:12
In order for the device to work in tuya_local, it must be added to the Tuya or Smart Home application (more precisely, it must be added to your cloud project in iot.tuya.com).
If you deleted the device from the Tuya application, then it will also deleted from your project.

You need to add the device back to your project:
1. Add your device to the Tuya app.
2. Go to project in iot.tuya.com/cloud/.
3. Check if the device from the application has been added to the project. If not - add manually.
4. Get the new locale_id of the device.

Using the new locale_id of the device, add it to tuya_local.


Data about added devices is not stored in .yaml files. They are stored in the Home Assistant database.

I do not recommend trying to delete any data from there yourself if you do not know exactly what you are doing and what consequences this may lead to.

**Comment by make-all** [comment] 2023-02-26 11:17
If there are duplicate entries in the Home Assistant database, they will show up in the Settings/Devices and Settings/Entities listings (you may need to clear the filter at top left to show all devices including non-working ones), and you can delete them from there.

In my experience having duplicate entities just results in a warning in the log, and a second entity being created with _2 at the end of its name, which works (but the first one remains unavailable). But I have never managed to get a duplicate device so I don't know whether the behaviour there would be consistent with what you are seeing.  In general, deleting the device from the Tuya Local box on the Settings/Integrations page should delete both the device and all entities associated with it, and I have never had any problem deleting and re-adding devices this way.  It is also possible to edit the local key for an existing device in the "Options" for that device.

**Comment by ErikSiemens** [comment] 2023-02-26 18:11
> **Describe the bug** I was thinking that I could use devices without Tuya app. I deleted a device, fond out it dit not work anymore. Re added the the divice in Tuya app. Still not working in Tuya local. Deleted in Tuya local. When I try to add it again, Tuya local says its still there and can not be added. But it is not there.
> 
> **To Reproduce** See above
> 
> **Expected behavior** possibel to add after remove
> 
> **Additional context**
> 
> If the bug involves a device, then please include device diagnostics from did it with a dual switch
> 
> Please check if there are messages from Tuya Local in the Home Assistant log (Settings / System / Logs), and include those too. Device is gone
> 
> If applicable, add screenshots to help explain your problem.

![image](https://user-images.githubusercontent.com/42713759/221428481-05efd957-f5bf-4db8-a655-36c3db1f4dc1.png)

**Comment by ErikSiemens** [comment] 2023-02-26 18:15
> If there are duplicate entries in the Home Assistant database, they will show up in the Settings/Devices and Settings/Entities listings (you may need to clear the filter at top left to show all devices including non-working ones), and you can delete them from there.
> 
> In my experience having duplicate entities just results in a warning in the log, and a second entity being created with _2 at the end of its name, which works (but the first one remains unavailable). But I have never managed to get a duplicate device so I don't know whether the behaviour there would be consistent with what you are seeing. In general, deleting the device from the Tuya Local box on the Settings/Integrations page should delete both the device and all entities associated with it, and I have never had any problem deleting and re-adding devices this way. It is also possible to edit the local key for an existing device in the "Options" for that device.



> > **Describe the bug** I was thinking that I could use devices without Tuya app. I deleted a device, fond out it dit not work anymore. Re added the the divice in Tuya app. Still not working in Tuya local. Deleted in Tuya local. When I try to add it again, Tuya local says its still there and can not be added. But it is not there.
> > **To Reproduce** See above
> > **Expected behavior** possibel to add after remove
> > **Additional context**
> > If the bug involves a device, then please include device diagnostics from did it with a dual switch
> > Please check if there are messages from Tuya Local in the Home Assistant log (Settings / System / Logs), and include those too. Device is gone
> > If applicable, add screenshots to help explain your problem.
> 
> ![image](https://user-images.githubusercontent.com/42713759/221428481-05efd957-f5bf-4db8-a655-36c3db1f4dc1.png)


Thanks for your sugestions.
I did have leftover integrations that where not working anymore. Delelted them all. 
When I try to re-add, I get the messagen as showen in the screenshot above. No possiblility to re-add

**Comment by make-all** [comment] 2023-02-26 22:09
I think you should be able to find this already configured device in the System / Devices & Services UI and either delete or edit it.
But if not, the entries will be in /config/.storage/core.config_entries, core.device_registry and core.entity_registry.  Since these files are meant to be automatically maintained by HA, if you edit them when HA is running your changes may get overwritten, so you need to shut down HA (ha core stop) before editing, and take care when removing blocks to leave the files as valid json and that all three files have the blocks referencing that device id removed.

**Closed** 2023-02-27 21:43 UTC
Labels: bug

**Comment by patrickcollins12** [comment] 2023-03-10 01:50
I got it working by
Use the terminal
$ cd /config/.storage

backup each of the files: /config/.storage/core.config_entries, core.device_registry and core.entity_registry
$cp /config/.storage/core.config_entries /config/.storage/core.config_entries.backup

Do a homeassisstant back up as well.

Then edit each of the files to remove the entries you need to remove.

**Comment by make-all** [comment] 2023-03-10 01:56
It should be much easier and safer to do these removals from the Home Assistant UI (Settings / Devices & Services, Devices and Entities tabs - you probably need to clear the filter to see the disabled items)
