### ISSUE TITLE
Home Assistant is annoying with these errors

### ISSUE THREAD

**Issue by Toolmaster30** [make-all/tuya-local#1637] opened 2024-02-10 07:36 UTC
Logger: homeassistant.components.climate
Source: components/climate/__init__.py:354
Integration: Klima ([documentation](https://www.home-assistant.io/integrations/climate), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+climate%22))
First occurred: 08:23:00 (9 occurrences)
Last logged: 08:23:00

Entity None (<class 'custom_components.tuya_local.climate.TuyaLocalClimate'>) does not set ClimateEntityFeature.TURN_OFF but implements the turn_off method. Please create a bug report at https://github.com/make-all/tuya-local/issues
Entity None (<class 'custom_components.tuya_local.climate.TuyaLocalClimate'>) does not set ClimateEntityFeature.TURN_ON but implements the turn_on method. Please create a bug report at https://github.com/make-all/tuya-local/issues
Entity None (<class 'custom_components.tuya_local.climate.TuyaLocalClimate'>) implements HVACMode(s): off, heat, auto and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/make-all/tuya-local/issues

What do these errors mean?
Greetings George

**Comment by make-all** [comment] 2024-02-10 08:48
Duplicate of #1597 

It is not my policy to pick up new features of Home Assistant within days of release, as it leaves other users behind and as a volunteer I do not have enough free time to react that quickly.

If you want to complain about the log messages being annoying it would be better aimed at the HA developers for jumping straight to outputting deprecation warnings pointing at the integrations as the source of the "problem" rather than giving them a couple of months to adapt first.

**Closed by make-all** 2024-02-10 08:48 UTC
