### ISSUE TITLE
Unable to add _third_ Orion Lock

### ISSUE THREAD

**Issue by jaydisc** [make-all/tuya-local#1692] opened 2024-03-02 02:54 UTC
So, I have two of the [Orion Bluetooth Locks](https://www.bunnings.com.au/orion-grid-connect-smart-door-handle-lock_p0330508) and the Bluetooth Hub (https://www.bunnings.com.au/orion-grid-connect-smart-wireless-hub-with-socket_p0330509). You helped me get them right and they work wonderfully. I bought a couple more, but I could not get them added in TuyaLocal. I'd get the error, "Unable to connect to your device with those details. It could be an intermittent issue, or they may be incorrect.", and the debug log output was always:

```
2024-03-02 12:41:47.120 DEBUG (MainThread) [custom_components.tuya_local.device] Refreshing device state for Test
2024-03-02 12:41:47.120 INFO (MainThread) [custom_components.tuya_local.device] Setting protocol version for Test to 3.4
2024-03-02 12:41:47.223 DEBUG (SyncWorker_36) [custom_components.tuya_local.device] Test refreshed device state: {"Error": "Check device key or version", "Err": "914", "Payload": null}
2024-03-02 12:41:47.223 WARNING (SyncWorker_36) [custom_components.tuya_local.device] Test protocol error 914: Check device key or version
2024-03-02 12:41:47.224 DEBUG (SyncWorker_36) [custom_components.tuya_local.device] new state (incl pending): {"updated_at": 1709347307.223619}
2024-03-02 12:41:48.577 DEBUG (MainThread) [custom_components.tuya_local.device] Refreshing device state for Test
2024-03-02 12:41:48.577 INFO (MainThread) [custom_components.tuya_local.device] Setting protocol version for Test to 3.4
2024-03-02 12:41:48.661 DEBUG (SyncWorker_38) [custom_components.tuya_local.device] Test refreshed device state: {"Error": "Check device key or version", "Err": "914", "Payload": null}
2024-03-02 12:41:48.661 WARNING (SyncWorker_38) [custom_components.tuya_local.device] Test protocol error 914: Check device key or version
2024-03-02 12:41:48.662 DEBUG (SyncWorker_38) [custom_components.tuya_local.device] new state (incl pending): {"updated_at": 1709347308.6614728}
```

I was mimicking the settings of the two working locks:

ID, address and key were all that of the Bluetooth Hub, and I would use Tuya IoT Cloud to get the UUID for the lock, and enter that as the sub-device ID.

I then tried to see if I could delete and re-add one of the existing locks (maybe the new locks had different firmware), and that worked! I was quite perplexed.

Then today I worked it out. The first two are always accepted correctly, regardless of whether old or new locks. But the third device never takes. There seems to be a limit on how many locks are supported? I do have 5 of them working correctly in the Tuya app, so maybe something else is happening at the Tuya Local level?

**Comment by make-all** [comment] 2024-03-02 03:51
Duplicate of #1054 
Another user has a branch with an experimental fix for this (should be referenced from that issue, or a Discussion linked to it)

**Closed by make-all** 2024-03-02 03:51 UTC
