### ISSUE TITLE
New version don't working stable with WiFi devices

### ISSUE THREAD

**Issue by Der-Nax** [make-all/tuya-local#238] opened 2022-09-21 21:15 UTC
Hi,
I installed new version 0.19.0.
All my WiFi Tuya devices stop working stable.
Generally all my devices - unavailable. Time to time one or two param get info.
See screenshots
![TuyaLocalError1](https://user-images.githubusercontent.com/108026974/191611547-3019d5cb-914d-49df-b76d-b676ccbdac2c.jpg)
![TuyaLocalError2](https://user-images.githubusercontent.com/108026974/191611550-9cb78890-df6d-408c-a641-3ab022261c92.jpg)
After downgrade back to 0.18.2 - all devices working properly.
Please check new version.
How I may help you?

**Comment by evlo** [comment] 2022-09-22 02:01
Same with _Kogan Wi-Fi convection panel heaters - KAHTP and KAWFHTP models_
```
2022-09-22 03:49:31.620 INFO (MainThread) [custom_components.tuya_local.device] Setting protocol version for topení koupelna to 3.3.
2022-09-22 03:49:31.626 INFO (MainThread) [homeassistant.components.climate] Setting up climate.tuya_local
2022-09-22 03:49:31.626 INFO (MainThread) [homeassistant.components.lock] Setting up lock.tuya_local
2022-09-22 03:49:31.626 INFO (MainThread) [homeassistant.components.number] Setting up number.tuya_local
2022-09-22 03:49:38.632 INFO (MainThread) [homeassistant.components.websocket_api.http.connection] [281472750404032] Connection closed by client
```
I dunno if that last message is related, but it says unavailable for everything after that.

**Comment by make-all** [comment] 2022-09-22 13:58
Thanks for this info.  There are some changes upstream since the tinytuya 1.6.6 release regarding closing and reopening of sockets, so hopefully the next release will fix it.

**Comment by make-all** [comment] 2022-09-22 14:38
For now I've marked the last release as a beta to avoid deploying it further until the cause and solution have been found.

**Comment by Der-Nax** [comment] 2022-09-23 12:48
I updated my installation. 
It look fine after update.
I'll check for 1-2 days.

**Comment by malomehi** [comment] 2022-09-23 16:27
I still have issues with the latest version:
```
2022-09-23 18:14:59.193 WARNING (MainThread) [homeassistant.components.switch] Setup of switch platform tuya_local is taking over 10 seconds.
2022-09-23 18:16:32.266 ERROR (SyncWorker_0) [custom_components.tuya_local.device] Failed to refresh device state for Lamparilla Salón.
2022-09-23 18:17:28.288 ERROR (SyncWorker_1) [custom_components.tuya_local.device] Failed to refresh device state for Lamparilla Salón.
2022-09-23 18:17:59.178 ERROR (SyncWorker_0) [custom_components.tuya_local.device] Failed to refresh device state for Lamparilla Salón.
2022-09-23 18:18:28.334 ERROR (SyncWorker_4) [custom_components.tuya_local.device] Failed to refresh device state for Lamparilla Salón.
2022-09-23 18:18:58.645 ERROR (SyncWorker_4) [custom_components.tuya_local.device] Failed to refresh device state for Lamparilla Salón.
2022-09-23 18:19:53.344 WARNING (MainThread) [homeassistant.components.switch] Updating tuya_local switch took longer than the scheduled update interval 0:00:30
2022-09-23 18:20:23.346 WARNING (MainThread) [homeassistant.components.switch] Updating tuya_local switch took longer than the scheduled update interval 0:00:30
2022-09-23 18:20:53.348 WARNING (MainThread) [homeassistant.components.switch] Updating tuya_local switch took longer than the scheduled update interval 0:00:30
2022-09-23 18:21:23.350 WARNING (MainThread) [homeassistant.components.switch] Updating tuya_local switch took longer than the scheduled update interval 0:00:30
2022-09-23 18:21:53.352 WARNING (MainThread) [homeassistant.components.switch] Updating tuya_local switch took longer than the scheduled update interval 0:00:30
2022-09-23 18:22:23.354 WARNING (MainThread) [homeassistant.components.switch] Updating tuya_local switch took longer than the scheduled update interval 0:00:30
2022-09-23 18:23:53.359 WARNING (MainThread) [homeassistant.components.switch] Updating tuya_local switch took longer than the scheduled update interval 0:00:30
2022-09-23 18:24:23.361 WARNING (MainThread) [homeassistant.components.switch] Updating tuya_local switch took longer than the scheduled update interval 0:00:30
2022-09-23 18:24:40.427 ERROR (SyncWorker_4) [custom_components.tuya_local.device] Failed to refresh device state for Lamparilla Salón.
2022-09-23 18:25:23.364 WARNING (MainThread) [homeassistant.components.switch] Updating tuya_local switch took longer than the scheduled update interval 0:00:30
2022-09-23 18:25:53.366 WARNING (MainThread) [homeassistant.components.switch] Updating tuya_local switch took longer than the scheduled update interval 0:00:30
```

**Comment by evlo** [comment] 2022-09-23 17:28
Looks ok so far.
***
BTW for my _Kogan Wi-Fi convection panel heaters - KAHTP and KAWFHTP models_ I still becomes unavailable for minute or so, after any change, it was doing it even on 18.2 and older. I think it works a bit better with tuya cloud, but it is tuya cloud. I think it might be time to flash esphome on it finally as luckily it is year old and does have espressif chip. _Although i noticed Poland made some great progress at open sourcing new tuya arm espressif chip rellacements._

**Comment by mverbnyak** [comment] 2022-09-23 18:29
Hello.  you can add this thermostat.  please![image](https://user-images.githubusercontent.com/86029323/192033595-0448ecad-64fc-4621-a785-fe3bf4e3d4b6.jpeg)

**Comment by Der-Nax** [comment] 2022-09-23 18:51
> Hello.  you can add this thermostat.  please![image](https://user-images.githubusercontent.com/86029323/192033595-0448ecad-64fc-4621-a785-fe3bf4e3d4b6.jpeg)

Please open new issue.
Also you may try to do it by yourself.
Anyway it is nessasary more detailed information about you device.

**Comment by evlo** [comment] 2022-09-23 20:52
```
Failed to refresh device state for glass panel heater koupeln

Last logged: 10:46:44 PM
First occurred: 10:30:35 PM (22 occurrences)
Integration: Tuya Local ([documentation](https://github.com/make-all/tuya-local), [issues](https://github.com/make-all/tuya-local/issues))
Source: custom_components/tuya_local/device.py:132
Logger: custom_components.tuya_local.device
```
```
Logger: homeassistant.components.climate
Source: helpers/entity_platform.py:796
Integration: Climate ([documentation](https://www.home-assistant.io/integrations/climate), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+climate%22))
First occurred: 10:32:37 PM (7 occurrences)
Last logged: 10:48:37 PM
```
```
Logger: homeassistant.components.lock
Source: helpers/entity_platform.py:796
Integration: Lock ([documentation](https://www.home-assistant.io/integrations/lock), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+lock%22))
First occurred: 10:31:37 PM (26 occurrences)
Last logged: 10:48:37 PM

Updating tuya_local lock took longer than the scheduled update interval 0:00:30
Updating tuya_local climate took longer than the scheduled update interval 0:01:00
```
```
Logger: homeassistant.components.number
Source: helpers/entity_platform.py:796
Integration: Number ([documentation](https://www.home-assistant.io/integrations/number), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+number%22))
First occurred: 10:31:37 PM (26 occurrences)
Last logged: 10:48:37 PM

Updating tuya_local number took longer than the scheduled update interval 0:00:30
```
with 1.8.2 it becomes unavailable, but after while it comes back, with 1.9.1 nope

**Comment by Der-Nax** [comment] 2022-09-23 23:12
> I updated my installation. 
> It look fine after update.
> I'll check for 1-2 days.

I'm sorry. New version didn't solve the problem. The same trouble. Don't work properly.

**Comment by make-all** [comment] 2022-09-26 00:08
1.9.2 reverts the tinytuya library to the previous version. This seems to be working so far for other users.

**Closed** 2022-10-02 12:12 UTC
Labels: awaiting confirmation
