### ISSUE TITLE
"permission deny" when querying the api for the local_key

### ISSUE THREAD

**Issue by bolisaf** [make-all/tuya-local#352] opened 2023-01-17 20:53 UTC
in the instructions on how to get the local_key it says:

_The easiest way to find your local key is with the Tuya Developer portal. If you have previously configured the built in Tuya cloud integration, or localtuya, you probably already have a developer account with the Tuya app linked. Note that you need to use Tuya's own branded "Tuya Smart" or "SmartLife" apps to access devices through the developer portal. For most devices, your device will work identically with those apps as it does with your manufacturer's branded app, but there are a few devices where that is not the case and you will need to decide whether you are willing to potentially lose access to some functionality (such as mapping for some vacuum cleaners).

If you log on to your Developer Portal account, under Cloud you should be able to get a list of your devices, which contains the "Device ID". If you don't see them, check your server is set correctly at the top of the page. Make a note of the Device IDs for all your devices, then select Cloud on the side bar again and go to the API Explorer.

**Under General Device Capabilities / General Devices Management, select the "Get Device Information" function, and enter your Device ID. In the results you should see your local_key.**_

however, when I try what is marked in **bold** I get:

{
"code": 1106,
"msg": "permission deny",
"success": false,
"t": 1673905416350,
"tid": "d4c70c4695e611edb15f72681cb52e7c"
}

I found this in the Tuya help, but I must admit that I don't understand half of what it says:
https://support.tuya.com/en/help/_detail/K9g77zlgd4xmb
https://support.tuya.com/en/help/_detail/K9kui9wvuwc93

_this issue is the same as #348, but I think I didn't provide enough details as it was misunderstood and closed_

thanks in advance
L

**Comment by make-all** [comment] 2023-01-17 22:42
Duplicate of #348 
This issue is not with this integration, please stop reopening it.  This is not a general Tuya support forum.  I am not Tuya.

**Closed by make-all** 2023-01-17 22:42 UTC

**Comment by toooni** [comment] 2023-04-06 17:06
Sorry, but this isn't totally unrelated. It is pretty helpful for other users to have a solution to this issue inside the repository (I would have found the issue sooner.). In my case, the "IoT Core" Trial period was expired. Maybe this is/was the issue with you @bolisaf ?

**Comment by littlej956** [comment] 2023-04-21 13:13
i know it's dumb, but in my case i clicked on "Get the device inf.." not "Get device infor..."  check screenshot. thanks

![tuya](https://user-images.githubusercontent.com/15059191/233644847-04ea26ae-658a-49bb-9413-254d801b272e.png)
