### ISSUE TITLE
Version  2024.4 log warning message

### ISSUE THREAD

**Issue by Joao-Sousa-71** [make-all/tuya-local#1859] opened 2024-04-29 17:40 UTC
This form is for reporting bugs.  If you have encountered a bug, you should
generally have some log messages or device diagnostics to show something is
going wrong.  If your problem is more of a question or a request for help,
then [Discussions](https://github.com/make-all/tuya-local/discussions) is
probably a more suitable venue.

**Describe the bug**
With the latest version there is the following message in the log HA:
`2024-04-29 18:22:33.529 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'tuya_local' sets "minor_version" directly to update a config entry. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to use async_update_entry instead at custom_components/tuya_local/__init__.py, line 448: entry.minor_version = 3, please create a bug report at https://github.com/make-all/tuya-local/issues`

**To Reproduce**
Install latest veriso and restart HA

**Expected behavior**
The integration continue to work and this is just a heads up for the developer since it will stop in September

**Additional context**
Not needed.

If the bug involves a device, then please include device diagnostics from
No

Please check if there are messages from Tuya Local in the Home
Assistant log (Settings / System / Logs), and include those too.

**Comment by make-all** [comment] 2024-04-29 19:20
Duplicate of #1854

**Closed by make-all** 2024-04-29 19:20 UTC
