### ISSUE TITLE
curtain support

### ISSUE THREAD

**Issue by bjoerngiese93** [make-all/tuya-local#69] opened 2021-11-06 20:30 UTC

**Comment by make-all** [comment] 2021-11-06 23:39
This is basically a duplicate of #46 requesting garage door support (both curtains and opening doors are handled by the `cover` platform which is currently not supported).  Since it isn't providing any new information, I'm closing it.

**Comment by make-all** [comment] 2021-11-14 23:46
https://github.com/make-all/tuya-local/issues/46#issuecomment-963610523

**Comment by make-all** [comment] 2021-11-14 23:50
https://github.com/make-all/tuya-local/issues/46#issuecomment-963638123

Hi @bjoerngiese93, I assume that is for the curtain device you requested in #69. That information is part of what I need, it tells the possible values that the dps take. But some of the meanings are not clear, specifically mach_operate FZ and ZZ, and what opposite actually means.

Also, this seems to be taken from the Tuya Portal, which is documentation for the cloud API. For the local API, the device uses numeric indexes in place of the Code, and I need to know those as well. They can be discovered using tuya-cli if you are familiar with that, or by starting to add the device until it gets to the point where it offers to add a Simple Switch or says no matching device found or some other device that isn't really a match. Then cancel and look in the Home Assistant Logs for the latest warning messages from Tuya Local about the mismatch.

Also brand and model are needed to identify what device this is, as there is no generally no standard for Tuya devces, so this will be unlikely to be a generic curtain that works for other devices as well (or at least we will need to find a few more devices to decide it is - so far only smartplugs seem to have common software that is shared across brands)

Further info:
It seems that like switches, Tuya has some standard defined for curtains, but yours seems to be using the options marked as legacy (FZ, ZZ instead of open, close), so I'm not sure the indexes will be the same, as like the switches, they probably reassigned indexes between v1 and v2.

**Comment by make-all** [comment] 2022-04-02 21:55
If no further information can be provided, I will close this issue in May, as it will have been open for 6 months without any further progress.  Cover support is ready, but to add support for the specific device, I require specific information.

Numeric indices are available also from the Tuya Cloud API, but you need to use a specific function, which is right near the end of all the options in the API Explorer. under Smart Home Management System, Device Control, the last "Get Device Specification Attribute" function is the only one that returns the local ID information among the many functions that return basically similar info in the API.

**Comment by make-all** [comment] 2022-04-14 10:31
Yes, that will help support a curtain, even if it isn't the original one that started this issue which uses FZ and ZZ in place of open and close, so is probably a completely different mapping of dps values.

**Comment by sylvainbui** [comment] 2022-04-25 12:53
Hi, I don't know if it will help but here is the device information for Loratap curtain switch. 
{
  "result": {
    "category": "cl",
    "functions": [
      {
        "code": "control",
        "lang_config": {
          "close": "turn off",
          "open": "turn on",
          "stop": "Pause"
        },
        "name": "Status",
        "type": "Enum",
        "values": "{\"range\":[\"open\",\"stop\",\"close\"]}"
      }
    ],
    "status": [
      {
        "code": "control",
        "lang_config": {
          "close": "turn off",
          "open": "turn on",
          "stop": "Pause"
        },
        "name": "Status",
        "type": "Enum",
        "values": "{\"range\":[\"open\",\"stop\",\"close\"]}"
      }
    ]
  }

**Comment by Privatecoder** [comment] 2022-05-10 08:14
enjoy Motors "product_name": "Roller blind" / "model": "GW Motor"

```
   "result":{
      "category":"cl",
      "functions":[
         {
            "code":"control",
            "type":"Enum",
            "values":"{\"range\":[\"open\",\"stop\",\"close\",\"continue\"]}"
         },
         {
            "code":"percent_control",
            "type":"Integer",
            "values":"{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
         }
      ],
      "status":[
         {
            "code":"control",
            "type":"Enum",
            "values":"{\"range\":[\"open\",\"stop\",\"close\",\"continue\"]}"
         },
         {
            "code":"percent_control",
            "type":"Integer",
            "values":"{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
         }
      ]
   }
```

**Comment by make-all** [comment] 2022-06-05 10:59
@Krispkiwi do you have some manfufacturer/model information about this curtain controller?  While it may be based on a generic Tuya sample that is used by a large number of brands, unless I know that for sure, I don't want to put the config in under a generic name, as it could be confusing to others if it turns out to not be generic.

**Comment by Krispkiwi** [comment] 2022-06-05 12:29
@make-all From what I can sees on Ali, it appears to be called the M027 Wifi Smart Curtains

**Comment by make-all** [comment] 2022-06-05 12:42
@sylvainbui, if you go back to the Tuya developer portal where you found that information, there should be an function in the API Explorer near the end of the list that also includes dp_id information.  This is required to tie that cloud API information to the local API.

**Comment by Krispkiwi** [comment] 2022-07-14 05:06
> @sylvainbui, @bjoerngiese93,
> 
> If you want to provide any more information on your respective devices, please open another issue. This issue has become too complex to handle with the number of requests made in it, so since the support for the curtain with full info provided by @Krispkiwi has been released, I would like to close this issue now.

I still get "Sorry, there is no support for this device. when adding the curtain"

**Comment by make-all** [comment] 2022-07-16 15:59
Can you please send the WARNING messages relating to the device from the Home Assistant log after getting that "no support for this device" message.  I am not able to see why it is not supported without them.

**Comment by Krispkiwi** [comment] 2022-07-17 01:21
> Can you please send the WARNING messages relating to the device from the Home Assistant log after getting that "no support for this device" message. I am not able to see why it is not supported without them.

Device matches None with quality of 0%. DPS: {'1': 'close', '2': 0, '4': 'morning', '7': 'closing', '10': 0, '12': 0, '101': False, 'updated_at': 1658020824.3314018}

**Comment by make-all** [comment] 2022-07-17 15:11
I've marked the missing dps as optional in the config, and made some changes to handle them being missing.

**Comment by Krispkiwi** [comment] 2022-07-17 20:02
Issue Resolved, they're set up and working now.

**Comment by Krispkiwi** [comment] 2022-07-17 20:02
Cheers :)

**Closed** 2022-07-24 10:11 UTC
