### ISSUE TITLE
warning appearing at HA Boot

### ISSUE THREAD

**Issue by legantois** [make-all/tuya-local#1756] opened 2024-03-18 19:47 UTC
**Describe the bug**
No real issue detected
just this warning message appearing in the log

2024-03-18 20:34:52.030 WARNING (MainThread) [homeassistant.util.async_] Detected blocking call to sleep inside the event loop by custom integration 'tuya_local' at custom_components/tuya_local/device.py, line 77: self._api = tinytuya.Device(dev_id, address, local_key), please create a bug report at https://github.com/make-all/tuya-local/issues

**To Reproduce**
appearing at each reboot

**Expected behavior**
just this warning nothing seems unworking

**Additional context**
Global HA Log file with integration in debug mode
[home-assistant_tuya_local_2024-03-18T19-44-51.829Z.log](https://github.com/make-all/tuya-local/files/14641608/home-assistant_tuya_local_2024-03-18T19-44-51.829Z.log)

Device Log of humidifier (i believe error comes from it)
[tuya_local-694351ebbef2e767e3c3497b10af7285-Dehumidifier - E0 - Cave-c4547f6c7a40464bde4842110fdd92e7.json](https://github.com/make-all/tuya-local/files/14641631/tuya_local-694351ebbef2e767e3c3497b10af7285-Dehumidifier.-.E0.-.Cave-c4547f6c7a40464bde4842110fdd92e7.json)

**Comment by make-all** [comment] 2024-03-18 22:15
Duplicate of #407

**Closed by make-all** 2024-03-18 22:15 UTC
