### ISSUE TITLE
Feyree charger temperature problem

### ISSUE THREAD

**Issue by technoman63** [make-all/tuya-local#1798] opened 2024-04-04 15:32 UTC
There is a probleme with the temperature with the Feyree charger, the decimal point was forgotten on the value, for example it shows me 312°C on the integration while on the application the temperature is 31.2°C.

Thank you for your work

![2024-04-04 17_28_40-Board – Home Assistant](https://github.com/make-all/tuya-local/assets/20636868/fad31398-6316-4ed6-9122-d356f41c9654)

**Comment by make-all** [comment] 2024-04-04 23:12
Duplicate of #1795

**Closed** 2024-04-04 23:13 UTC
Labels: bug
