### ISSUE TITLE
HA LOG Entity Warning

### ISSUE THREAD

**Issue by epajfl00** [make-all/tuya-local#998] opened 2023-08-18 01:54 UTC
There is a HA warning, indicating to report to author/owner:
![image](https://github.com/make-all/tuya-local/assets/86779948/ebce8d4e-a0ba-44fd-9e3b-76d4b3a352dc)

Entity None (<class 'custom_components.tuya_local.switch.TuyaLocalSwitch'>) is implicitly using device name by not setting its name. Instead, the name should be set to None, please report it to the custom integration author.

Entity None (<class 'custom_components.tuya_local.siren.TuyaLocalSiren'>) is implicitly using device name by not setting its name. Instead, the name should be set to None, please report it to the custom integration author.

Does this need to be corrected?

**Comment by make-all** [comment] 2023-08-18 05:59
Duplicate of #992

**Closed by make-all** 2023-08-18 05:59 UTC
