### ISSUE TITLE
Error in logs relating to names

### ISSUE THREAD

**Issue by Krispkiwi** [make-all/tuya-local#1010] opened 2023-08-20 11:47 UTC
This error is appearing in the logs in the latest version of Home Assistant and 2023.8.1 of Tuya Local
Entity None (<class 'custom_components.tuya_local.switch.TuyaLocalSwitch'>) is implicitly using device name by not setting its name. Instead, the name should be set to None, please report it to the custom integration author.

**Comment by make-all** [comment] 2023-08-20 12:28
Duplicate of #992

**Closed by make-all** 2023-08-20 12:28 UTC
Labels: bug
