### ISSUE TITLE
Entity None (<class 'custom_components.tuya_local.fan.TuyaLocalFan'>) does not set FanEntityFeature.TURN_ON but implements the turn_on method.

### ISSUE THREAD

**Issue by robinhood-code** [make-all/tuya-local#2243] opened 2024-08-25 23:28 UTC
```
Logger: homeassistant.components.fan
Source: components/fan/__init__.py:295
integration: Fan ([documentation](https://www.home-assistant.io/integrations/fan), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+fan%22))
First occurred: 9:11:31 AM (6 occurrences)
Last logged: 9:11:41 AM

Entity None (<class 'custom_components.tuya_local.fan.TuyaLocalFan'>) does not set FanEntityFeature.TURN_ON but implements the turn_on method. Please create a bug report at https://github.com/make-all/tuya-local/issues
```

**Comment by make-all** [comment] 2024-08-25 23:39
Duplicate of #2164

**Closed by make-all** 2024-08-25 23:39 UTC
