### ISSUE TITLE
device not connecting

### ISSUE THREAD

**Issue by MarioNava1962** [make-all/tuya-local#1462] opened 2023-12-28 10:24 UTC
Greetings
I am having troubules with devise, previusoly connected and working.
I enabled the log and the checked after a while.
I got this message suggesting me to open an issue request.
I attached the diagnostic for one device.

 Logger: homeassistant.util.async_
Source: util/async_.py:140
First occurred: December 27, 2023 at 14:14:57 (3 occurrences)
Last logged: December 27, 2023 at 14:16:32
Detected blocking call to sleep inside the event loop by custom integration 'tuya_local' at custom_components/tuya_local/device.py, line 77: self._api = tinytuya.Device(dev_id, address, local_key), please create a bug report at https://github.com/make-all/tuya-local/issues

[config_entry-tuya_local-54ce7b3081542b75698a4cc2189135ca.json.txt](https://github.com/make-all/tuya-local/files/13785595/config_entry-tuya_local-54ce7b3081542b75698a4cc2189135ca.json.txt)

**Comment by make-all** [comment] 2023-12-28 11:20
Duplicate of #407

**Closed by make-all** 2023-12-28 11:20 UTC
Labels: bug
