### ISSUE TITLE
Madimack Pool Heater no longer working

### ISSUE THREAD

**Issue by mvnixon** [make-all/tuya-local#38] opened 2021-08-15 14:47 UTC
Hi there,

Since upgrading to the latest release of tuya-local, I can no longer control my Madimack pool heater. 

It seems that it still gets discovered according to the log (see below), but then it shows 'unavailable' in Lovelace/Homekit.

`
2021-08-16 00:44:04 INFO (MainThread) [custom_components.tuya_local.device] Creating device: 10568847c82b96120e36
2021-08-16 00:44:04 INFO (MainThread) [custom_components.tuya_local.device] Setting protocol version for Pool Heater to 3.3.
`

Any ideas on how to sort this out?

**Comment by make-all** [comment] 2021-08-17 03:18
Ensure the pool heater is on, and no other device (app) is connected to it.
The Tuya module only supports a single connection, so if the app was started on a phone, it may block Home Assistant until the app is force closed, and if some time has passed, Home Assistant seems to mark the device as offline, and won't retry for quite some time unless you restart Home Assistant.

**Comment by adamkoch** [comment] 2021-11-07 10:44
Running into this as well. All was working fine for the past months and then my Madimack heater is now unavailable as well. My logs show the exact same as @mvnixon. I checked the local key and also all the settings at iot.tuya.com and all looks well.

Has anyone found a fix? Or any suggestions on how to debug more?

The only thing was I did get an email from Tuya that my "Tuya IoT Platform" free trial was expiring (around the same time it stopped working in HA). Not sure if that is related. I see others discussing it as well:
https://community.home-assistant.io/t/email-from-from-tuya-iot-free-trial-is-expiring-today-tuya-official-integration/350181

**Comment by adamkoch** [comment] 2021-11-07 11:10
Ah I think I got it working. Downgrading to v0.11.3 of tuya local in HACs and then removing and re-adding the integration got things going. I guess some issue with the device ID changes as per:
https://github.com/make-all/tuya-local/releases/tag/0.12.0

**Comment by make-all** [comment] 2021-11-07 21:26
The unique id changes would not have affected the Madimack device, as it does not have any secondary entities. There was an update to the underlying version of tinytuya from 1.2.8 to 1.2.9 in 0.12.0 as well but I don't think those changes would have affected a previously working device either.  The "latest version" on Aug 6 when this report was made was 0.9.1, so the original problem does not seem to be related to a change between 0.11.3 and 0.12.0 anyway.  I suspect whatever is happening that removing and re-adding may be the solution independant of which version of the integration you are on.  Removing the device from the integration config, rebooting and re-adding might work also if the problem is a corrupt device config.

**Comment by make-all** [comment] 2021-11-07 21:28
If you have backups of the broken version, it might be interesting to compare the configs for the device in config/.storage/core.config_entries to see what is different.

**Comment by adamkoch** [comment] 2021-11-07 21:57
You are 100% correct! It wasn't the version that made the difference, it was removing and re-adding the integration. I upgraded back to 0.13.0 and the device broke again. I then removed the integration and re-added it and it's all working again 👍

**Comment by make-all** [comment] 2021-11-07 22:15
OK, but it does seem then that there is a problem with the migration for this device. Which is strange, as there does not seem to be a problem in general, and there isn't anything special about this device's config that I can see.

**Comment by adamkoch** [comment] 2021-11-07 22:17
I had upgraded a few versions in the past and had no issue so maybe it was just jumping from one specific version to another and it will work fine in the future.

**Comment by make-all** [comment] 2022-04-03 03:09
There seems to be a workaround available of re-adding the device, and it is unlikely that anyone will provide sufficient info to identify what the actual problem is after all this time, so I am closing this issue.

**Closed by make-all** 2022-04-03 03:09 UTC
Labels: bug
