### ISSUE TITLE
Warning in log AREA_SQAURE_METERS 

### ISSUE THREAD

**Issue by MarcRaynor** [make-all/tuya-local#2650] opened 2024-12-15 23:45 UTC
### Description

HI, I'm not saying this is causing me a specific issue but I saw this in the log.
2024-12-14 06:55:08.318 WARNING (ImportExecutor_0) [homeassistant.const] AREA_SQUARE_METERS was used from tuya_local, this is a deprecated constant which will be removed in HA Core 2025.12. Use UnitOfArea.SQUARE_METERS instead, please report it to the author of the 'tuya_local' custom integration
Thanks for developing this integration. Let me know if you need any other information.
I appologise if this is not the right place to post this, I'm fairly new to HA and GitHub.
Kind regards,
Marc Raynor

### Steps to reproduce

Look at the logs.

### Expected behaviour

Probably not write this to the log.  I'm not complaining I'm just reporting it.

### Confirmation

- [X] I am sure this is a bug or improvement, that is well enough described that it can be implemented.
- [X] If this is for a specific device, the device config is mentioned above, or diagnostics are included.

- [X] Log messages or diagnostics relevant to the issue are included.

- [X] This is not requesting addition of a new device.

**Comment by make-all** [comment] 2024-12-16 01:23
Duplicate of #2596

**Closed by make-all** 2024-12-16 01:23 UTC
