### ISSUE TITLE
Detected blocking call to sleep inside the event loop by custom integration 'tuya_local' 

### ISSUE THREAD

**Issue by JacobsenKim** [make-all/tuya-local#1594] opened 2024-02-03 16:24 UTC
This form is for reporting bugs.  If you have encountered a bug, you should
generally have some log messages or device diagnostics to show something is
going wrong.  If your problem is more of a question or a request for help,
then [Discussions](https://github.com/make-all/tuya-local/discussions) is
probably a more suitable venue.

**Describe the bug**
When a device is not power this error comes up in the log of HA

**To Reproduce**
turn off a device that is add, restart HA and look at the log

**Expected behavior**
not showing up in log and faster boot of HA, it take a long time to boot now, if i turn off  'tuya_local' then im not having the long boot time.

Please check if there are messages from Tuya Local in the Home
Assistant log (Settings / System / Logs), and include those too.

Logdetaljer (ADVARSEL)
Logger: homeassistant.util.async_
Source: util/async_.py:141
First occurred: 16.13.16 (4 occurrences)
Last logged: 16.13.39

Detected blocking call to sleep inside the event loop by custom integration 'tuya_local' at custom_components/tuya_local/device.py, line 77: self._api = tinytuya.Device(dev_id, address, local_key), please create a bug report at https://github.com/make-all/tuya-local/issues

**Comment by make-all** [comment] 2024-02-04 01:08
Duplicate of #407

**Closed by make-all** 2024-02-04 01:08 UTC
