### ISSUE TITLE
Cannot set fan speed to low: error speed (33) must be between 33.333333333333336 and 100.0

### ISSUE THREAD

**Issue by jonatino** [make-all/tuya-local#1014] opened 2023-08-21 14:41 UTC
**Describe the bug**
When trying to set fan speed to low it fails.

![image](https://github.com/make-all/tuya-local/assets/1808569/df5b5d68-3951-4ffb-96ea-971320b867bb)

**To Reproduce**
Setup arlec_ceiling_fan_remote device and try and set speed to low.

**Expected behavior**
Low should work without error.

**Additional context**
```
2023-08-21 10:39:07.496 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140645327007424] speed (33) must be between 33.333333333333336 and 100.0
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 226, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1974, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2011, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 870, in entity_service_call
    response_data = await _handle_entity_call(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 942, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/tuya_local/fan.py", line 121, in async_set_percentage
    values_to_set = self._speed_dps.get_values_to_set(self._device, percentage)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_local/helpers/device_config.py", line 892, in get_values_to_set
    raise ValueError(f"{self.name} ({value}) must be between {mn} and {mx}")

```

**Comment by make-all** [comment] 2023-08-22 06:35
Previous cases like this have been fixed in the config, by allowing speed to go down to 0, since the 0 will be caught and converted to an off command anyway.  But it is probably better to round the values so that 33% is not out of range for a fan with speeds 1-3.

(Issue was caused by the not-yet rounded value of 0.99 being checked if it is in the range 1 <= n <= 3 )

**Closed** 2023-08-22 14:33 UTC

**Comment by jonatino** [comment] 2023-09-02 01:39
Confirmed working. Thank you @make-all
