### ISSUE TITLE
Detected blocking call to scandir with args ('/config/custom_components/tuya_local/devices',) inside the event loop by custom integration 'tuya_local' at custom_components/tuya_local/helpers/device_config.py, line 1010

### ISSUE THREAD

**Issue by HaraldKiessling** [make-all/tuya-local#2621] opened 2024-12-07 15:44 UTC
[home-assistant_tuya_local_2024-12-07T15-32-22.901Z.log](https://github.com/user-attachments/files/18048991/home-assistant_tuya_local_2024-12-07T15-32-22.901Z.log)
### Description

```
2024-12-07 16:26:54.889 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to scandir with args ('/config/custom_components/tuya_local/devices',) inside the event loop by custom integration 'tuya_local' at custom_components/tuya_local/helpers/device_config.py, line 1010: for path, dirs, files in walk(_CONFIG_DIR): (offender: <frozen os>, line 368: ?), please create a bug report at https://github.com/make-all/tuya-local/issues
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#scandir
```

### Confirmation

- [X] I am sure this is a bug or improvement, that is well enough described that it can be implemented.
- [ ] If this is for a specific device, the device config is mentioned above, or diagnostics are included.

- [ ] Log messages or diagnostics relevant to the issue are included.

- [X] This is not requesting addition of a new device.

**Comment by make-all** [comment] 2024-12-08 01:10
Duplicate of #2584

**Closed by make-all** 2024-12-08 01:10 UTC
Labels: bug
