### ISSUE TITLE
AREA_SQUARE_METERS was used from tuya_local, this is a deprecated constant which will be removed in HA Core 2025.12. Use UnitOfArea.SQUARE_METERS instead.

### ISSUE THREAD

**Issue by jacobwoods62** [make-all/tuya-local#2707] opened 2024-12-29 22:34 UTC
### Description

Logger: homeassistant.const
Source: helpers/deprecation.py:222
First occurred: 7:47:38 AM (1 occurrences)
Last logged: 7:47:38 AM

AREA_SQUARE_METERS was used from tuya_local, this is a deprecated constant which will be removed in HA Core 2025.12. Use UnitOfArea.SQUARE_METERS instead, please report it to the author of the 'tuya_local' custom integration

### Confirmation

- [ ] I am sure this is a bug or improvement, that is well enough described that it can be implemented.
- [ ] If this is for a specific device, the device config is mentioned above, or diagnostics are included.

- [ ] Log messages or diagnostics relevant to the issue are included.

- [ ] This is not requesting addition of a new device.

**Comment by make-all** [comment] 2024-12-29 23:00
Duplicate of #2615

**Closed by make-all** 2024-12-29 23:00 UTC
Labels: bug
