### ISSUE TITLE
Add bluetooth devices through gateway 

### ISSUE THREAD

**Issue by Andreasjkoch** [make-all/tuya-local#301] opened 2022-12-03 22:54 UTC
I am trying to connect my Yeeuu K2 Smart Key Lock box. This lock box however uses bluetooth and does not have wifi, so a gateway is needed for accessing it over the internet. This also means that the lock box does not have any local IP, so that the integration cannot find it directly. So my question is, is it possible to add the lock box through the gateway?  The integration does find the gateway, but when trying to add that I just get "Connection to device succeeded but no datapoints found, please try again. Create a new issue and include debug logs if problem persists.". 

I don't know if it matters, but here are the tuya datapoints for the lock box:
bluetooth_unlock | Raw | {}
residual_electricity | Integer | {   "min": 0,   "max": 100,   "scale": 0,   "step": 1 }
unlock_fingerprint | Integer | {   "min": 0,   "max": 999,   "scale": 0,   "step": 1 }
unlock_password | Integer | {   "min": 0,   "max": 999,   "scale": 0,   "step": 1 }
unlock_dynamic | Integer | {   "min": 0,   "max": 999,   "scale": 0,   "step": 1 }
unlock_ble | Integer | {   "min": 0,   "max": 999,   "scale": 0,   "step": 1 }
alarm_lock | Enum | {   "range": [     "wrong_finger",     "wrong_password",     "wrong_card",     "wrong_face",     "tongue_bad",     "too_hot",     "unclosed_time",     "tongue_not_out",     "pry",     "key_in",     "low_battery",     "power_off",     "shock"   ] }
hijack | Boolean | "{true,false}"
lock_motor_state | Boolean | "{true,false}"
unlock_temporary | Integer | {   "min": 0,   "max": 999,   "scale": 0,   "step": 1 }

**Comment by make-all** [comment] 2022-12-04 01:48
This will be dependent on implementation of #70

**Comment by felipecrs** [comment] 2022-12-05 14:14
- I suggest to close as duplicate of https://github.com/make-all/tuya-local/issues/275

**Comment by make-all** [comment] 2022-12-05 23:26
It does contain details for a specific device, though there isn't enough information there yet to implement local protocol support.

**Comment by make-all** [comment] 2023-04-29 15:01
Although this does contain tuya portal details for a subdevice, there are no local protocol details, so this will be closed with the general subdevice support without adding this specific device.

**Closed** 2023-05-07 09:35 UTC
