### ISSUE TITLE
Beca BAC-002 thermostat can't add to Tuya Local

### ISSUE THREAD

**Issue by apiraino87** [make-all/tuya-local#129] opened 2022-02-06 13:32 UTC
Hello, I have already installed a switch with Tuya local but my thermostat get this error:

![image](https://user-images.githubusercontent.com/92855612/152683321-9b8ff195-6dbd-4848-8631-db5325bd591d.png)
 Please, help me :)

**Comment by make-all** [comment] 2022-02-06 20:21
Please check the Home Assistant log.  There may be more details about the problem there.  If IP address is wrong, it may not be able to contact the device at all. If device id is wrong, it may not be getting a response from the device. If local key is wrong, it may not be able to decode the response it gets from the device.

**Comment by yarosman** [comment] 2022-02-19 18:47
I try to add Moes BHT thermostat and nothing work

2022-02-19 20:44:50 WARNING (MainThread) [custom_components.tuya_local.config_flow] Device matches simple_switch with quality of 8%. DPS: {'1': True, '2': 'manual', '10': False, '16': 23, '19': 40, '24': 225, '27': -2, '36': 'open', '43': 'all', '45': 0, '101': 1, '102': '70', 'updated_at': 1645296285.746908}

**Comment by shakin89** [comment] 2022-02-19 20:44
reading this issue you will find how to implent them in HA,
I have 3 beca bac-002-elw fully functional and working. 
I can tell you they haven't a great wifi connection...

**Comment by make-all** [comment] 2022-04-03 03:11
Closing as this seems to be caused by the device's poor WiFi strength.

**Closed by make-all** 2022-04-03 03:11 UTC
Labels: awaiting feedback
