### ISSUE TITLE
Detected blocking call to sleep inside the event loop by custom integration 'tuya_local' 

### ISSUE THREAD

**Issue by wbrione** [make-all/tuya-local#1482] opened 2024-01-06 10:46 UTC
As suggested by the log, I only open the issue as requested...

> Logger: homeassistant.util.async_
> Source: util/async_.py:141
> First occurred: 07:40:09 (6 occurrences)
> Last logged: 07:40:22
> 
> Detected blocking call to sleep inside the event loop by custom integration 'tuya_local' at custom_components/tuya_local/device.py, line 77: self._api = tinytuya.Device(dev_id, address, local_key), please create a bug report at https://github.com/make-all/tuya-local/issues

**Comment by make-all** [comment] 2024-01-06 11:11
Duplicate of #407

**Closed by make-all** 2024-01-06 11:11 UTC
Labels: bug
