### ISSUE TITLE
Request support please for: Orison Low Profile Ceiling Fan

### ISSUE THREAD

**Issue by airwebber** [make-all/tuya-local#1750] opened 2024-03-15 17:12 UTC
# Log Message
<details>
![image](https://github.com/make-all/tuya-local/assets/108987983/44393b9d-d716-4ac0-848c-e713b19b2ccc)
![image](https://github.com/make-all/tuya-local/assets/108987983/37b39df5-46f4-4c84-9f7c-0d99d57c97f1)
</details>

```
This error originated from a custom integration.

Logger: custom_components.tuya_local.config_flow
Source: custom_components/tuya_local/config_flow.py:97
integration: Tuya Local (documentation, issues)
First occurred: 12:03:49 PM (1 occurrences)
Last logged: 12:03:49 PM

Device matches ledkia_fan_light with quality of 62%. DPS: {"updated_at": 1710518626.192288, "20": true, "21": "white", "22": 1000, "23": 0, "24": "000003e803e8", "25": "07464602000003e803e800000000464602007803e803e80000000046460200f003e803e800000000464602003d03e803e80000000046460200ae03e803e800000000464602011303e803e800000000", "26": 0, "60": true, "61": "fresh", "62": 100, "63": "forward", "64": 0, "103": true}
```

```
Code	Type	Values
switch_led	Boolean	
"{true,false}"
work_mode	Enum	
{
  "range": [
    "white",
    "colour",
    "scene",
    "music"
  ]
}
bright_value	Integer	
{
  "min": 10,
  "max": 1000,
  "scale": 0,
  "step": 1
}
temp_value	Integer	
{
  "min": 0,
  "max": 1000,
  "scale": 0,
  "step": 1
}
colour_data	Json	
{}
scene_data	String	
{
  "maxlen": 255
}
countdown	Integer	
{
  "unit": "s",
  "min": 0,
  "max": 86400,
  "scale": 0,
  "step": 1
}
music_data	String	
{
  "maxlen": 255
}
control_data	String	
{
  "maxlen": 255
}
fan_switch	Boolean	
"{true,false}"
fan_mode	Enum	
{
  "range": [
    "fresh",
    "nature"
  ]
}
fan_speed	Integer	
{
  "min": 1,
  "max": 100,
  "scale": 0,
  "step": 1
}
fan_direction	Enum	
{
  "range": [
    "forward",
    "reverse"
  ]
}
countdown_left_fan	Integer	
{
  "unit": "min",
  "min": 0,
  "max": 540,
  "scale": 0,
  "step": 1
}
```

# Information about DPS mappings:

```
"eb625d82272d284c30mjcl"
```

# Product ID: 
"8k3ss1tcresem1bh"

# Information about how the device functions:  

- 【2 in 1 Design】This modern low profile ceiling fan with light can fully save your space while adding the stylish sense of space. And the flush mount ceiling fan is equipped with a whispering wind DC motor that makes no noise, Perfect for low-profile small rooms, like bedrooms, living rooms, kitchens, etc.

- 【Remote & APP Control】The 6 speed & timing settings of the enclosed fan light as well as the stepless dimming light output all from the convenience of the easy-to-use remote control (included) or APP.

- 【Remembers Your Setting】 Our smart ceiling fan light offers three color temperatures-white, neutral, and warm, ranging from 2700K to 6500K. All settings are memorized when turning off lights with the remote control. Color temperature and brightness remain unchanged the next time you use the remote control turn on it.

- 【Unique Designed for Clean】The ceiling fan with remote control considers your cleaning cares,the protective net has been specially designed and can be opened and every part of the ceiling fan can be cleaned to keep it looking like new.

- 【Quality Assurance】We endeavor to provide the best quality products to our customers and value your feedback. You will enjoy a 30-day refund & return policy and a LIFETIME WARRANTY. If you have any question with the purchase, please contact us and we will be there for you.

# Manual or other explanation available online: 
https://www.amazon.com/gp/product/B0B1WPR62M

**Comment by make-all** [comment] 2024-03-16 01:05
Duplicate of #407

**Comment by make-all** [comment] 2024-03-16 01:06
Sorry, I didn't notice the actual log message further down in your message

**Comment by airwebber** [comment] 2024-03-16 01:41
If you need me to provide anything else, please let me know. Thank you for doing all this.

**Closed** 2024-03-27 07:42 UTC

**Comment by airwebber** [comment] 2024-03-27 14:01
I just wanted to say thank you! :)
