### ISSUE TITLE
Cannot add second PIR sensor through Zigbee GW

### ISSUE THREAD

**Issue by damjanev** [make-all/tuya-local#1915] opened 2024-05-13 18:50 UTC
**Describe the bug**
I have one Zigbee gateway devices of the Aliexpress type ("product_id": "5utsqib6s8lw2yxo", "product_name": "多模网关") to which i have connected two PIR sensors ("product_id": "msl6wxk9", "product_name": "人体运动传感器_Zigbee") and two switches with power monitoring ("product_name": "Aubess Smart Socket zEM", "product_id": "hdopuwv6"). I successfuly added both switches without any issues, but was able to only add one of the PIR sensors. First PIR sensor gets added without problems, while the second one reports the generic "Unable to connect to your device with those details. It could be an intermittent issue, or they may be incorrect.". It doesn't matter which gets added first, it is always the second one that is having issues.

**To Reproduce**
Add one PIR sensor through the gateway. Try to add a second one.

**Expected behavior**
All devices gets added successfully. 

**Additional context**
Logs:

Logger: custom_components.tuya_local.device
Source: custom_components/tuya_local/device.py:433
integration: Tuya Local ([documentation](https://github.com/make-all/tuya-local), [issues](https://github.com/make-all/tuya-local/issues))
First occurred: 19:52:44 (14 occurrences)
Last logged: 20:44:35

Test protocol error 901: Network Error: Unable to Connect
Test protocol error 914: Check device key or version

The log entry does not correspond to the reality. The key and the version are correct. If i remove the already added PIR sensor, the other one can be added with the same parameters that failed initially. After this, the first one cannot be added anymore. 

ETA: I have tried changing the version, just in case, but the result is the same. Only the first device gets added (with version 3.4)

ETA2: New info. Removed the PIR device and added a door/window contact sensor ("product_name": "Contact Sensor", "product_id": "au1rjicn"). Now neither PIR sensor can be added until i remove the contact sensor. Gateway issue?

ETA3: New info. I removed all devices from the integration. The two above mentioned Zigbee switches and a couple of WiFi switches. Now i was able to add all 3 Zigbee sensors without issues. Confused...

ETA4: Corrected Zigbee switch/socket product info.

**Comment by make-all** [comment] 2024-05-13 21:40
Duplicate of #1054

**Closed by make-all** 2024-05-13 21:40 UTC
