### ISSUE TITLE
Problem on adding new 3.4 devices: blocking call to sleep inside the event loop

### ISSUE THREAD

**Issue by matteozamu** [make-all/tuya-local#620] opened 2023-04-16 08:10 UTC
**Describe the bug**
I was trying to add a new device to this amazing Tuya integration but I got the generic message in the popup "Unable to connect to your device with those details. It could be an intermittent issue, or they may be incorrect."

So I checked the logs and I found this:

```
Logger: homeassistant.util.async_
Source: util/async_.py:159
First occurred: 09:46:12 (7 occurrences)
Last logged: 10:01:50

Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom integration author for tuya_local doing blocking calls at custom_components/tuya_local/device.py, line 66: self._api = tinytuya.Device(dev_id, address, local_key)
```

![image](https://user-images.githubusercontent.com/51788939/232283975-24b89361-5bcc-41e5-8d98-2c1a2c20b842.png)
![image](https://user-images.githubusercontent.com/51788939/232284007-c7e581e0-2fa2-41e7-a368-bcdd09d9d5c6.png)

**Comment by matteozamu** [comment] 2023-04-16 08:20
I found out that it is happening with devices that have the 3.4 firmware

**Comment by make-all** [comment] 2023-04-16 10:09
No, it is happening because you have not supplied an IP address, so the underlying library goes off and searches for it, and sleeps until it gets a response or timeout because the library does not support asyncio.

**Comment by make-all** [comment] 2023-04-16 10:30
Duplicate of #407

**Closed by make-all** 2023-04-16 10:30 UTC
Labels: bug
