### ISSUE TITLE
Unable to add any new devices

### ISSUE THREAD

**Issue by SmartLifeAbbecourt** [make-all/tuya-local#1900] opened 2024-05-09 19:03 UTC
Hello,

Since last update of HA (2024.5.2) and tuya Local 2024.5.2 I can not add any device with all time same message:

Unable to connect to your device with these settings. This may be an intermittent problem or the settings are incorrect.

Enregistreur: custom_components.tuya_local.config_flow
Source: custom_components/tuya_local/config_flow.py:216
intégration: Tuya Local ([documentation](https://github.com/make-all/tuya-local), [problèmes](https://github.com/make-all/tuya-local/issues))
S'est produit pour la première fois: 20:35:06 (2 occurrences)
Dernier enregistrement: 20:47:12
Connection test failed with <class 'OSError'> [Errno 98] Address in use

Also, first version IP adresse / host name was prefilled with "Auto".

That is not the case now, so what is the host name or ip to fill here? I try 88.162.214.201 found on device detail query and also IP 192.168.1.58 found from scaning my box but same failure.

here data from my device:
    "active_time": 1715115257,
    "bind_space_id": "71966963",
    "category": "pir",
    "create_time": 1715111784,
    "custom_name": "",
    "icon": "smart/icon/ay1565138036928sSi0S/d065134f80b56f89bbdd25854c81bcf1.jpg",
    "id": "bf589874494e1c5c99xn6h",
    "ip": "88.162.214.201",
    "is_online": true,
    "lat": "49.3700",
    "local_key": "U(:4EUL9+JY/JYTH",
    "lon": "2.1600",
    "model": "FH_PIR400A-CBU",
    "name": "Détecteur infrarouge multifonctionnel",
    "product_id": "lokl35ptqxauik7x",
    "product_name": "多功能红外探测器",
    "sub": false,
    "time_zone": "+02:00",
    "update_time": 1715115257,
    "uuid": "9505747944304d69"
  
Thank you for your help
Philippe

**Comment by make-all** [comment] 2024-05-09 19:14
Duplicate of #408 

For IP address, you should use the local address (the 192.168. prefixed one).  You may also need to fill the protocol to get your device working (the devices will also recover from network errors quicker if you do that).

Finally, if your devices contain low end tuya modules, they may only support one local connection. The same thing that is blocking auto address discovery may be blocking the local connection.

**Closed** 2024-05-09 19:15 UTC

**Comment by SmartLifeAbbecourt** [comment] 2024-05-09 20:58
Thank you but still not working, I have no local tuya installed and no local using it.

Using tinytuya I get information what I need:

Détecteur infrarouge multifonctionnel   Product ID = lokl35ptqxauik7x  [Valid Broadcast]:
    Address = 192.168.1.58   Device ID = bf589874494e1c5c99xn6h (len:22)  Local Key = _v@TdrKOt2{/s.ue  Version = 3.4  Type = default, MAC = 18:de:50:60:5f:e3

but filling all of that, I get same error, it s probably device problem. I will replace it, I will see.

**Comment by make-all** [comment] 2024-05-09 21:26
If tinytuya can connect, then tuya-local should be abe to connect, as it uses tinytuya under the covers. But something seems to be blocking it.
Protocol version 3.4 definitely needs to be explicitly declared.

**Comment by SmartLifeAbbecourt** [comment] 2024-05-09 21:34
I declare the protocol version 3.4 but same result. I don't know what can block it

**Comment by SmartLifeAbbecourt** [comment] 2024-05-09 21:47
With wizard tinytuya I received :
[Détecteur infrarouge mult] 192.168.1.58       - No Response

So it can not be add to tuya local, Still to understand why no response
