### ISSUE TITLE
Aquatech Heat pump

### ISSUE THREAD

**Issue by Mrsash2020** [make-all/tuya-local#1922] opened 2024-05-16 10:35 UTC
**Describe the bug**
Wanted to ask about another device but thought I can make it quick if ok. I am not sure how these things work so bear with me. 

I have a new heat pump. I got it installed as it is tuya compatible. I have managed to add it in HA and using a tile card since don't have any options. Not sure if there are any other options

https://www.aquatechheatpumps.com.au/dynamic

The  issue is the current water temp in the tank seems to indicate for example 17deg C which is not the current water temperature. Tuya shows me correct values. I have added screens of tuya app and also another screen in tuya which has other diagnostic temps etc.
Added HA screen showing the incorrect temperature as well.

So basically trying to figure out if the heat pump developer has stuffed up or is the data being read incorrectly by the integration. If the issue is the developer of the heat pump I can try and chase it up but the tuya app shows the info correctly, so was thinking something to do with integration and how it gets the data. I could be wrong...

I also note the tile card does not correctly show the heat pump modes. They should be Stand Water, Eco Water, Hyb Water, Hyb1 Water, ELE Water as per tuya but does have different names. 

**Expected behavior**
Correct temp in the tank shown.

**Additional context**

If the bug involves a device, then please include device diagnostics from
[config_entry-tuya_local-f5914d7e4059e1d693c31106ad430b9a.json](https://github.com/make-all/tuya-local/files/15333719/config_entry-tuya_local-f5914d7e4059e1d693c31106ad430b9a.json)

Please check if there are messages from Tuya Local in the Home
Assistant log (Settings / System / Logs), and include those too. None

![20240516_201805](https://github.com/make-all/tuya-local/assets/62192773/98c92995-004a-4065-b305-2fec6b36b7b7)
![Screenshot_20240516_201656_Tuya Smart](https://github.com/make-all/tuya-local/assets/62192773/39b2fe8c-516e-4641-be1c-40dbba122fec)
![Screenshot_20240516_201726_Tuya Smart](https://github.com/make-all/tuya-local/assets/62192773/c6c2b8b0-6b95-408d-ab60-0457593d1e21)

**Comment by make-all** [comment] 2024-05-16 22:14
This seems to be caused by PR #1686, which switched the displayed temperature from outlet to inlet temperature, because it matched what was displayed in their app, and they were getting garbage for the outlet temperature.

If the value in that case is always -50, then maybe it can be made conditional.

**Comment by make-all** [comment] 2024-05-16 22:37
Outlet temperature is reported as -50, same as the original report, but your device seems to be reporting an additional dp 16 with data matching the current temperature in your screenshots.  I have added this as the primary current_temperature, with a redirect to inlet temperature when it is missing (as in the original report for this device).

The mode naming is based on predefined modes in Home Assistant. My preference is to fit in with HA rather than strictly following Tuya.

Stand (abbreviation for Standard) = Heat pump
HYB = High demand
HYB1 = Performance
ELE = Electric

The decision of which Hybrid option was which was based on the description in the manual, but this was for the Gen5 device.

**Comment by Mrsash2020** [comment] 2024-05-16 23:09
The modes I am ok with I guess as its not too much of an issue but the temperature I have no idea what you mean. So water temperature data is missing?

**Comment by matheuscanela** [comment] 2024-05-24 13:12
I also notice the same issue on mine, I can see the bug fixed in the code, do you know when it is going to be merged?

**Comment by make-all** [comment] 2024-05-24 13:31
It is merged already

**Comment by matheuscanela** [comment] 2024-05-24 13:46
sorry, I meant released

**Closed** 2024-05-25 14:54 UTC

**Comment by Mrsash2020** [comment] 2024-05-26 06:20
> It is merged already

I was wondering why mine wasn't showing. I had to again go to hacs for the update to show. Curious when was it released? 

BTW thank you so much for fixing this.
