### ISSUE TITLE
Request support for [UanTii Smart Wifi IR Remote Controller Infrared Universal]

### ISSUE THREAD

**Issue by Nas-au** [make-all/tuya-local#847] opened 2023-06-28 04:16 UTC
# Information about DPS mappings

```
{
  "result": {
    "properties": [
      {
        "code": "ir_send",
        "custom_name": "",
        "dp_id": 201,
        "time": 1687894256155,
        "value": ""
      },
      {
        "code": "ir_study_code",
        "custom_name": "",
        "dp_id": 202,
        "time": 1687894256155
      }
    ]
  },
  "success": true,
  "t": 1687925653845,
  "tid": "3d86a565156a11ee9b65f25b5112df17"
}
```

# Product ID
    "model": "S06，S18通用",
    "name": "Smart IR",
    "product_id": "mjffeakbzlnfxpzt"

# Information about how the device functions

**Comment by make-all** [comment] 2023-06-28 07:38
IR remotes are not supported at this time.  It may be possible to use pre-programmed devices as sub devices, but so far the IR gateways that have been studied do not return any datapoints for IR devices, so they are impossible to detect.

**Comment by Nas-au** [comment] 2023-07-02 15:12
> IR remotes are not supported at this time. It may be possible to use pre-programmed devices as sub devices, but so far the IR gateways that have been studied do not return any datapoints for IR devices, so they are impossible to detect.

Thanks you for you response.

**Comment by make-all** [comment] 2023-12-29 06:51
QueryThingsDataModel result of the device I have here (different model, but may help in figuring out the missing details in the above docs.
```
{
  "result": {
    "model": "{\"modelId\":\"000003fa6f\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[
{\"abilityId\":101,\"accessMode\":\"ro\",\"code\":\"temp_current\",\"description\":\"\",\"extensions\":{\"attribute\":\"2\",\"trigger\":\"direct\"},\"name\":\"温度\",\"typeSpec\":{\"max\":800,\"min\":-200,\"scale\":1,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":-200,\"unit\":\"℃\"}},
{\"abilityId\":102,\"accessMode\":\"ro\",\"code\":\"humidity_value\",\"description\":\"\",\"extensions\":{\"attribute\":\"2\",\"trigger\":\"direct\"},\"name\":\"湿度\",\"typeSpec\":{\"max\":100,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"%\"}},
{\"abilityId\":201,\"accessMode\":\"rw\",\"code\":\"ir_send\",\"description\":\"\",\"extensions\":{\"attribute\":\"128\"},\"name\":\"红外控制下发\",\"typeSpec\":{\"maxlen\":3072,\"type\":\"string\",\"typeDefaultValue\":\"\"}},
{\"abilityId\":202,\"accessMode\":\"ro\",\"code\":\"ir_study_code\",\"description\":\"\",\"extensions\":{\"attribute\":\"128\"},\"name\":\"红外学习值上报\",\"typeSpec\":{\"maxlen\":128,\"type\":\"raw\"}}]}]}"
  },
  "success": true,
  "t": 1703832547488,
  "tid": "5cec039fa61611eead0c9aea27a974a5"
}
```

**Comment by make-all** [comment] 2023-12-30 16:04
IR support will be available in the next release, but unfortunately this device can still not be supported due to limitations in the way devices are detected.

Basically the two dps supported by this device are: 
201: not reported by the device, only for sending commands to the device.
202: only reported when the device is in learning mode and an IR signal is received.

**Comment by make-all** [comment] 2024-08-16 09:53
Seems like a duplicate of https://github.com/make-all/tuya-local/issues/507#issuecomment-1528889860 where setting the protocol to 3.2 was required to make a Pet feeder work.

**Comment by felipecrs** [comment] 2024-11-03 16:09
In my case, Tuya Local discovers the device (using cloud) and reaches the adding phase but doesn't get passed that.

![image](https://github.com/user-attachments/assets/47cbdc5f-2356-46be-9321-7202d03c3d77)

```
2024-11-03 13:02:01.246 DEBUG (MainThread) [custom_components.tuya_local.device] Refreshing device state for Test
2024-11-03 13:02:01.246 INFO (MainThread) [custom_components.tuya_local.device] Setting protocol version for Test to 3.3
2024-11-03 13:02:04.336 DEBUG (SyncWorker_11) [custom_components.tuya_local.device] Test refreshed device state: {"Error": "Network Error: Unable to Connect", "Err": "901", "Payload": null}
2024-11-03 13:02:04.336 WARNING (SyncWorker_11) [custom_components.tuya_local.device] Test protocol error 901: Network Error: Unable to Connect
2024-11-03 13:02:04.336 DEBUG (SyncWorker_11) [custom_components.tuya_local.device] new state (incl pending): {"updated_at": 1730649724.336469}
```

**Comment by make-all** [comment] 2024-11-03 22:12
Did you force close the mobile app after scanning the qr code? Or do the step with WiFi disabled on your mobile device?

**Comment by felipecrs** [comment] 2024-11-04 01:19
Yes, I actually tried everything. Since I am not able to make tinytuya get useful data of from the device, I suppose there's nothing this integration can do either, right?

See: https://github.com/jasonacox/tinytuya/issues/554#issuecomment-2453674732

**Comment by make-all** [comment] 2024-11-04 02:02
If the device returns no info, it is currently not possible to use with this integration, and falls under the same issue as this, which is still open for future enhancement to be made to allow supporting such devices that have send only dps (and only return info when put into learning mode)

**Comment by felipecrs** [comment] 2024-11-04 02:16
You are right! When I put it into learning mode, I can get one dp:

```
{'dps': {'201': '{"control":"study"}'}, 't': 12}
```

**Closed** 2024-12-12 13:49 UTC
