### ISSUE TITLE
Antela Smart plug updating slow (is there an interval setting for yaml?)

### ISSUE THREAD

**Issue by Kulturnilpferd** [make-all/tuya-local#286] opened 2022-11-24 17:11 UTC
Hey there,
I have bought some Antela Smart Plugs, they're get well recognized with smartplugv2.yaml but after it updates 3 times every 5 minutes it stopped updating. After I plugged it in it update the first 2-3 Times (only every 5 Minutes) but then it got stuck on 93,2W. This is not the behaviour I would expect from "Smart Switch Gotchas", so maybe someone could point out where to get me a hint to add an update interval to the yaml config or an extended error log to see what's going wrong...

PS:
Ah sorry and totally forgot to tell that the switches are cut off from the internet by mac-address filtering

**Comment by Kulturnilpferd** [comment] 2022-11-24 17:28
Update: It is updating (gosh what an englich :D) but very slow. Is there a way to add a scan interval or increase it in smartplugv2.yaml or globally (doesn't mind if it is specifig or the whole eco system)?

**Comment by make-all** [comment] 2022-11-26 07:50
Basically this issue is a duplicate of issue #176, but it is likely being made worse by the fact that you are blocking network access for the device (which would be device behaviour that is outside our control).

**Closed by make-all** 2022-11-26 07:50 UTC
Labels: device behaviour
