### ISSUE TITLE
Hello, can you support humidifier

### ISSUE THREAD

**Issue by superman110** [make-all/tuya-local#16] opened 2021-05-24 16:30 UTC
The following information is obtained from IOT Tuya and rospogrigio / localtuya:

DPS                                 Function description     Code                   Type              Value range

"2 (value: middle)",           Humidifier Intensity    mode	                Enum	      {"range":["small","middle","large"]}
"3 (value: cancel)",            Timer(Hours)                                                             
"4 (value: 0)",                    Timer(Minutes)                                                         
"9 (value: 0)",                    Low Water Level                                                     
"10 (value: True)",             Master switch             switch	                Boolean	      {true,false}           
"12 (value: humidity)",      Work Mode	            spray_mode	        Enum	      {"range":["sleep","humidity","work"]}
"15 (value: 65)",                Set Humidity             humidity_set	        Integer	      {"unit":"%","min":40,"max":90,"scale":0,"step":1}
"16 (value: 65)",                Current  Humidity                     
"22 (value: True)"              UV Lamp                   sterilization          Boolean	      {true,false}

dp's 3 and 4 – it is timer setting. 3 – in hours, 4 – in minutes. When timer is no set, then dp_3 have value 'cancel'.

Can you add support?  Thank you !

**Comment by make-all** [comment] 2021-05-30 10:11
Do you have any identifying name for this device?

**Comment by superman110** [comment] 2021-05-31 13:00
> Do you have any identifying name for this device?

It's QT-JS2014

details:
https://www.alibaba.com/product-detail/2021-Newest-White-Led-Display-Constant_1600227334261.html?spm=a2700.galleryofferlist.normal_offer.d_title.3ef86ed93Reg5Q

iot.tuya.com debug info

{
  "result": {
    "category": "jsq",
    "functions": [
      {
        "code": "spray_mode",
        "type": "Enum",
        "values": "{\"range\":[\"sleep\",\"humidity\",\"work\"]}"
      },
      {
        "code": "switch",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "mode",
        "type": "Enum",
        "values": "{\"range\":[\"small\",\"middle\",\"large\"]}"
      },
      {
        "code": "sterilization",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "humidity_set",
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":40,\"max\":90,\"scale\":0,\"step\":1}"
      }
    ],
    "status": [
      {
        "code": "spray_mode",
        "type": "Enum",
        "values": "{\"range\":[\"sleep\",\"humidity\",\"work\"]}"
      },
      {
        "code": "switch",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "mode",
        "type": "Enum",
        "values": "{\"range\":[\"small\",\"middle\",\"large\"]}"
      },
      {
        "code": "sterilization",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "humidity_current",
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      },
      {
        "code": "humidity_set",
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":40,\"max\":90,\"scale\":0,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1622465858360
}

**Comment by make-all** [comment] 2021-05-31 22:27
Thanks.  About the only one that isn't described by the schema above is the "9": (value 0) Low water level.
I suspect this is a bad translation, and is actually a tank full indicator, similar to the Goldair dehumidifier.  In the Goldair case, it seems to be an error code bitfield (and I think I saw the schema in the past, where it was documented as "Error"), with the only observed values being 0 (no error) and 8 (tank full or removed).

Can you confirm this by 1) removing the tank and polling the dps values. 2) filling up the tank and polling the dps values.

The tank full status is useful to have for notifications, so if you can confirm it the integration will be more useful.

**Comment by make-all** [comment] 2021-05-31 22:44
I just realised, this is a humidifier rather than a dehumidifier, so the "low water level" will be correct.  I just need the value for it then.

**Comment by make-all** [comment] 2021-06-01 06:50
I've released 0.5.3 just now, with support for this device as a climate device.  

I will replace this sometime in the future with a proper humidifier device implementation, but currently it is not a supported device type so this was quicker. 

A climate device also gives access to the fan mode ("mode" above), which would become read-only for a humidifier device, but it seems the presets ("spray_mode" above) may already cover this with Sleep corresponding to Small, and Work corresponding to Large.  Possibly, like the Goldair dehumidifier, these presets force the fan mode to a specific value, and only the middle preset lets you control the fan separately, making the two controls a bit redundant.

**Comment by superman110** [comment] 2021-06-01 13:14
Thank your job
I have tested the state of water shortage, "9 (value: 0)" becomes 1, it should be a binary sensor, and "15 (value: 65)" becomes unavailable at the same time

**Comment by superman110** [comment] 2021-06-01 14:07
I test released 0.5.3, "Set Humidity" Cannot be set, "Timer" and "UV Lamp Switch" have no control buttons are displayed on the climate panel interface

log in HA:
2021-06-01 21:43:34 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Pureenjoy Humidifier for climate
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 269, in async_setup
result = await component.async_setup_entry(hass, self) # type: ignore
File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 162, in async_setup_entry
return await hass.data[DOMAIN].async_setup_entry(entry)
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 164, in async_setup_entry
raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!
2021-06-01 21:50:01 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547991721248] async_set_humidity() got an unexpected keyword argument 'humidity'
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 167, in handle_call_service
await hass.services.async_call(
File "/usr/src/homeassistant/homeassistant/core.py", line 1481, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1516, in _execute_service
await handler.job.target(service_call)
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
await self.hass.helpers.service.entity_service_call(
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
future.result() # pop exception if have
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 726, in async_request_call
await coro
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 689, in _handle_entity_call
result = hass.async_run_job(partial(getattr(entity, func), **data)) # type: ignore
File "/usr/src/homeassistant/homeassistant/core.py", line 443, in async_run_job
return self.async_run_hass_job(HassJob(target), *args)
File "/usr/src/homeassistant/homeassistant/core.py", line 427, in async_run_hass_job
return self.async_add_hass_job(hassjob, *args)
File "/usr/src/homeassistant/homeassistant/core.py", line 361, in async_add_hass_job
task = self.loop.create_task(hassjob.target(*args))
TypeError: async_set_humidity() got an unexpected keyword argument 'humidity'

**Comment by make-all** [comment] 2021-06-01 22:28
It seems you have some config duplication, perhaps from an earlier attempt to get the humidifier working.
Please delete everything referring to the device from your configuration.yaml, restart HA, and check for any entities realted to it in the Configuration UI, and delete them before trying to add it again.

The other error is coming from the front end, I just tried Call Service from the Developer UI to set the humidity on my dehumidifier here, and it does not give that error, so it may be related to the earlier failure to properly initialise the device.

**Comment by make-all** [comment] 2021-06-02 00:08
Regarding the water level sensor, the tuya protocol is sending it as 0 or 1, and we don't know if there are other values used to indicate other less usual errors as well, so for the integration, I'd rather not make it a binary sensor.  You can use a template sensor to pull out the attribute into its own binary sensor if you find that more convenient to work with.

**Comment by make-all** [comment] 2021-06-02 10:33
I've fixed the UV Switch, I had typed the wrong dps in for that field. Also added a descriptive field for the Water Low state.

I also went ahead and implemented the humidifier entity type. I've added it into the config keeping the climate entity there - they control the same DPS values, so there may be some conflict if you leave both configured, especially if you have automations.

Advantage of the humidifier type is that the default lovelace card can control the humidity.
The disadvantage is that it is lacking fan support, and also support for reporting current temperature and humidity, though I have added those as attributes, so they are available to automations and to some card types.  I guess next I'll have to implement sensor entities so I can export these properly, and also the Tank as a binary sensor as you requested.

**Comment by superman110** [comment] 2021-06-02 13:48
I have deleted the localtuya components and tested 0.6.0. The humidity setting is still unavailable. The UV lamp has no switch. The humidifier card looks like the following:
![2](https://user-images.githubusercontent.com/1772988/120490493-05626f00-c3eb-11eb-8518-3e803c87c723.JPG)
![3](https://user-images.githubusercontent.com/1772988/120490536-0eebd700-c3eb-11eb-9a95-cf2905c07ab5.JPG)

debug log:
2021-06-02 21:11:18 DEBUG (MainThread) [custom_components.tuya_local] Setting up entry for device: 03800086483fda90b427
2021-06-02 21:11:18 INFO (MainThread) [custom_components.tuya_local.device] Creating device: 03800086483fda90b427
2021-06-02 21:11:18 INFO (MainThread) [custom_components.tuya_local.device] Setting protocol version for Pureenjoy Humidifier to 3.3.
2021-06-02 21:11:22 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config andersson_gsh_heater.yaml
2021-06-02 21:11:22 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Loaded device config eanons_humidifier.yaml
2021-06-02 21:11:22 DEBUG (MainThread) [custom_components.tuya_local.humidifier] Adding humidifier device for eanons_humidifier
2021-06-02 21:12:27 DEBUG (SyncWorker_13) [custom_components.tuya_local.device] Refreshing device state for Pureenjoy Humidifier.
2021-06-02 21:12:27 DEBUG (SyncWorker_13) [custom_components.tuya_local.device] Pureenjoy Humidifier refreshed device state: {"devId": "03800086483fda90b427", "dps": {"2": "middle", "3": "cancel", "4": 0, "9": 0, "10": false, "12": "work", "15": 40, "16": 66, "22": false, "updated_at": 1622639547.2252648}}
2021-06-02 21:12:27 DEBUG (SyncWorker_13) [custom_components.tuya_local.device] new cache state (including pending properties): {"2": "middle", "3": "cancel", "4": 0, "9": 0, "10": false, "12": "work", "15": 40, "16": 66, "22": false, "updated_at": 1622639547.2252648}
2021-06-02 21:12:28 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Eanons/pureenjoy Humidifier: Mapped dps 12 value from work to boost
2021-06-02 21:12:28 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Eanons/pureenjoy Humidifier: Mapped dps 2 value from middle to medium
2021-06-02 21:12:28 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Eanons/pureenjoy Humidifier: Mapped dps 9 value from 0 to OK
2021-06-02 21:13:25 DEBUG (SyncWorker_7) [custom_components.tuya_local.device] Refreshing device state for Pureenjoy Humidifier.
2021-06-02 21:13:25 DEBUG (SyncWorker_7) [custom_components.tuya_local.device] Pureenjoy Humidifier refreshed device state: {"devId": "03800086483fda90b427", "dps": {"2": "middle", "3": "cancel", "4": 0, "9": 0, "10": false, "12": "work", "15": 40, "16": 66, "22": false, "updated_at": 1622639605.7587986}}
2021-06-02 21:14:49 DEBUG (SyncWorker_10) [custom_components.tuya_local.device] new cache state (including pending properties): {"2": "middle", "3": "cancel", "4": 0, "9": 0, "10": false, "12": "work", "15": 40, "16": 66, "22": false, "updated_at": 1622639689.9826572}
2021-06-02 21:14:49 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Eanons/pureenjoy Humidifier: Mapped dps 12 value from work to boost
2021-06-02 21:14:49 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Eanons/pureenjoy Humidifier: Mapped dps 2 value from middle to medium
2021-06-02 21:14:49 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Eanons/pureenjoy Humidifier: Mapped dps 9 value from 0 to OK
2021-06-02 21:15:27 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [548009184176] async_set_humidity() got an unexpected keyword argument 'humidity'
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 167, in handle_call_service
await hass.services.async_call(
File "/usr/src/homeassistant/homeassistant/core.py", line 1481, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1516, in _execute_service
await handler.job.target(service_call)
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
await self.hass.helpers.service.entity_service_call(
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
future.result() # pop exception if have
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 726, in async_request_call
await coro
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 689, in _handle_entity_call
result = hass.async_run_job(partial(getattr(entity, func), **data)) # type: ignore
File "/usr/src/homeassistant/homeassistant/core.py", line 443, in async_run_job
return self.async_run_hass_job(HassJob(target), *args)
File "/usr/src/homeassistant/homeassistant/core.py", line 427, in async_run_hass_job
return self.async_add_hass_job(hassjob, *args)
File "/usr/src/homeassistant/homeassistant/core.py", line 361, in async_add_hass_job
task = self.loop.create_task(hassjob.target(*args))
TypeError: async_set_humidity() got an unexpected keyword argument 'humidity'

**Comment by superman110** [comment] 2021-06-02 14:16
Thank you again for your job

Explain "humility" mode in spray_ mode("12 (value: humidity)") it is not normal mode, it should be constant humidity mode, which means to keep running at the set humidity,"work" mode is the working mode, which means to stop running at the set humidity, not the boost mode

btw:
mode("2 (value: middle)") ,It's the amount of mist from the humidifier,and it can also be understood as fan speed

**Comment by make-all** [comment] 2021-06-02 21:34
OK, I've reproduced the humidity setting problem, it seems the frontend is using keyword args for this, so the parameter name needs to match exactly.  I will modify and make a new release today.  For the UV light, you need to enable the switch entity on the device (in Configuration/Integrations, select the device in Tuya Local box, and choose Options to change which entites are enabled).  Maybe it can be modelled as a light, I did not think of that, but the functionality is the same since it only has on/off capabiities, and you probably don't want it included in automations for "turn on all lights".

I mapped humidifier intensity mode to fan_mode because the climate entity in HA supports adjusting fan, swing and preset, and I thought fan was closest match.  But for humidifier entity, there is no fan support, so it is better to change it to "intensity_mode" I guess. Maybe you need to include both the climate and humidifier entities for now to be able to adjust this.

For the presets (spray_mode), do all modes allow setting intensity, or only the "work" mode?  My guess is that Sleep mode forces "small" intensity to stay quiet, and Humidify mode automatically adjusts intensity to keep constant humidity, would that be correct?

If it is correct, then in my future plan I plan to support pairing of DPS so that the Home Assistant mode could control spray mode and intensity mode together like:

Sleep: spray_mode="sleep"
Auto: spray_mode="humidify"
Eco: spray_mode="work", intensity_mode="small"
Normal: spray_mode="work", intensity_mode="middle"
Boost: spray_mode="work", intensity_mode="large"

I tried to use standard mode names from https://github.com/home-assistant/core/blob/dev/homeassistant/components/humidifier/const.py:

- MODE_NORMAL = "normal"
- MODE_ECO = "eco"
- MODE_AWAY = "away"
- MODE_BOOST = "boost"
- MODE_COMFORT = "comfort"
- MODE_HOME = "home"
- MODE_SLEEP = "sleep"
- MODE_AUTO = "auto"
- MODE_BABY = "baby"

Different mode names is technically possible, but there will be no translations in the UI if they are not part of the base Home Assistant mode set.

**Comment by superman110** [comment] 2021-06-03 12:39
Thank you. setting the target humidity can be controlled. I have selected the switch and humidifier options at the same time. The switch entity cannot be used. The UV lamp is not mapped to the switch entity
![1](https://user-images.githubusercontent.com/1772988/120646006-a87abd80-c4ab-11eb-871f-3200c0ed0e51.JPG)
![2](https://user-images.githubusercontent.com/1772988/120646064-b7fa0680-c4ab-11eb-8b85-0344ea7653b0.JPG)

**Comment by make-all** [comment] 2021-06-04 06:49
I'm not sure why the second switch is showing up as disabled.  I double checked, the switch is set to dps 22, and that matches your original request and the logs you've posted since.  The unit tests are passing, so the config seems correct for a switch. 

The only think I can think of is that the only switches I have for testing here are with power monitoring, and maybe the generic switch containing a function for power that returns None in your case is causing a problem in Home Assistant. If you have anything in the logs it would help confirm if that is the problem.

**Comment by superman110** [comment] 2021-06-04 12:19
Your guess is correct, the switch can not be used because there is no power attribute


2021-06-04 20:15:41 ERROR (MainThread) [homeassistant.components.switch] Error adding entities for domain switch with platform tuya_local
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 364, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 558, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 581, in add_to_platform_finish
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 334, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 370, in _async_write_ha_state
attr.update(self.state_attributes or {})
File "/usr/src/homeassistant/homeassistant/components/switch/__init__.py", line 107, in state_attributes
value = getattr(self, prop)
File "/config/custom_components/tuya_local/generic/switch.py", line 87, in current_power_w
if self._power_dps is None:
AttributeError: 'TuyaLocalSwitch' object has no attribute '_power_dps'
2021-06-04 20:15:41 ERROR (MainThread) [homeassistant.components.switch] Error while setting up tuya_local platform for switch
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 239, in _async_setup_platform
await asyncio.gather(*pending)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 364, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 558, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 581, in add_to_platform_finish
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 334, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 370, in _async_write_ha_state
attr.update(self.state_attributes or {})
File "/usr/src/homeassistant/homeassistant/components/switch/__init__.py", line 107, in state_attributes
value = getattr(self, prop)
File "/config/custom_components/tuya_local/generic/switch.py", line 87, in current_power_w
if self._power_dps is None:
AttributeError: 'TuyaLocalSwitch' object has no attribute '_power_dps'

**Comment by make-all** [comment] 2021-06-04 21:14
Oh, its a bug, The power dps should be None when it doesn't exist in the config, but it is not even initialised.

**Comment by make-all** [comment] 2021-06-05 02:42
I hope this issue is fixed in 0.6.2.

I will add a proper fan entity in soon, so you can control the intensity as a "fan" without needing to configure a climate entity.  And also move some of the more important attributes out to their own sensors (current humidity mainly), as after reading the discussions about why the humidifier entity is lacking in features compared with the climate entity, it seems the modern way is to implement everything in separate smaller entities tied together by being attached to the same device.

**Comment by superman110** [comment] 2021-06-05 03:00
Thanks, UV lamp is ready to use in 0.6.2

**Closed** 2021-06-05 03:38 UTC
Labels: New Device
