### ISSUE TITLE
Use UnitOfArea.SQUARE_METERS instead, please report it to the author of the 'tuya_local' custom integration

### ISSUE THREAD

**Issue by Lexx178** [make-all/tuya-local#2627] opened 2024-12-08 19:43 UTC
### Description

2024-12-07 23:37:31.430 WARNING (ImportExecutor_0) [homeassistant.const] AREA_SQUARE_METERS was used from tuya_local, this is a deprecated constant which will be removed in HA Core 2025.12. Use UnitOfArea.SQUARE_METERS instead, please report it to the author of the 'tuya_local' custom integration

Read this in logs, and write to tuyalocal author. Sorry if i did bad.

### Steps to reproduce

 OS Version:               Home Assistant OS 13.2
 Home Assistant Core:      2024.12.0
Tuya Local 2024.11.4

### Confirmation

- [X] I am sure this is a bug or improvement, that is well enough described that it can be implemented.
- [ ] If this is for a specific device, the device config is mentioned above, or diagnostics are included.

- [X] Log messages or diagnostics relevant to the issue are included.

- [X] This is not requesting addition of a new device.

**Comment by make-all** [comment] 2024-12-08 23:01
Duplicate of #2596

**Closed** 2024-12-08 23:04 UTC
