### ISSUE TITLE
Kyvol E30 vacuum no further action possible

### ISSUE THREAD

**Issue by SvenMartin81** [make-all/tuya-local#338] opened 2023-01-06 07:33 UTC
Hi,
everything was running fine until somewhere. I wanted to start the vacuum but nothing happend.
I don't know what I can do....all the entities are right there but I cannot use them...the vacuum is always doing nothing...
I deleted the integration and reinstalled it....but nothing changed....
The only thing I changed was, that I deleted my vaccum from the tuya app.... I added it again but the localkey was another. could this be the reason?

any idea?

**Comment by make-all** [comment] 2023-01-06 08:49
Yes, if you re-pair with the app, the local key needs to be updated.

**Comment by SvenMartin81** [comment] 2023-01-06 08:51
hi,
but why do I need the caccum in the app....I thought that this is local tuya and I only need the localkey....means i need to have the vacuum always in the app?

**Comment by make-all** [comment] 2023-01-06 08:54
Pairing with an app is what causes the device to generate a local key.

**Comment by SvenMartin81** [comment] 2023-01-06 09:39
yes, I know. I got the local key through the developer accound from tuya.
But why can't I use my vaccum any more....? there is no fault noticed. I can use it through the smartlife app but not through HA....

**Comment by make-all** [comment] 2023-01-07 01:18
I am unable to answer questions about the internal workings of Tuya devices and the Tuya ecosystem.  But since the problems started when you removed the device from your app, I think the cause of the problem is sufficiently clear that this can be closed.

**Comment by SvenMartin81** [comment] 2023-01-23 18:19
Hi, the Problem is again. My vacuum has only some Switches and a Sensor for infrated. No Control for my vacuum. I deleted again and got the vacuum in the smartlife App again. I noticed the uiid and the all the things i Need . But everytime i only get some switches….. What is goning wrong there?

**Comment by make-all** [comment] 2023-01-23 23:55
I'm not really sure if I am understanding the issue correctly, but I have noticed a potential issue with PR #269 which could cause detection issues, since a previously optional dp was made mandatory.

**Comment by SvenMartin81** [comment] 2023-01-24 18:20
Hi,
Yes could be a similar problem. The DPs are Not correct managed through the integration. By looking into the tuya Cloud Information there is all ok. The DPs are the Same as one year ago.

**Comment by SvenMartin81** [comment] 2023-01-24 18:21
But the Tuya integration…. It is Not only your Integration. The Same thing with the other integration. I get only Switches and Sensors but nothing has to do with a vacuum.

**Comment by make-all** [comment] 2023-01-25 08:54
I don't know what you mean by "the other integration", so I can't parse your last comment.

I suggest trying the "main" version I just committed yesterday, as that should restore the config back to match as it did originally.

**Comment by make-all** [comment] 2023-01-26 14:01
The release is now made, so I expect upgrading will help

**Comment by SvenMartin81** [comment] 2023-01-28 20:39
Hi,
I can now see ma vacuum again and all informationa. But I cannot start the vacuum to clean the rooms......it nothing happening....

**Comment by make-all** [comment] 2023-01-29 23:35
Please go to Settings / Devices & Services / Tuya Local - kyvol_e30_vacuum / 1 device and press the "Download Diagnostics" button.  Paste the contents of the downloaded file here.

**Comment by SvenMartin81** [comment] 2023-01-30 11:35
Hi, please find attached the file

[tuya_local.json.txt](https://github.com/make-all/tuya-local/files/10535335/tuya_local.json.txt)

**Comment by make-all** [comment] 2023-01-30 12:38
It seems to be detected as a 3.3 device, so if it is getting data, the local key must be correct.  But if it is in fact a 3.2 device, I think you may see problems like this, as it needs to use a different command to update the dps.  But it isn't really clear whether that is the problem.  Anyway, it is possible to set the protocol explicitly now, so may be worth trying version 3.2.  It won't be a later version, as the encryption is different for them, so it wouldn't be able to get data with the protocol on 3.3.

**Comment by SvenMartin81** [comment] 2023-01-30 18:53
Hi,
I tried to change to 3.2 but then the Integration ends with a fault. If i take 3.3 the vacuum is dedected. But I cannot use the vacuum.

**Comment by SvenMartin81** [comment] 2023-01-30 20:04
if I am using the Tuya app on my smartphone I can see changes in the status of the vacuum in HA....

**Comment by SvenMartin81** [comment] 2023-01-31 12:46
![3 2](https://user-images.githubusercontent.com/89967563/215763714-d9191dfd-db8c-4c13-b835-c56c7879a7cf.JPG)
![3 1](https://user-images.githubusercontent.com/89967563/215763720-a27305e6-0dfa-46d7-97b5-60e732741160.JPG)

**Comment by SvenMartin81** [comment] 2023-01-31 21:02
means the next version will have a new option....or how can I test this?

**Comment by make-all** [comment] 2023-01-31 21:55
You can test it by selecting "Redownload" from the menu in HACS, and select main as the version to download.  Wait for the select box to re-activate before pressing download.  After downloading, you should get nagged about upgrading to the latest release, which you can ignore until there is a new release.

**Comment by SvenMartin81** [comment] 2023-02-01 08:57
strange...since yesterday (although before I did the new download with the "main" version). my vaccum ist telling "Status: return_to_base"...all the time.....I deleted the integration and downloaded the "main" version activated the button "poll_only" but nothing changed.

**Comment by SvenMartin81** [comment] 2023-02-01 19:12
But when I try to control via TUYA App the status is like the app says. by coming back to the base the status stays at "return_to_base"....although the vacuum is already on the base.

**Comment by make-all** [comment] 2023-02-01 22:02
Can you send commands to it once it is running?  Maybe it has had a firmware update that causes it to cut off the local connection when it is on the base.

**Comment by SvenMartin81** [comment] 2023-02-02 05:55
No, Not possible. If the device is Running i See only the activities but i can Not control it through HA. Only Tuya app

**Comment by make-all** [comment] 2023-02-02 14:03
It seems it is not just your device having problems, as I just got a similar report in #372, but I do not have any explanation for why, as all my devices are working OK with the current version, and that seems to be the case for most other people too.  I gave some instructions for gathering debug log at the protocol level on that issue, and it might help diagnose the problem if you could try too.

**Comment by make-all** [comment] 2023-02-03 15:25
The other user having the same problem has reported that their device id setting was incorrect.  It seems some devices ignore the device id when sending status out, but check it is correct before accepting commands.  Can you remove the device and re add it, being careful to use the device_id exactly as it appears in the iot portal (including case)?

**Comment by SvenMartin81** [comment] 2023-02-13 06:17
I will Check this next week. But as i Said: i only have the Problem to Control the vaccum. All Sensors are Running fine except the „buttons“ to Start or change things through HA

**Comment by SvenMartin81** [comment] 2023-02-13 06:21
What do you mean with „remove the device“? From HA or the Cloud iot?
I removed it several times and added it again. I although changed my accound but all the Same.

**Comment by make-all** [comment] 2023-02-13 06:28
From HA.  If you removed it from the cloud, it would have gotten another local key assigned, so that could be another potential source of trouble.

**Comment by SvenMartin81** [comment] 2023-02-25 15:19
Hi, I removed from HA and added it again. The Vacuum is there but the problem is not gone. it is the same as before. I see allt sensors and buttons but I cannot control the vacuum.

**Comment by make-all** [comment] 2023-06-11 15:17
Possibly tinytuya 1.12.7 has fixed this issue, but I don't know if you are still using this integration after all this time of it not working.

**Closed** 2023-07-08 15:41 UTC
