### ISSUE TITLE
Pool heatpomp going unavailable

### ISSUE THREAD

**Issue by bezigebever** [make-all/tuya-local#660] opened 2023-04-29 09:16 UTC
### Discussed in https://github.com/make-all/tuya-local/discussions/649

<div type='discussions-op-text'>

<sup>Originally posted by **bezigebever** April 25, 2023</sup>
I have a pool heat pump (Gardenpac) wich was working last year (stored offline in winter), I re-installed the heatpump and since then it is very unstable and if often unavailable in HA. I know meanwhile version of this integration has changed, but can't say on which version I was in september last year...
Heatpump and HA are not on the same network, but FW is open (and no dropped packets).
After restarting HA it works again for some time.
```
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2023.4.6",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.10",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/Brussels",
    "os_name": "Linux",
    "os_version": "6.1.24",
    "supervisor": "2023.04.1",
    "host_os": "Home Assistant OS 10.0",
    "docker_version": "23.0.3",
    "chassis": "vm",
    "run_as_root": true
  },
  "custom_components": {
    "adaptive_lighting": {
      "version": "1.11.0",
      "requirements": [
        "ulid-transform"
      ]
    },
    "hikvision_next": {
      "version": "1.0.3",
      "requirements": [
        "xmltodict==0.13.0",
        "hikvisionapi==0.3.2",
        "requests-toolbelt==0.10.1"
      ]
    },
    "tuya_local": {
      "version": "2022.4.1",
      "requirements": [
        "pycryptodome~=3.17",
        "tinytuya==1.12.4"
      ]
    },
    "solaredge_modbus": {
      "version": "1.4.0",
      "requirements": [
        "pymodbus==3.1.1"
      ]
    },
    "hacs": {
      "version": "1.32.1",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "afvalbeheer": {
      "version": "5.2.3",
      "requirements": [
        "rsa",
        "pycryptodome"
      ]
    },
    "lms_tts_notify": {
      "version": "0.3.13",
      "requirements": []
    },
    "frigate": {
      "version": "4.0.0",
      "requirements": [
        "pytz==2022.7"
      ]
    },
    "browser_mod": {
      "version": "1.5.3",
      "requirements": []
    },
    "ltss": {
      "version": "2.0.1",
      "requirements": [
        "sqlalchemy>=2.0,<3.0",
        "psycopg2>=2.8,<3.0",
        "geoalchemy2>=0.13,<1.0"
      ]
    },
    "youfone_be": {
      "version": "4.0.0",
      "requirements": []
    },
    "panasonic_cc": {
      "version": "1.0.32",
      "requirements": []
    },
    "esxi_stats": {
      "version": "0.6.4",
      "requirements": [
        "pyvmomi==7.0.3"
      ]
    },
    "weatherflow": {
      "version": "1.0.14",
      "requirements": [
        "pyweatherflowrest==1.0.9"
      ]
    }
  },
  "integration_manifest": {
    "domain": "tuya_local",
    "name": "Tuya Local",
    "codeowners": [
      "@make-all"
    ],
    "config_flow": true,
    "dependencies": [],
    "documentation": "https://github.com/make-all/tuya-local",
    "integration_type": "device",
    "iot_class": "local_push",
    "issue_tracker": "https://github.com/make-all/tuya-local/issues",
    "requirements": [
      "pycryptodome~=3.17",
      "tinytuya==1.12.4"
    ],
    "version": "2022.4.1",
    "is_built_in": false
  },
  "data": {
    "name": "Warmtepomp",
    "type": "gardenpac_heatpump",
    "device_id": "**REDACTED**",
    "local_key": "**REDACTED**",
    "host": "**REDACTED**",
    "protocol_version": "auto",
    "api_version_set": 3.2,
    "api_version_used": 3.2,
    "api_working": false,
    "status": {
      "102": 10
    },
    "cached_state": {
      "updated_at": 0
    },
    "pending_state": {},
    "connected": true,
    "force_dps": [],
    "home_assistant": {
      "name": "Warmtepomp",
      "name_by_user": null,
      "disabled": false,
      "disabled_by": null,
      "entities": [
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": null,
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "climate.warmtepomp",
            "state": "unavailable",
            "attributes": {
              "hvac_modes": [
                "heat",
                "off"
              ],
              "min_temp": null,
              "max_temp": null,
              "target_temp_step": 1.0,
              "preset_modes": [
                "Silent",
                "Smart"
              ],
              "friendly_name": "Warmtepomp",
              "supported_features": 17
            },
            "last_changed": "2023-04-25T16:35:49.234983+00:00",
            "last_updated": "2023-04-25T16:35:49.234983+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "diagnostic",
          "device_class": null,
          "original_device_class": "power_factor",
          "icon": null,
          "unit_of_measurement": "%",
          "state": {
            "entity_id": "sensor.warmtepomp_power_level",
            "state": "unavailable",
            "attributes": {
              "state_class": "measurement",
              "unit_of_measurement": "%",
              "device_class": "power_factor",
              "icon": "mdi:signal",
              "friendly_name": "Warmtepomp Power level"
            },
            "last_changed": "2023-04-25T16:35:49.234356+00:00",
            "last_updated": "2023-04-25T16:35:49.234356+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "diagnostic",
          "device_class": null,
          "original_device_class": "problem",
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "binary_sensor.warmtepomp_water_flow",
            "state": "unavailable",
            "attributes": {
              "device_class": "problem",
              "friendly_name": "Warmtepomp Water flow"
            },
            "last_changed": "2023-04-25T16:35:49.233691+00:00",
            "last_updated": "2023-04-25T16:35:49.233691+00:00"
          }
        }
      ]
    }
  }
}
```</div>

**Comment by make-all** [comment] 2023-04-29 09:51
Duplicate of #653

**Closed by make-all** 2023-04-29 09:51 UTC
