### ISSUE TITLE
Request support for Geyserwise Max

### ISSUE THREAD

**Issue by mac-za** [make-all/tuya-local#1002] opened 2023-08-19 11:11 UTC
Good Afternoon

If you could please look at the provided info in order to create support for a Geyserwise Max control unit.
I have the following information. Please let me know if I have omitted anything?

|DPID | Description | Example | unit|
|-- | -- | -- | --|
|1 | Power | On / Off | -|
|2 | Mode | Holiday or Normal | -|
|10 | Geyser Temp. | 31 | Deg C|
|13 | Element | On / Off | -|
|20 | Fault | E1 to E9 | -|
|101 | Pump | On / Off | -|
|102 | Solar Differential | 7 | Deg C|
|103 | Block 1 | 55 | Deg C|
|104 | Block 2 | 55 | Deg C|
|105 | Block 3 | 55 | Deg C|
|106 | Block 4 | 55 | Deg C|
|107 | Anti Freeze Temp. | 5 | Deg C|
|108 | Collector | 38 | Deg C|
|109 | Element Run Time | 10 | hours|

Product ID:  atagzqpggkegajmw

Thanks in advance

**Comment by make-all** [comment] 2023-08-24 13:39
Duplicate of #765.  No new information is given by this report, local protocol values for the mode dp are still unknown.

**Closed by make-all** 2023-08-24 13:39 UTC
Labels: new device
