### ISSUE TITLE
Detected blocking call to open inside the event loop by custom integration 'tuya_local

### ISSUE THREAD

**Issue by FunkeyMonkey** [make-all/tuya-local#1992] opened 2024-06-09 14:01 UTC
This form is for reporting bugs.  If you have encountered a bug, you should
generally have some log messages or device diagnostics to show something is
going wrong.  If your problem is more of a question or a request for help,
then [Discussions](https://github.com/make-all/tuya-local/discussions) is
probably a more suitable venue.

**Describe the bug**
Found this in the logs while trying to diagnose another issue

**To Reproduce**
Steps to reproduce the behavior including the device the issue was observed with:

**Expected behavior**

**Additional context**

If the bug involves a device, then please include device diagnostics from
Settings / Devices & Services / Tuya Local (your device) / "1 device"

Please check if there are messages from Tuya Local in the Home
Assistant log (Settings / System / Logs), and include those too.

WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open inside the event loop by custom integration 'tuya_local' at custom_components/tuya_local/helpers/device_config.py, line 101: self._config = load_yaml(filename) (offender: /usr/src/homeassistant/homeassistant/util/yaml/loader.py, line 226: with open(fname, encoding="utf-8") as conf_file:), please create a bug report at https://github.com/make-all/tuya-local/issues

**Comment by make-all** [comment] 2024-06-09 14:06
Duplicate of #1981 which is fixed in the new release just made.

**Closed by make-all** 2024-06-09 14:06 UTC
Labels: bug
