### ISSUE TITLE
Request support for KWS-302WF

### ISSUE THREAD

**Issue by alexps70** [make-all/tuya-local#2259] opened 2024-08-30 13:59 UTC
### Log message

```text
Device matches qoto_03_sprinkler with quality of 28%. DPS: {"updated_at": 1725005939.0350885, "16": true, "101": 2258, "102": 3620, "103": 6284, "104": 8173, "105": 129146, "106": 76, "107": 49, "108": 36, "109": 180, "110": 250, "111": 0, "113": 0, "114": 0, "115": 85, "116": "2", "119": 0, "123": 12495439}
```

### DPS information

```text
"dps_strings": [
        "16 (value: True)",
        "101 (value: 2261)",
        "102 (value: 4770)",
        "103 (value: 8464)",
        "104 (value: 31943)",
        "105 (value: 571020)",
        "106 (value: 78)",
        "107 (value: 50)",
        "108 (value: 39)",
        "109 (value: 180)",
        "110 (value: 250)",
        "111 (value: 0)",
        "113 (value: 0)",
        "114 (value: 0)",
        "115 (value: 85)",
        "116 (value: 2)",
        "119 (value: 0)",
        "123 (value: 2742620)"
      ]
```

### Product ID

"product_id": "tadm13agjigbdtxd",

### Product Name

KWS-302WF

### Information about how the device functions

DIN Power meter relay

"entities": [
        {
          "friendly_name": "Switch",
          "restore_on_reconnect": false,
          "is_passive_entity": false,
          "current_consumption": 103,
          "current": 102,
          "voltage": 101,
          "id": 16,
          "platform": "switch"
        },
        {
          "friendly_name": "Voltage",
          "unit_of_measurement": "V",
          "device_class": "voltage",
          "scaling": 0.1,
          "id": 101,
          "platform": "sensor"
        },
        {
          "friendly_name": "Current",
          "unit_of_measurement": "A",
          "device_class": "current",
          "scaling": 0.001,
          "id": 102,
          "platform": "sensor"
        },
        {
          "friendly_name": "Power",
          "unit_of_measurement": "W",
          "device_class": "power",
          "scaling": 0.1,
          "id": 103,
          "platform": "sensor"
        },
        {
          "friendly_name": "PF",
          "unit_of_measurement": "%",
          "device_class": "power_factor",
          "id": 106,
          "platform": "sensor"
        },
        {
          "friendly_name": "Frequency",
          "unit_of_measurement": "Hz",
          "device_class": "frequency",
          "id": 107,
          "platform": "sensor"
        },
        {
          "friendly_name": "Temperature",
          "unit_of_measurement": "\u2103",
          "device_class": "temperature",
          "id": 108,
          "platform": "sensor"
        },
        {
          "friendly_name": "Energy",
          "unit_of_measurement": "kWh",
          "device_class": "energy_storage",
          "scaling": 0.001,
          "id": 105,
          "platform": "sensor"
        }
      ],

**Comment by make-all** [comment] 2024-08-30 14:57
Duplicate of #2257

**Closed** 2024-08-30 14:58 UTC
