### ISSUE TITLE
HA Warning: Detected blocking call to sleep inside the event loop by custom integration 'tuya_local'

### ISSUE THREAD

**Issue by MaBeniu** [make-all/tuya-local#1685] opened 2024-02-27 05:59 UTC
Hi, in home assistant host logs I find a warning for tuya-local integration. I only have one tuya device setup. In general device seems to be functioning all right it is just that warning message in HA logs that also says I shall report it. Would nice to know if there is something to fix or troubleshoot the issue.

Home Assistant Core warning message:
```
Logger: homeassistant.util.async_
Source: util/async_.py:141
First occurred: 7:39:32 AM (1 occurrences)
Last logged: 7:39:32 AM

Detected blocking call to sleep inside the event loop by custom integration 'tuya_local' at custom_components/tuya_local/device.py, line 77: self._api = tinytuya.Device(dev_id, address, local_key), please create a bug report at https://github.com/make-all/tuya-local/issues
```
**To Reproduce**
It appears each time after HA restart.

**Expected behavior**
no warning and stable integration

device diagnostic file attached.
[config_entry-tuya_local-b882502d637ab019e549e0038010d583.json](https://github.com/make-all/tuya-local/files/14415006/config_entry-tuya_local-b882502d637ab019e549e0038010d583.json)

**Comment by make-all** [comment] 2024-02-27 07:30
Duplicate of #407

**Closed by make-all** 2024-02-27 07:30 UTC
Labels: bug
