### ISSUE TITLE
Request support for Intelbras IRF 7000+ Smart Lock

### ISSUE THREAD

**Issue by thomenz** [make-all/tuya-local#1792] opened 2024-04-02 02:04 UTC
```
Este erro originou-se de uma integração personalizada.

Registrador: custom_components.tuya_local.config_flow
Fonte: custom_components/tuya_local/config_flow.py:97
integração: Tuya Local (documentação, problemas)
Ocorreu pela primeira vez: 21:17:47 (2 ocorrências)
Último registro: 21:23:17

Device matches co2_box with quality of 33%. DPS: {"updated_at": 1712020666.1940782, "2": 0, "7": 0, "8": true}
Device matches co2_box with quality of 33%. DPS: {"updated_at": 1712020996.670844, "2": 0, "7": 0, "8": true}
```

```
{
  "result": {
    "model": "{\"modelId\":\"000002j1w7\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[
{\"abilityId\":1,\"accessMode\":\"ro\",\"code\":\"unlock_fingerprint\",\"description\":\"【可选】指纹在门锁上录入，录入完成后由硬件分配id，发生指纹解锁后，门锁将上报该dp点。请用记录型上报\",\"extensions\":{\"iconName\":\"icon-dp_lock\",\"trigger\":\"direct\"},\"name\":\"指纹解锁\",\"typeSpec\":{\"type\":\"value\",\"max\":999,\"min\":0,\"scale\":0,\"step\":1}},
{\"abilityId\":2,\"accessMode\":\"ro\",\"code\":\"unlock_password\",\"description\":\"【可选】普通密码在门锁上录入，录入完成后由硬件分配id，发生普通密码解锁后，门锁将上报该dp点。普通密码指在门锁硬件上创建的密码，不包含通过app创建的临时密码。请用记录型上报\\n\",\"extensions\":{\"iconName\":\"icon-dp_lock\",\"trigger\":\"direct\"},\"name\":\"普通密码解锁\",\"typeSpec\":{\"type\":\"value\",\"max\":999,\"min\":0,\"scale\":0,\"step\":1}},
{\"abilityId\":3,\"accessMode\":\"ro\",\"code\":\"unlock_temporary\",\"description\":\"【可选】通过app创建的临时密码，使用该类型开门成功后需要上报，上报的id为门锁端id。请用记录型上报\\n\",\"extensions\":{\"iconName\":\"icon-dp_lock\",\"trigger\":\"direct\"},\"name\":\"临时密码解锁\",\"typeSpec\":{\"type\":\"value\",\"max\":999,\"min\":0,\"scale\":0,\"step\":1}},
{\"abilityId\":4,\"accessMode\":\"ro\",\"code\":\"unlock_dynamic\",\"description\":\"【可选】使用动态密码开门成功后，进行上报，只要报指定数字1。app显示的时候，只要有动态密码记录，不显示具体编号只显示类型\\n\",\"extensions\":{\"iconName\":\"icon-dp_lock\",\"trigger\":\"direct\"},\"name\":\"动态密码解锁\",\"typeSpec\":{\"type\":\"value\",\"max\":999,\"min\":0,\"scale\":0,\"step\":1}},
{\"abilityId\":5,\"accessMode\":\"ro\",\"code\":\"unlock_card\",\"description\":\"【可选】卡片在门锁上录入，录入完成后由硬件分配id，发生卡片解锁后，门锁将上报该dp点。请用记录型上报\\n\",\"extensions\":{\"iconName\":\"icon-dp_lock\",\"trigger\":\"direct\"},\"name\":\"卡片解锁\",\"typeSpec\":{\"type\":\"value\",\"max\":999,\"min\":0,\"scale\":0,\"step\":1}},
{\"abilityId\":7,\"accessMode\":\"ro\",\"code\":\"unlock_key\",\"description\":\"【可选】如硬件能检测出机械钥匙开门，则固定上报 dp值为1，表示发生了机械钥匙开门。该开门记录请有记录型数据上报\\n\",\"extensions\":{\"iconName\":\"icon-dp_lock\"},\"name\":\"机械钥匙解锁\",\"typeSpec\":{\"type\":\"value\",\"max\":999,\"min\":0,\"scale\":0,\"step\":1,\"unit\":\"\"}},
{\"abilityId\":8,\"accessMode\":\"ro\",\"code\":\"open_close\",\"description\":\"【可选】如门锁硬件支持开门/关门事件监测则勾选该项，在开门记录中，加入门的开关门事件，并且最近一次的开关门记录反映门当前的开合状态。0=关，1=开。请使用记录型数据上报\\n\",\"extensions\":{\"iconName\":\"icon-fangzi1\",\"trigger\":\"direct\"},\"name\":\"开关门事件\",\"typeSpec\":{\"type\":\"bool\"}},
{\"abilityId\":9,\"accessMode\":\"ro\",\"code\":\"alarm_lock\",\"description\":\"【必选】0=指纹试错告警、1=密码试错高警、2=卡试错告警、3=人脸试错告警、4=假锁（锁舌卡住）、5=高温告警、6=超时未关门、7=电子锁舌未弹出、8=防撬告警 、9=钥匙插入、10=低电告警、11=电量耗尽告警、12=震动告警。\\n\",\"extensions\":{\"iconName\":\"icon-Trigger\",\"attribute\":\"512\",\"trigger\":\"direct\"},\"name\":\"Alarm\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"wrong_finger\",\"wrong_password\",\"wrong_card\",\"wrong_face\",\"tongue_bad\",\"too_hot\",\"tongue_not_out\",\"pry\",\"key_in\",\"power_off\",\"shock\",\"unclosed_time\",\"low_battery\",\"defense\"]}},
{\"abilityId\":10,\"accessMode\":\"ro\",\"code\":\"residual_electricity\",\"description\":\"【必选】门锁上报电量百分比\\n\",\"extensions\":{\"iconName\":\"icon-dp_battery\",\"attribute\":\"512\",\"trigger\":\"direct\"},\"name\":\"剩余电量\",\"typeSpec\":{\"type\":\"value\",\"max\":100,\"min\":0,\"scale\":0,\"step\":1,\"unit\":\"%\"}},
{\"abilityId\":19,\"accessMode\":\"rw\",\"code\":\"key_tone\",\"description\":\"【可选】该dp点用来对门锁键盘的反馈音进行设置。从0到9，表示从静音到最大音量。app设置后，如果硬件收到，需要将原设置值返回给服务器。如设置的是5，硬件设置成功返回5，设置失败，不返回\\n\",\"extensions\":{\"iconName\":\"icon-sound\"},\"name\":\"按键音量\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"mute\",\"low\",\"normal\",\"high\"]}},
{\"abilityId\":22,\"accessMode\":\"ro\",\"code\":\"remote_result\",\"description\":\"【可选】上报开门结果，门锁mcu需回复该dp，ture或false\\n\",\"extensions\":{\"iconName\":\"icon-dp_loop\",\"trigger\":\"direct\"},\"name\":\"远程开门指令反馈\",\"typeSpec\":{\"type\":\"bool\"}},
{\"abilityId\":23,\"accessMode\":\"wr\",\"code\":\"remote_unlock_switch\",\"description\":\"【可选】通过app进行设置，可以禁用，启用远程开门功能；禁用远程开门功能后，无法通过app进行远程开门，进行该操作门锁硬件会拒绝，重新启用后才能进行远程开门。禁用远程开门，会下发dp48，使得mcu端免密远程开门密钥失效。\\n\",\"extensions\":{\"iconName\":\"icon-HomeArm\"},\"name\":\"禁用远程开门\",\"typeSpec\":{\"type\":\"bool\"}},
{\"abilityId\":24,\"accessMode\":\"wr\",\"code\":\"password_creat\",\"description\":\"【可选】app/web发起操作，调用服务端接口，服务器转换为dp点\\n\",\"extensions\":{\"iconName\":\"icon-dp_add\"},\"name\":\"创建临时密码\",\"typeSpec\":{\"type\":\"raw\",\"maxlen\":128}},
{\"abilityId\":25,\"accessMode\":\"wr\",\"code\":\"password_delete\",\"description\":\"【可选】app/web发起操作，调用服务端接口，服务器转换为dp点\\n\",\"extensions\":{\"iconName\":\"icon-dp_reduce\"},\"name\":\"删除临时密码\",\"typeSpec\":{\"type\":\"raw\",\"maxlen\":128}},
{\"abilityId\":26,\"accessMode\":\"wr\",\"code\":\"password_update\",\"description\":\"【可选】app/web发起操作，调用服务端接口，服务器转换为dp点\\n\",\"extensions\":{\"iconName\":\"icon-dp_home2\"},\"name\":\"修改临时密码\",\"typeSpec\":{\"type\":\"raw\",\"maxlen\":128}},
{\"abilityId\":27,\"accessMode\":\"wr\",\"code\":\"password_disable\",\"description\":\"【可选】app/web发起操作，调用服务端接口，服务器转换为dp点\\n\",\"extensions\":{\"iconName\":\"icon-dp_home2\"},\"name\":\"冻结临时密码\",\"typeSpec\":{\"type\":\"raw\",\"maxlen\":128}},
{\"abilityId\":28,\"accessMode\":\"wr\",\"code\":\"password_enable\",\"description\":\"【可选】app/web发起操作，调用服务端接口，服务器转换为dp点\\n\",\"extensions\":{\"iconName\":\"icon-dp_home2\"},\"name\":\"解冻临时密码\",\"typeSpec\":{\"type\":\"raw\",\"maxlen\":128}},
{\"abilityId\":35,\"accessMode\":\"ro\",\"code\":\"hijack\",\"description\":\"【可选】该功能默认不需要硬件实现，门锁不用做劫持判断，只要在app上标记解锁id即可\\n\",\"extensions\":{\"iconName\":\"icon-guanjia\",\"trigger\":\"direct\"},\"name\":\"劫持报警\",\"typeSpec\":{\"type\":\"bool\"}},
{\"abilityId\":38,\"accessMode\":\"ro\",\"code\":\"door_opened\",\"description\":\"【可选】该dp点指门发生了解锁事件，并不是指门从闭合状态到打开状态，开合状态需要通过8dp点实现。该dp的作用在于用户可以更方便的在app上进行自动化配置。如果门锁能够检测出内开与开外，建议使用8dp点进行联动；如不能检测，则是由解锁事件触发\\n\",\"extensions\":{\"iconName\":\"icon-baifeng\",\"trigger\":\"direct\"},\"name\":\"门被打开\",\"typeSpec\":{\"type\":\"bool\"}},
{\"abilityId\":39,\"accessMode\":\"rw\",\"code\":\"password_reset\",\"description\":\"【必选】当app对门锁进行恢复出厂设置时，云端下发指令给门锁，门锁清除本地的临时密码。如果门锁本地进行恢复出厂设置，清除了本地的临时密码，需要上报该dp点云端，确保云端的临时密码记录和本地保持一致。如果本地恢复出厂设置时，上报该39失败，需要在下次重新配网后上报39\\n\",\"extensions\":{\"iconName\":\"icon-dp_reduce\"},\"name\":\"清除门锁临时密码\",\"typeSpec\":{\"type\":\"raw\",\"maxlen\":128}},
{\"abilityId\":41,\"accessMode\":\"ro\",\"code\":\"unlock_remote\",\"description\":\"【可选】当门锁使用远程开门后，需要1、回复远程开门成功的指令，即dp点22；   2、上报门被打开，即dp点38 ；3、上报远程开门的记录，即dp点41\\n\",\"name\":\"远程开门记录\",\"typeSpec\":{\"type\":\"value\",\"max\":999,\"min\":0,\"scale\":0,\"step\":1}},
{\"abilityId\":47,\"accessMode\":\"ro\",\"code\":\"closed_opened\",\"description\":\"【可选】门锁硬件上能够判断门开合状态的请勾选该功能（地磁，陀螺仪等），状态变化时，上报对应的值。首次配网初始化时，上报unknown\\n\",\"name\":\"开合状态\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"open\",\"closed\",\"unknown\"]}},
{\"abilityId\":48,\"accessMode\":\"rw\",\"code\":\"remote_no_pd_setkey\",\"description\":\"【可选】该功能为免密远程开门安全方案新增dp：免密远程开门功能需要勾选该dp，由服务端下发该dp，带密钥到门锁端。当前逻辑：门锁收到dp48后，存储该远程开门密钥。门锁收到免密远程开门指令dp49后，校验该密钥。\",\"extensions\":{\"attribute\":\"128\"},\"name\":\"新免密远程开门-设置免密密钥\",\"typeSpec\":{\"type\":\"raw\",\"maxlen\":128}},
{\"abilityId\":49,\"accessMode\":\"rw\",\"code\":\"remote_no_dp_key\",\"description\":\"【可选】该dp与dp48配合使用。新免密远程开门下发功能使用 新的dp49 ，下发该dp需要mcu端解析数据格式。原dp40免密远程开门弃用。\\n新免密远程开门，先由服务端下发安全密钥：dp48，mcu端存储该密钥。然后面板端发起dp49，免密远程开门，mcu则回复dp49，如果开门成功回复dp22：远程开门记反馈 和dp41：远程开门解锁记录。\",\"extensions\":{\"attribute\":\"128\"},\"name\":\"新免密远程开门-安全方案\",\"typeSpec\":{\"type\":\"raw\",\"maxlen\":128}},
{\"abilityId\":54,\"accessMode\":\"rw\",\"code\":\"unlock_method_create\",\"description\":\"\",\"extensions\":{\"attribute\":\"128\"},\"name\":\"添加开门方式\",\"typeSpec\":{\"type\":\"raw\",\"maxlen\":128}},
{\"abilityId\":55,\"accessMode\":\"rw\",\"code\":\"unlock_method_delete\",\"description\":\"\",\"extensions\":{\"attribute\":\"128\"},\"name\":\"删除开门方式\",\"typeSpec\":{\"type\":\"raw\",\"maxlen\":128}},
{\"abilityId\":57,\"accessMode\":\"rw\",\"code\":\"lock_motor_state\",\"description\":\"注意：如果要实现Alexa或Google语音开门，则必须上报该dp。该dp为bool类型，true为开锁，false为关锁。\",\"extensions\":{\"iconName\":\"icon-dp_lock\",\"attribute\":\"128\",\"trigger\":\"direct\"},\"name\":\"电机状态\",\"typeSpec\":{\"type\":\"bool\"}},
{\"abilityId\":61,\"accessMode\":\"rw\",\"code\":\"single_use_password\",\"description\":\"该dp用于控制面板端显示一次性密码，默认为true。如果勾选该dp，则有一次性密码功能，如果不勾选该dp，则无一次性密码功能。\",\"extensions\":{\"attribute\":\"128\"},\"name\":\"一次性密码\",\"typeSpec\":{\"type\":\"bool\"}},
{\"abilityId\":62,\"accessMode\":\"rw\",\"code\":\"unlock_voice_remote\",\"description\":\"【可选】如果门锁支持Google Home语音开锁，则需要勾选该dp用来设置Google Home语音开关锁 Voice Code。\",\"extensions\":{\"iconName\":\"icon-dp_mic\",\"attribute\":\"640\"},\"name\":\"Remote unlock by voice box\",\"typeSpec\":{\"type\":\"value\",\"max\":999,\"min\":0,\"scale\":0,\"step\":1}}]}]}"
  },
  "success": true,
  "t": 1712021178519,
  "tid": "0166dadff09011eeaf18ce1e08994cdc"
}
```

```
"product_id": "snr3p274",
"product_name": "IFR 7000 / IFR 7001"
```

```
https://www.intelbras.com/pt-br/fechadura-smart-de-embutir-com-macaneta-ifr-7000-ifr-7000
```

**Comment by thomenz** [comment] 2024-05-17 01:58
Hello! It's working now under the config of IRF 7000 that's already in the code, i can see the states changes between lock and unlock, but it's read only, i was able to add key tone config using the yaml, but what i'm trying here is to have the ability to send a temporary password to the lock and delete it when i want.

The DP to create is 24 and to delete is 25 , the data structure provided by tuya is:

**Create:**

> DP structure: Tuya serial number+Server serial number+Lock manufacturer ID+Start time+End time+Whether a one-time password is used+Password. Content analysis: a) Tuya serial number: Data[0] and Data[1]. b) Server serial number: Data[2] and Data [3]. c) Lock manufacturer ID: Data[4] and Data[5], initial value: 0x0 and 0x0. d) Start time: Data[6] to Data[9], standard timestamp. e) End time: Data[10] to Data[13], standard timestamp. f) Whether a one-time password is used: Data[14]. 1: a one-time password. 0: other types of passwords. g) Password: Data[15] to Data[20]. The ASCII codes specify a 6-digit password.

>Report:
DP structure: Tuya serial number+Server serial number+Lock manufacturer ID+Response status. 1) Content analysis: a) Tuya serial number: Data[0] and Data[1]. b) Server serial number: Data[2] and Data[3]. c) Lock manufacturer ID: Data[4] and Data[5]. d) Response status: Data[6]. Valid values: 0: failure. 1: success. 2: duplicated password. 3: The maximum number of passwords is reached.

**Delete**

>DP structure: Tuya serial number+Server serial number+Lock manufacturer ID. Content analysis: a) Tuya serial number: Data[0] and Data[1]. b) Server serial number: Data[2] and Data[3]. c) Lock manufacturer ID: Data[4] and Data [5.]

>Report:
DP structure: Tuya serial number+Server serial number+Lock manufacturer ID+Response status. Content analysis: a) Tuya serial number: Data[0] and Data[1]. b) Server serial number: Data[2] and Data[3]. c)Lock manufacturer ID: Data[4] and Data[5]. d) Response status: Data[6]. Valid values: 0: failure. 1: success. 2: The password does not exist.

[https://developer.tuya.com/en/docs/iot/zigbee-doorlock-dp?id=K9fembhbeab0p](url)

What are the chances of getting to it? Thanks in advance!

**Comment by make-all** [comment] 2024-05-17 02:12
Duplicate of #1105, #1921

**Comment by make-all** [comment] 2024-05-17 02:17
I see the current implementation is missing a lot of dps, and apparently marked the wrong ones as non-optional, making it difficult to detect.

While the requested temporary password feature is an outstanding enhancement request, which will take a long time to implement, adding the missing dps should be relatively easy.

**Closed** 2024-05-25 14:46 UTC
