### ISSUE TITLE
homeassistant.util.async - blocking call to sleep

### ISSUE THREAD

**Issue by nliaudat** [make-all/tuya-local#799] opened 2023-06-14 17:38 UTC
```
2023-06-14 19:34:15.628 WARNING (MainThread) [homeassistant.util.async_] Detecte
d blocking call to sleep inside the event loop. This is causing stability issues
. Please report issue to the custom integration author for tuya_local doing bloc
king calls at custom_components/tuya_local/device.py, line 78: self._api = tinyt
uya.Device(dev_id, address, local_key)  
```

**Comment by make-all** [comment] 2023-06-14 22:20
Duplicate of #407

**Closed by make-all** 2023-06-14 22:20 UTC
Labels: bug
