### ISSUE TITLE
Failed to unload - reload config entry

### ISSUE THREAD

**Issue by iotinkognito** [make-all/tuya-local#1949] opened 2024-05-26 04:15 UTC
**Describe the bug**
My devices are unresponsive when looking at the integration I see the message after reload config entry. 

**To Reproduce**
Services -> core integration reload

**Expected behavior**
Reload the tuya local integration

**Additional context**
If devices on ubiquiti networks are physically switched off they don’t become controllable with tuyalocal after being switched back on even with static ipaddress. I was running an integration reload on interval to overcome the problem.

**Log Error information**
After running code integration reload. 

Logger: homeassistant.components.number
Source: helpers/entity_platform.py:910
integration: Number (documentation, issues)
First occurred: 6:01:44 AM (2 occurrences)
Last logged: 6:01:44 AM

Error while removing entity number.dl_pantry_local_timer
Error while removing entity number.locdl_wir_jowo_timer
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1378, in async_remove
    await self.__async_remove_impl(force_remove)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1394, in __async_remove_impl
    await self.async_will_remove_from_hass()
  File "/config/custom_components/tuya_local/helpers/mixin.py", line 111, in async_will_remove_from_hass
    await self._device.async_unregister_entity(self)
  File "/config/custom_components/tuya_local/device.py", line 195, in async_unregister_entity
    await self.async_stop()
  File "/config/custom_components/tuya_local/device.py", line 170, in async_stop
    await self._refresh_task
TypeError: object Future can't be used in 'await' expression

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 910, in async_reset
    await entity.async_remove()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1383, in async_remove
    self.__remove_future.set_result(None)
asyncio.exceptions.InvalidStateError: invalid state

Logger: homeassistant.config_entries
Source: config_entries.py:792
First occurred: 6:01:44 AM (2 occurrences)
Last logged: 6:01:44 AM

Error unloading entry DL Pantry LOCAL for tuya_local
Error unloading entry locDL WIR JOWO for tuya_local
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 792, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_local/__init__.py", line 517, in async_unload_entry
    await async_delete_device(hass, config)
  File "/config/custom_components/tuya_local/device.py", line 655, in async_delete_device
    await hass.data[DOMAIN][device_id]["device"].async_stop()
  File "/config/custom_components/tuya_local/device.py", line 170, in async_stop
    await self._refresh_task
TypeError: object Future can't be used in 'await' expression

**Comment by make-all** [comment] 2024-05-26 05:21
Your line numbers are off-by-one compared with latest code.  I think this is an indication that you are using an older version, and this is therefore a duplicate of #1888

**Closed by make-all** 2024-05-26 05:21 UTC
Labels: bug

**Comment by iotinkognito** [comment] 2024-05-26 14:26
Running latest? 

Home Assistant

Core
2024.5.5
Supervisor
2024.05.1
Operating System
12.2
Frontend
20240501.1

**Comment by make-all** [comment] 2024-05-29 12:24
What does the version say here?: https://my.home-assistant.io/redirect/integration/?domain=tuya_local
