### ISSUE TITLE
AREA_SQUARE_METERS was used from tuya_local, this is a deprecated constant 

### ISSUE THREAD

**Issue by Esp32-zapper** [make-all/tuya-local#2674] opened 2024-12-21 06:00 UTC
### Description

Got this in the logg

Logger: homeassistant.const
Källa: helpers/deprecation.py:222
Inträffade först: 06:47:05 (1 händelser)
Senast loggade: 06:47:05

AREA_SQUARE_METERS was used from tuya_local, this is a deprecated constant which will be removed in HA Core 2025.12. Use UnitOfArea.SQUARE_METERS instead, please report it to the author of the 'tuya_local' custom integration

### Confirmation

- [X] I am sure this is a bug or improvement, that is well enough described that it can be implemented.
- [X] If this is for a specific device, the device config is mentioned above, or diagnostics are included.

- [X] Log messages or diagnostics relevant to the issue are included.

- [X] This is not requesting addition of a new device.

**Comment by make-all** [comment] 2024-12-21 11:49
Duplicate of #2596

**Closed by make-all** 2024-12-21 11:49 UTC
Labels: bug

**Comment by Esp32-zapper** [comment] 2024-12-21 13:11
Sorry, git search is a pretty dull instrument.
