### ISSUE TITLE
BLE Lights having issues sticking to their toggle

### ISSUE THREAD

**Issue by Krispkiwi** [make-all/tuya-local#2613] opened 2024-12-05 03:21 UTC
### Description

When pressing the turn on buttons for the BLE lights, they immediately try to switch back to off and vice versa. Sometimes the light turns off / on other times they don't. I remember we've ran into this issue before but not sure if we ever found the fix.

HA logs stating:
Failed to fetch device status
Check device key or version
Network Error: Unable to Connect

These are connected fine on my network though, fully functional in the app, semi functional in HA. They've always required 3.4 to connect so I don't believe it's an error with the device key or version otherwise they wouldn't work at all. 

### Steps to reproduce

Pair the BLE lights to a Hub then to home assistant
Try turning them off and on

### Expected behaviour

Turn on and stay on and vice versa with off

### Additional context

[home-assistant_tuya_local_2024-12-05T03-21-09.252Z.log](https://github.com/user-attachments/files/18016801/home-assistant_tuya_local_2024-12-05T03-21-09.252Z.log)

### Confirmation

- [X] I am sure this is a bug or improvement, that is well enough described that it can be implemented.
- [X] If this is for a specific device, the device config is mentioned above, or diagnostics are included.

- [X] Log messages or diagnostics relevant to the issue are included.

- [X] This is not requesting addition of a new device.

**Comment by make-all** [comment] 2024-12-05 11:11
I'm fairly certain this is just a duplicate of #1323 and other hub connection limitation issues. The lights are not properly connected.

**Closed** 2024-12-05 11:12 UTC
