### ISSUE TITLE
Warning massage after update.

### ISSUE THREAD

**Issue by sp0ok1** [make-all/tuya-local#1946] opened 2024-05-25 12:04 UTC
After updating the Home Assistant core 2024.5.5 A "warning" has occurred:
"Detected blocking call to sleep inside the event loop by custom integration 'tuya_local' at custom_components/tuya_local/device.py, line 77: self._api = tinytuya.Device(dev_id, address, local_key) (offender: /usr/local/lib/python3.12/site-packages/tinytuya/core.py, line 944: time.sleep(0.1))"

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior including the device the issue was observed with:

**Expected behavior**

**Additional context**

If the bug involves a device, then please include device diagnostics from
Settings / Devices & Services / Tuya Local (your device) / "1 device"

Please check if there are messages from Tuya Local in the Home
Assistant log (Settings / System / Logs), and include those too.

**Comment by make-all** [comment] 2024-05-25 13:03
Duplicate of #407

**Closed by make-all** 2024-05-25 13:03 UTC
Labels: bug
