### ISSUE TITLE
New Device request "Inventor ATMOSPHERE XL" Dehumidifier

### ISSUE THREAD

**Issue by geroulas** [make-all/tuya-local#263] opened 2022-11-05 14:19 UTC
**Standard Instruction Set**
switch | Boolean | "{true,false}"
dehumidify_set_enum | Enum | {   "range": [     "40",     "50"   ] }
fan_speed_enum | Enum | {   "range": [     "low",     "high"   ] }
mode | Enum | {   "range": [     "drying"   ] }
swing | Boolean | "{true,false}"
anion | Boolean | "{true,false}"
uv | Boolean | "{true,false}"
child_lock | Boolean | "{true,false}"
countdown_set | Enum | {   "range": [     "1h",     "2h",     "3h"   ]

**Standard Status Set**
switch | Boolean | "{true,false}"
dehumidify_set_enum | Enum | {   "range": [     "40",     "50"   ] }
fan_speed_enum | Enum | {   "range": [     "low",     "high"   ] }
mode | Enum | {   "range": [     "drying"   ] }
humidity_indoor | Integer | {   "unit": "%",   "min": 0,   "max": 100,   "scale": 0,   "step": 1 }
temp_indoor | Integer | {   "unit": "℃",   "min": 0,   "max": 100,   "scale": 0,   "step": 1 }
swing | Boolean | "{true,false}"
anion | Boolean | "{true,false}"
uv | Boolean | "{true,false}"
pm25 | Integer | {   "unit": "ug/m³",   "min": 0,   "max": 999,   "scale": 0,   "step": 1 }
child_lock | Boolean | "{true,false}"
countdown_set | Enum | {   "range": [     "1h",     "2h",     "3h"   ] }
countdown_left | Integer | {   "unit": "min",   "min": 0,   "max": 540,   "scale": 0,   "step": 1 }
fault | Bitmap | {   "label": [     "E1",     "E2"   ]

**CODE**
Power - 1
Humidity Set - 3
Fan Speed - 4
Mode - 5
Room Humidity - 6
Room Temp. - 7
Auto Louver Swing - 8
Air Purifier - 105
Ionizer - 10
HI - 106
LO - 107
Air Quality - 108
UVC - 13
Operation - 110
PM2.5 - 15
Light - 111
Child Lock - 16
Fan Speed (Air purifier) - 112
Timer - 17
Remaining Time - 18
Error - 19

**Comment by make-all** [comment] 2022-11-06 07:48
It looks like the "standard instruction set" and "standard status set" only documents the codes less than 100.  For codes 105 - 112, though I can guess at some from the name, for now I am just going to set them as read-only attributes on the main humidifier entity.  If some are supposed to be switches, numbers (for configuration) or sensors, I'll need more info on the type and any enum values or ranges.

**Comment by geroulas** [comment] 2022-11-06 10:00
> 

you are fast mate! thanks a lot.. If you can though me a link with a guide on what you need i'll get back to you.
I know what is what, I'll try to find the enum values or ranges somewhere in threre.

**Comment by make-all** [comment] 2022-11-06 10:06
Since you've already given me ranges on other values that look like they come from the portal, I'm not sure they will be there to find.  You may need to experiment with changing settings that are missing from this integration in the app (with wifi turned off so it does not steal the local connection) while observing the Attributes of the humidifier entity in the more info window or developer tools.  It may take up to 30s to reflect changes made outside of Home Assistant, so will need some patience.

**Comment by espressionist** [comment] 2022-11-07 23:30
Hiya,

Quite new here but got an Atmosphere XL 25L and keen to assist to get all functionality in HA. Let me know if I can help in any way (preferably with simple instructions :) )

**Comment by espressionist** [comment] 2022-11-08 00:21
Tried to add my Atmosphere XL 25 (downloaded the main branch instead of 0.20.2) however the dehumidifier is recognised as simple switch. HA Logs below (with the device initially turned on, then off while adding the device)

2022-11-08 02:18:36.985 WARNING (MainThread) [custom_components.tuya_local.config_flow] Device matches simple_switch with quality of 5%. DPS: {'1': True, '3': '50', '4': 'high', '5': 'night', '6': 55, '7': 22, '8': False, '10': True, '13': True, '15': 7, '16': False, '17': 'None', '18': 0, '19': 0, '105': 'night', '106': 0, '107': 0, '108': 'great', '110': 'air_purifier', '111': '3', '112': 'low', 'updated_at': 1667866716.8530164}
2022-11-08 02:18:36.986 WARNING (MainThread) [custom_components.tuya_local.config_flow] Report this to https://github.com/make-all/tuya-local/issues/
2022-11-08 02:19:32.766 WARNING (MainThread) [custom_components.tuya_local.config_flow] Device matches simple_switch with quality of 5%. DPS: {'1': False, '3': '50', '4': 'high', '5': 'night', '6': 55, '7': 22, '8': False, '10': True, '13': True, '15': 5, '16': False, '17': 'None', '18': 0, '19': 0, '105': 'night', '106': 0, '107': 0, '108': 'fine', '110': 'air_purifier', '111': '3', '112': 'low', 'updated_at': 1667866772.6318083}

**Comment by geroulas** [comment] 2022-11-08 08:22
> Tried to add my Atmosphere XL 25 (downloaded the main branch instead of 0.20.2) however the dehumidifier is recognised as simple switch.

Will be added as a dehumidifier in the next release.



> For codes 105 - 112, though I can guess at some from the name, for now I am just going to set them as read-only attributes on the main humidifier entity.

Seems we are good to go, Codes 105-112 are all attributes.

**Comment by espressionist** [comment] 2022-11-08 10:22
@geroulas Is there a way of testing the controls or are we stuck with the simple switch function for now?

**Comment by geroulas** [comment] 2022-11-08 10:35
@espressionist yes, just wait for the next update.

**Comment by make-all** [comment] 2022-11-08 14:33
Thanks @espressionist for the logs, they helped fill in some missing options for mode and timer, and also identified some type differences that might be causing the misdetection.

**Comment by espressionist** [comment] 2022-11-09 07:26
> Thanks @espressionist for the logs, they helped fill in some missing options for mode and timer, and also identified some type differences that might be causing the misdetection.

No problem at all @make-all , I can perform further tests while having the Dehumidifier working in different modes if that makes it easier for you?

Let me know if you need anything and many thanks for making this a thing in HA 😃

**Comment by espressionist** [comment] 2022-11-09 12:07
Device recognised and works in HA, however not sure what's the thing with the timer's switch values (OFF, 1h, 2h, 3h) I've set through the app a timer of 9h and is represented successfully by the timer attribute:
![image](https://user-images.githubusercontent.com/81738823/200825498-c6e63e6b-147c-4d24-a4b5-a3514b43cc60.png)

I've confirmed that adding values 4h to 9h (lines 147-158) work and represent a working state of the device and is also presented in the timer attribute
![image](https://user-images.githubusercontent.com/81738823/200826160-1002343b-a31b-425b-8f0e-998a893ef5f2.png)

**Comment by nikomaxos** [comment] 2022-11-17 07:32
> Device recognised and works in HA

@espressionist how did you get it to work? my HA is still identifying it as a simple switch.

My log below:

This error originated from a custom integration.

Logger: custom_components.tuya_local.config_flow
Source: custom_components/tuya_local/config_flow.py:35
Integration: Tuya Local (documentation, issues)
First occurred: 9:10:00 AM (4 occurrences)
Last logged: 9:19:02 AM

Device matches simple_switch with quality of 5%. DPS: {'1': True, '3': 'CO', '4': 'low', '5': 'manual', '6': 49, '7': 22, '8': False, '10': True, '13': True, '15': 3, '16': False, '17': 'None', '18': 0, '19': 0, '105': 'manual', '106': 0, '107': 0, '108': 'great', '110': 'dehumi_air', '111': '3', '112': 'middle', 'updated_at': 1668669000.050032}
Report this to https://github.com/make-all/tuya-local/issues/
Device matches simple_switch with quality of 5%. DPS: {'1': True, '3': 'CO', '4': 'low', '5': 'manual', '6': 49, '7': 22, '8': False, '10': True, '13': True, '15': 3, '16': False, '17': 'None', '18': 0, '19': 0, '105': 'manual', '106': 0, '107': 0, '108': 'great', '110': 'dehumi_air', '111': '3', '112': 'middle', 'updated_at': 1668669542.5157433}

**Comment by espressionist** [comment] 2022-11-17 07:50
> > Device recognised and works in HA
> 
> @espressionist how did you get it to work? my HA is still identifying it as a simple switch.
> 

I believe it is not released yet, did you try to download the latest main .zip file, then upload it to HA?

**Comment by make-all** [comment] 2022-11-17 12:41
It seems the target humidity is not limited to "40" and "50" as previously documented, and can also be "CO".  I made some changes to the config that should allow the auto detection to work.

**Comment by nikomaxos** [comment] 2022-11-17 13:47
Yes, CO stands for Continuous Operation. Also as I checked on the Tuya IOT platform Device Debugging and through the mobile application, the following should be taken into consideration:

On the modes, you have mapped "drying" (option for clothes) with "dehumidify". Please consider renaming it.

Also, the available target humidity is not only 40 and 50. Check below on the table. My export is somehow different than georgoulas user above:

Code | Type | Values
-- | -- | --
switch | Boolean | "{true,false}"
dehumidify_set_enum | Enum | {   "range": [     "CO",     "40",     "45",     "50",     "55",     "60",     "65",     "70",     "75",     "80"   ] }
fan_speed_enum | Enum | {   "range": [     "low",     "high"   ] }
mode | Enum | {   "range": [     "manual",     "drying",     "night",     "auto"   ] }
humidity_indoor | Integer | {   "unit": "%",   "min": 0,   "max": 100,   "scale": 0,   "step": 1 }
temp_indoor | Integer | {   "unit": "℃",   "min": 0,   "max": 100,   "scale": 0,   "step": 1 }
swing | Boolean | "{true,false}"
anion | Boolean | "{true,false}"
uv | Boolean | "{true,false}"
pm25 | Integer | {   "unit": "ug/m³",   "min": 0,   "max": 999,   "scale": 0,   "step": 1 }
child_lock | Boolean | "{true,false}"
countdown_set | Enum | {   "range": [     "1h",     "2h",     "3h",     "4h",     "5h",     "6h",     "7h",     "8h",     "9h",     "None"   ] }
countdown_left | Integer | {   "unit": "min",   "min": 0,   "max": 540,   "scale": 0,   "step": 1 }
fault | Bitmap | {   "label": [     "C1",     "C2",     "C8",     "000",     "999",     "P1",     "P2",     "Replace_HEPA"   ],   "maxlen": 8 }
Air_purify_mode | Enum | {   "range": [     "manual",     "night",     "auto"   ] }
Ambient_humidity_hi | Bitmap | {   "label": [     "HI"   ],   "maxlen": 1 }
Ambient_humidity_low | Bitmap | {   "label": [     "lo"   ],   "maxlen": 1 }
Air_quality | Enum | {   "range": [     "bad",     "fine",     "great"   ] }
Air_purify_switch | Enum | {   "range": [     "dehumi_air",     "air_purifier"   ] }
Light_level | Enum | {   "range": [     "1",     "2",     "3"   ] }
Air_purify_fan_speed | Enum | {   "range": [     "low",     "middle",     "high"   ] }

Also bear in mind that based on the device itself hardware buttons/settings and the tuya application:
1. When on "auto" mode -> you can not set either the target humidity or the fan speed
2. On "sleep" mode -> you can set the target humidity but not the fan speed and its auto-set to "low"
3. On "drying" mode -> you can not set either the speed or the target humidity and the fan speed is auto-set to "high"
4. On "manual" mode -> you can set both target humidity (with 5% step) and fan speed to "low" or "high"
5.  When you disable the dehumidification and the device acts only as an air purifier, you get an extra option on fan speed "middle" that you can choose (Air_purify_fan_speed) and the "drying" option is missing from the available modes to select
6. Consider adding one more switch for "swing"

I hope I helped and thank you for the integration up to the point you currently reached it. After 3 re-installs I managed to add the device properly.

**Comment by make-all** [comment] 2022-11-17 14:09
Thanks for that extra info.  Mostly it seems my guesses in the last commit based on the manual I found online were correct, the only one I am not sure about is the light values - they may be in the wrong order.

Unfortunately the complexity of those conditions is a bit too much to capture in the simple config format we have.  If there is something that causes the device to bug out though, I will try to prioritise that over other conditions.  Many Tuya devices do not do sufficient validation on the input and can go into strange misbehaving modes if the wrong input for the current state is given.

**Comment by nikomaxos** [comment] 2022-11-17 14:22
> Thanks for that extra info. Mostly it seems my guesses in the last commit based on the manual I found online were correct, the only one I am not sure about is the light values - they may be in the wrong order.

In regards to the light values, there is a 3 color led light indicator were it changes to notify the user about the pm2.5 levels. 
It turns to 
green for levels 0<=50
blue 51<=100
red for bigger than > 101

it is also connected with the "auto" mode, where it will be affected and changed together with the fan speed [when ONLY the air purifier is enabled (dehumidify is disabled)]

Air_purify_fan_speed | Enum | { "range": [ "low", "middle", "high" ] }
-- | -- | --



Thank you for the commit

**Comment by make-all** [comment] 2022-11-17 14:48
What I mean for the light is that the manual mentions that it can be switched off, with the 3 possibilities being "Indicator off, display on", "Both indicator and display off" (may be automatic during sleep mode?) and "Both indicator and display on".

**Comment by nikomaxos** [comment] 2022-11-17 17:11
> What I mean for the light is that the manual mentions that it can be switched off, with the 3 possibilities being "Indicator off, display on", "Both indicator and display off" (may be automatic during sleep mode?) and "Both indicator and display on".

Oh yes this is another feature. As you mentioned, "Indicator" is for the pm2.5 led light and "display" for its small lcd screen and lights on hardware buttons. It's a tuya app setting that works, but not affected by the night mode

check the device logs from Tuya cloud:

2022-11-17 19:10:09 | Report | Light | 3 - All indications on | device itself |  
2022-11-17 19:10:04 | Report | Light | 1 - Air quality indication off | device itself |  
2022-11-17 19:10:00 | Report | Light | 2 - All indications off | device itself

**Comment by nikomaxos** [comment] 2022-11-17 18:13
hi @make-all, adjusting target humidity is not working, check log below:

`Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/tuya_local/helpers/device_config.py:711
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 7:32:42 PM (11 occurrences)
Last logged: 8:09:29 PM

[140272142536176] '<' not supported between instances of 'str' and 'int'
[140271578786176] '<' not supported between instances of 'str' and 'int'
[140271110899120] '<' not supported between instances of 'str' and 'int'
[140271111093120] '<' not supported between instances of 'str' and 'int'
[140272325750560] '<' not supported between instances of 'str' and 'int'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1744, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1781, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 208, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 678, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 943, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 715, in _handle_entity_call
    await result
  File "/config/custom_components/tuya_local/generic/humidifier.py", line 101, in async_set_humidity
    await self._humidity_dps.async_set_value(self._device, humidity)
  File "/config/custom_components/tuya_local/helpers/device_config.py", line 361, in async_set_value
    settings = self.get_values_to_set(device, value)
  File "/config/custom_components/tuya_local/helpers/device_config.py", line 711, in get_values_to_set
    if result < minimum or result > maximum:
TypeError: '<' not supported between instances of 'str' and 'int'`
![Screen Shot 2022-11-17 at 20 10 06](https://user-images.githubusercontent.com/62503985/202524958-4308117a-12fc-4c05-8ad7-c45dcce3ee9c.png)

**Comment by nikomaxos** [comment] 2022-11-17 18:15
You're also missing the "Clothes" mode here.

![Screen Shot 2022-11-17 at 20 14 38](https://user-images.githubusercontent.com/62503985/202525400-c97e8a5c-a38a-4ad7-a894-5218469456fe.png)

**Comment by make-all** [comment] 2022-11-17 21:42
That last one is the purifier mode, which does not support clothes drying.  The dehumidifier mode is part of the humidifier entity.

**Comment by nikomaxos** [comment] 2022-11-18 09:28
> That last one is the purifier mode, which does not support clothes drying. The dehumidifier mode is part of the humidifier entity.

Ok thanks for the clarification.
So, if you fix the target humidity, i believe the integration is 100% complete then

**Comment by make-all** [comment] 2022-11-26 08:31
This should be all working now in the latest release, including adjusting the humidity.

**Comment by make-all** [comment] 2022-11-27 06:36
Closing as no feedback received since the 0.20.3 release

**Closed by make-all** 2022-11-27 06:36 UTC
Labels: awaiting confirmation

**Comment by nikomaxos** [comment] 2022-11-27 11:05
Yes all is working as expected, thank you for your effort @make-all
