### ISSUE TITLE
Error in logs: Detected blocking call to sleep inside the event loop. This is causing stability issues. 

### ISSUE THREAD

**Issue by KAKtyC87** [make-all/tuya-local#503] opened 2023-03-06 10:48 UTC
Error in logs when restarting integration:
_[homeassistant.util.async_] Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom integration author for tuya_local doing blocking calls at custom_components/tuya_local/device.py, line 66: self._api = tinytuya.Device(dev_id, address, local_key)_

Version HA: 2023.2.5
Version Module: 2023.3.0

But there are no problems in working with the device.

I will still attach the device diagnostics file:
[tuya_local-3a49750b17b55ee5b17799bbe75cb94d-Thermostat_BHT-002_kitchen-c59607afb5e6cfaead2fc05c2cecc599.json.txt](https://github.com/make-all/tuya-local/files/10897263/tuya_local-3a49750b17b55ee5b17799bbe75cb94d-Thermostat_BHT-002_kitchen-c59607afb5e6cfaead2fc05c2cecc599.json.txt)

**Comment by make-all** [comment] 2023-03-06 11:41
Duplicate of #407

**Closed by make-all** 2023-03-06 11:41 UTC
Labels: bug
