### ISSUE TITLE
Warning: bht002_gblw_thermostat.yaml/climate: Unrecognised HVAC Action Heat ignored

### ISSUE THREAD

**Issue by VladimirTuzovGitHub** [make-all/tuya-local#2386] opened 2024-10-11 05:52 UTC
Hello! I get a lot of "Warning" messages in the HA log - bht002_gblw_thermostat.yaml/climate: Unrecognised HVAC Action Heat ignored. I have two identical thermostats of the same manufacturer working in Tuya Local.

![image](https://github.com/user-attachments/assets/d052cca6-caea-4bff-9366-d0f8c34f65a8)

Diagnostic data: 
[tuya_local-96e59b2d972aea2493476c4cf2fcdbf0-Smart thermostat EKF - Спальня-66dde66840ea4d28f7f212356a4b33f4.json](https://github.com/user-attachments/files/17338221/tuya_local-96e59b2d972aea2493476c4cf2fcdbf0-Smart.thermostat.EKF.-.-66dde66840ea4d28f7f212356a4b33f4.json)

**Comment by make-all** [comment] 2024-10-11 12:08
I assume you closed it because you confirmed that the fix works.
My usual practice is to use the "awaiting confirmation" tag to track whether a fix is confirmed, and only close the issue when the fix is released in a published version.

**Comment by VladimirTuzovGitHub** [comment] 2024-10-11 12:23
Yes, that's right, I made the changes and tested it, the fix works. I apologize for closing the request, apparently I didn't understand all the tags correctly and thought that the changes were made and it was ready.

**Closed** 2024-10-14 12:36 UTC
