### ISSUE TITLE
Hassio reports stability issue

### ISSUE THREAD

**Issue by nliaudat** [make-all/tuya-local#744] opened 2023-05-28 16:53 UTC
```
Logger: homeassistant.util.async_
Source: util/async_.py:159
First occurred: 18:35:47 (7 occurrences)
Last logged: 18:49:52
Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom integration author for tuya_local doing blocking calls at custom_components/tuya_local/device.py, line 78: self._api = tinytuya.Device(dev_id, address, local_key)
```

Version 2023.5.1

**Comment by make-all** [comment] 2023-05-28 22:02
Duplicate of #407

**Closed by make-all** 2023-05-28 22:02 UTC
Labels: bug
