### ISSUE TITLE
Request support for [device description]

### ISSUE THREAD

**Issue by maticlms** [make-all/tuya-local#1081] opened 2023-09-09 23:04 UTC
# Log Message

```
Please paste logs here
```

# Information about DPS mappings

```
{
  "result": {
    "model": "{\"modelId\":\"ebtly8\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[
{\"abilityId\":1,\"accessMode\":\"rw\",\"code\":\"forward_energy_total\",\"description\":\"\",\"extensions\":{\"attribute\":\"1152\"},\"name\":\"正向总有功电量\",\"typeSpec\":{\"max\":99999999,\"min\":0,\"scale\":2,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"KWH\"}},
{\"abilityId\":2,\"accessMode\":\"rw\",\"code\":\"reverse_energy_total\",\"description\":\"\",\"extensions\":{\"attribute\":\"1152\"},\"name\":\"反向总有功电量\",\"typeSpec\":{\"max\":99999999,\"min\":0,\"scale\":2,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"KWH\"}},
{\"abilityId\":101,\"accessMode\":\"ro\",\"code\":\"power_a\",\"description\":\"\",\"name\":\"Power_a\",\"typeSpec\":{\"max\":600000,\"min\":0,\"scale\":1,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"W\"}},
{\"abilityId\":102,\"accessMode\":\"ro\",\"code\":\"direction_a\",\"description\":\"\",\"name\":\"Current_Flow_A\",\"typeSpec\":{\"range\":[\"FORWARD\",\"REVERSE\"],\"type\":\"enum\",\"typeDefaultValue\":\"FORWARD\"}},
{\"abilityId\":103,\"accessMode\":\"ro\",\"code\":\"tbd\",\"description\":\"\",\"name\":\"TBD\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":104,\"accessMode\":\"ro\",\"code\":\"direction_b\",\"description\":\"\",\"name\":\"Current_FLow_B\",\"typeSpec\":{\"range\":[\"FORWARD\",\"REVERSE\"],\"type\":\"enum\",\"typeDefaultValue\":\"FORWARD\"}},
{\"abilityId\":105,\"accessMode\":\"ro\",\"code\":\"power_b\",\"description\":\"\",\"name\":\"Power_b\",\"typeSpec\":{\"max\":600000,\"min\":0,\"scale\":1,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"W\"}},
{\"abilityId\":106,\"accessMode\":\"ro\",\"code\":\"energy_forword_a\",\"description\":\"\",\"name\":\"Forward_Energy_A\",\"typeSpec\":{\"max\":999999,\"min\":0,\"scale\":2,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"KWH\"}},
{\"abilityId\":107,\"accessMode\":\"ro\",\"code\":\"energy_reverse_a\",\"description\":\"\",\"name\":\"Reverse_Energy_A\",\"typeSpec\":{\"max\":999999,\"min\":0,\"scale\":2,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"KWH\"}},
{\"abilityId\":108,\"accessMode\":\"ro\",\"code\":\"energy_forword_b\",\"description\":\"\",\"name\":\"Forward_Energy_B\",\"typeSpec\":{\"max\":999999,\"min\":0,\"scale\":2,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"KWH\"}},
{\"abilityId\":109,\"accessMode\":\"ro\",\"code\":\"energy_reserse_b\",\"description\":\"\",\"name\":\"energy_reserse_b\",\"typeSpec\":{\"max\":999999,\"min\":0,\"scale\":2,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"KWH\"}},
{\"abilityId\":110,\"accessMode\":\"ro\",\"code\":\"power_factor\",\"description\":\"\",\"name\":\"Power_factor_A\",\"typeSpec\":{\"max\":100,\"min\":0,\"scale\":2,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"\"}},
{\"abilityId\":111,\"accessMode\":\"ro\",\"code\":\"freq\",\"description\":\"\",\"name\":\"AC_Freq\",\"typeSpec\":{\"max\":10000,\"min\":0,\"scale\":2,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"Hz\"}},
{\"abilityId\":112,\"accessMode\":\"ro\",\"code\":\"voltage_a\",\"description\":\"\",\"name\":\"Voltage\",\"typeSpec\":{\"max\":28000,\"min\":0,\"scale\":1,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"V\"}},
{\"abilityId\":113,\"accessMode\":\"ro\",\"code\":\"current_a\",\"description\":\"\",\"name\":\"Current_A\",\"typeSpec\":{\"max\":1000000,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"mA\"}},
{\"abilityId\":114,\"accessMode\":\"ro\",\"code\":\"current_b\",\"description\":\"\",\"name\":\"Current_B\",\"typeSpec\":{\"max\":1000000,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"mA\"}},
{\"abilityId\":115,\"accessMode\":\"ro\",\"code\":\"total_power\",\"description\":\"\",\"name\":\"Total_Power\",\"typeSpec\":{\"max\":99999999,\"min\":-99999999,\"scale\":1,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":-99999999,\"unit\":\"W\"}},
{\"abilityId\":116,\"accessMode\":\"rw\",\"code\":\"voltage_coef\",\"description\":\"\",\"name\":\"voltage_calibration\",\"typeSpec\":{\"max\":1200,\"min\":800,\"scale\":3,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":800,\"unit\":\"\"}},
{\"abilityId\":117,\"accessMode\":\"rw\",\"code\":\"current_a_calibration\",\"description\":\"\",\"name\":\"current_a_calibration\",\"typeSpec\":{\"max\":1200,\"min\":800,\"scale\":3,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":800,\"unit\":\"\"}},
{\"abilityId\":118,\"accessMode\":\"rw\",\"code\":\"power_a_calibration\",\"description\":\"\",\"name\":\"power_a_calibration\",\"typeSpec\":{\"max\":1200,\"min\":800,\"scale\":3,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":800,\"unit\":\"\"}},
{\"abilityId\":119,\"accessMode\":\"rw\",\"code\":\"energy_a_calibration_fwd\",\"description\":\"\",\"name\":\"energy_a_calibration_fwd\",\"typeSpec\":{\"max\":1200,\"min\":800,\"scale\":3,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":800,\"unit\":\"\"}},
{\"abilityId\":120,\"accessMode\":\"wr\",\"code\":\"coef_a_reset\",\"description\":\"\",\"name\":\"coef_a_reset\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":121,\"accessMode\":\"ro\",\"code\":\"power_factor_b\",\"description\":\"\",\"name\":\"Power_factor_B\",\"typeSpec\":{\"max\":100,\"min\":0,\"scale\":2,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"\"}},
{\"abilityId\":122,\"accessMode\":\"rw\",\"code\":\"freq_calibration\",\"description\":\"\",\"name\":\"频率校准\",\"typeSpec\":{\"max\":1200,\"min\":800,\"scale\":3,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":800,\"unit\":\"\"}},
{\"abilityId\":123,\"accessMode\":\"rw\",\"code\":\"current_b_calibration\",\"description\":\"\",\"name\":\"current_b_calibration\",\"typeSpec\":{\"max\":1200,\"min\":800,\"scale\":3,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":800,\"unit\":\"\"}},
{\"abilityId\":124,\"accessMode\":\"rw\",\"code\":\"power_b_calibration\",\"description\":\"\",\"name\":\"power_b_calibration\",\"typeSpec\":{\"max\":1200,\"min\":800,\"scale\":3,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":800,\"unit\":\"\"}},
{\"abilityId\":125,\"accessMode\":\"rw\",\"code\":\"energy_b_calibration_fwd\",\"description\":\"\",\"name\":\"energy_b_calibration_fwd\",\"typeSpec\":{\"max\":1200,\"min\":800,\"scale\":3,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":800,\"unit\":\"\"}},
{\"abilityId\":126,\"accessMode\":\"wr\",\"code\":\"coef_b_reset\",\"description\":\"\",\"name\":\"coef_b_reset\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":127,\"accessMode\":\"rw\",\"code\":\"energy_a_calibration_rev\",\"description\":\"\",\"name\":\"energy_a_calibration_rev\",\"typeSpec\":{\"max\":1200,\"min\":800,\"scale\":3,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":800,\"unit\":\"\"}},
{\"abilityId\":128,\"accessMode\":\"rw\",\"code\":\"energy_b_calibration_rev\",\"description\":\"\",\"name\":\"energy_b_calibration_rev\",\"typeSpec\":{\"max\":1200,\"min\":800,\"scale\":3,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":800,\"unit\":\"\"}},
{\"abilityId\":129,\"accessMode\":\"rw\",\"code\":\"report_rate_control\",\"description\":\"\",\"name\":\"report_rate_control\",\"typeSpec\":{\"max\":60,\"min\":3,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":3,\"unit\":\"s\"}}]}]}"
  },
  "success": true,
  "t": 1694300396550,
  "tid": "983bb89f4f6411eeb3f09e6a0abc163a"
}
```

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/matic/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/matic/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

DPID | Description | Example | unit
-- | -- | -- | --
128 | energy_b_calibration_rev | 1.000 | -
1 | Forward energy | 1.36KWH | kWh
129 | dp_report_rate_control | 3-60seconds | s
2 | Reverse energy | 1.48KWH | kWh
101 | Power_a | 346.10W | W
102 | Current_Flow_A | REVERSE/FORWARD | -
103 | TBD | ??? | ???
104 | Current_FLow_B | REVERSE/FORWARD | -
105 | Power_b | 325.10W | W
106 | energy_forword_a | 0.08KWH | kWh
107 | energy_reverse_a | 1.37KWH | kWh
108 | energy_forword_b | 1.33KWH | kWh
109 | energy_reserse_b | 0.14KWH | kWh
110 | Power_factor | 0.90 | -
111 | AC_Freq | 49.22Hz | Hz
112 | Voltage | 240.80V | V
113 | Current_a | 1492mA | mA
114 | Current_b | 1549mA | mA
115 | Total power | 4.50W | W
116 | voltage_calibration | 1.000 | -
117 | current_a_calibration | 1.000 | -
118 | power_a_calibration | 1.000 | -
119 | energy_a_calibration_fwd | 1.000 | -
120 | coef_a_reset | ? | ?
121 | Power_factor_b | 0.93 | -
122 | freq_calibration | 1.000 | -
123 | current_b_calibration | 1.000 | -
124 | power_b_calibration | 1.000 | -
125 | energy_b_calibration_fwd | 1.000 | -
126 | coef_b_reset | ? | ?
127 | energy_a_calibration_rev | 1.000 | -

</body>
</html>
![image](https://github.com/make-all/tuya-local/assets/57050502/9147fd92-9add-4c69-a2da-ef92c53af581)

# Product ID

# Information about how the device functions

https://www.aliexpress.com/item/1005005898087698.html?spm=a2g0o.productlist.main.1.4e2b125cciswNi&algo_pvid=6e7cb3be-2ae3-4838-99ce-81fb4b561631&algo_exp_id=6e7cb3be-2ae3-4838-99ce-81fb4b561631-0&pdp_npi=4%40dis%21EUR%2147.26%2125.99%21%21%2149.48%21%21%402101e9d516943006118592883e97b8%2112000034759160970%21sea%21SI%21735920768%21S&curPageLogUid=aCo4rGCnnpaY

**Comment by make-all** [comment] 2023-09-10 00:28
Duplicate of #1072.
If you can provide the product id, it can be added to the config as an Aubess 2CT

I see they also have a 1CT model, if it is the same DP layout, just missing some dps then it might be useful to make some of those optional.

**Closed by make-all** 2023-09-10 00:28 UTC

**Comment by maticlms** [comment] 2023-09-10 11:57
> 

Im new to this Tuya stuff. By product id you meen the Device ID from Tuya IoT platform or? Alwso what is a 1CT model. You meen number of Current clamps?

**Comment by make-all** [comment] 2023-09-10 13:36
By product id, I mean the product id from the Tuya IoT platform API Explorer (same function used to get local_key usually also lists this).  Device id is specific to your individual device, product id is shared with all devices that are the same.

The above is an issue with the configs - energy sensors should have a state class of total_increasing (or total and be capable of reporting when they were last reset), not measurement, but my templates for building up the configs quickly are putting measurement in for sensors.
