### ISSUE TITLE
Request support for M515EGWT V2

### ISSUE THREAD

**Issue by ops244** [make-all/tuya-local#1292] opened 2023-11-12 23:03 UTC
Detected blocking call to sleep inside the event loop by custom integration 'tuya_local' at custom_components/tuya_local/device.py, line 77: self._api = tinytuya.Device(dev_id, address, local_key), please create a bug report at

-------------------------------------------------------------------------------------------------------------------------------------------------

{
  "result": {
    "model": "{\"modelId\":\"000002otuw\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[
{\"abilityId\":1,\"accessMode\":\"rw\",\"code\":\"control\",\"description\":\"【必选项】用于控制电机的开启、暂停、关闭。该DP点枚举值参数不允许修改，不允许增减。\",\"extensions\":{\"iconName\":\"icon-dp_power2\"},\"name\":\"控制\",\"typeSpec\":{\"range\":[\"open\",\"stop\",\"close\"],\"type\":\"enum\",\"typeDefaultValue\":\"open\"}},
{\"abilityId\":2,\"accessMode\":\"rw\",\"code\":\"percent_control\",\"description\":\"如果窗帘电机可以监控窗帘目前的所处位置，例如窗帘现在开了一半，也就是50%，那么可以通过该DP点进行窗帘位置的自定义控制。控制使用该DP点，如果选择了该DP点，必选选择“”开启百分比状态显示“”，该DP点数值范围值参数不允许修改，不允许增减。\",\"extensions\":{\"iconName\":\"icon-dp_power\"},\"name\":\"开启百分比控制\",\"typeSpec\":{\"max\":100,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"%\"}},
{\"abilityId\":5,\"accessMode\":\"rw\",\"code\":\"control_back\",\"description\":\"用于设置电机转向，顺时针，或者逆时针，0代表顺时针，1代表顺时针\",\"extensions\":{\"iconName\":\"icon-dp_time2\"},\"name\":\"电机反向\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":7,\"accessMode\":\"ro\",\"code\":\"work_state\",\"description\":\"【必选项】用于显示电机的当前工作状态。该DP点枚举值参数不允许修改，不允许增减。如需要修改在APP面板中显示的内容，可以前往第四步的拓展中心，多语言管理修改代表值，新增的枚举值所代表的的内容也是在多语言中修改代表值。\",\"name\":\"工作状态\",\"typeSpec\":{\"range\":[\"opening\",\"closing\"],\"type\":\"enum\",\"typeDefaultValue\":\"opening\"}},
{\"abilityId\":12,\"accessMode\":\"ro\",\"code\":\"fault\",\"description\":\"【必选】设备上报故障值，该DP点枚举值可增减，但不可修改枚举值名称，例如可以删除motor_fault，可以增加其他值，未选则不展示该功能。 如需要修改在APP面板中显示的内容，可以前往第四步的拓展中心，多语言管理修改代表值，新增的枚举值所代表的的内容也是在多语言中修改代表值。\",\"name\":\"故障告警\",\"typeSpec\":{\"label\":[\"motor_fault\"],\"maxlen\":1,\"type\":\"bitmap\",\"typeDefaultValue\":0}},
{\"abilityId\":16,\"accessMode\":\"rw\",\"code\":\"border\",\"description\":\"\",\"extensions\":{\"attribute\":\"128\"},\"name\":\"设置限位\",\"typeSpec\":{\"range\":[\"up\",\"down\",\"up_delete\",\"down_delete\",\"remove_top_bottom\"],\"type\":\"enum\",\"typeDefaultValue\":\"up\"}},
{\"abilityId\":19,\"accessMode\":\"rw\",\"code\":\"position_best\",\"description\":\"\",\"extensions\":{\"attribute\":\"128\"},\"name\":\"最佳位置\",\"typeSpec\":{\"max\":100,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"%\"}}]}]}"
  },
  "success": true,
  "t": 1699829896536,
  "tid": "f70e6cfd81ae11eea7ba0a96cea2b375"
}

------------------------------------------------------------------------------------------------------------------------------------------------

{
  "code": 40001900,
  "msg": "No space permission",
  "success": false,
  "t": 1699829981137,
  "tid": "29864b9b81af11eea7ba0a96cea2b375"
}

-----------------------------------------------------------------------------------------------------------------------------------
curtain motor with power supply

https://aliexpress.ru/item/1005001890929280.html?sku_id=12000019272268447

**Comment by make-all** [comment] 2023-11-15 13:06
Duplicate of #1306

**Closed by make-all** 2023-11-15 13:06 UTC
Labels: new device
