### ISSUE TITLE
Home Assistant Warning in Logs

### ISSUE THREAD

**Issue by Daverover66** [make-all/tuya-local#736] opened 2023-05-23 16:23 UTC
This form is for reporting bugs.  If you have encountered a bug, you should
generally have some log messages or device diagnostics to show something is
going wrong.  If your problem is more of a question or a request for help,
then [Discussions](https://github.com/make-all/tuya-local/discussions) is
probably a more suitable venue.

**Describe the bug**
Just a routine check of my Home Asstant Logs

**To Reproduce**
Steps to reproduce the behavior including the device the issue was observed with:

**Expected behavior**

**Additional context**
Logger: homeassistant.util.async_
Source: util/async_.py:159
First occurred: 17:03:04 (13 occurrences)
Last logged: 17:03:49

Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom integration author for tuya_local doing blocking calls at custom_components/tuya_local/device.py, line 78: self._api = tinytuya.Device(dev_id, address, local_key)

**Comment by make-all** [comment] 2023-05-23 22:16
Duplicate of #407

**Closed by make-all** 2023-05-23 22:16 UTC
Labels: bug
