### ISSUE TITLE
Request support for wifi smart doorbell 柔乐-WiFi Monitor(RL-B17-TY系列)

### ISSUE THREAD

**Issue by karolzamosc** [make-all/tuya-local#462] opened 2023-02-24 19:34 UTC
Device is a smart doorbell with touchscreen and a few switches that allows: opening gateway, opening door, starts conversation after someone press outside ring button 

![obraz_2023-02-24_203354284](https://user-images.githubusercontent.com/61420368/221274310-067c8904-bced-4115-8b01-fdfdfe817fbc.png)

Device ID: bf33302eedb41c2022jxz2

Datapoints:
1. Lock-1: code 148
2. Record Switch: code 150
3. Doorbell active: code 136
4. Lock-2: code 232
5. Doorbell Snapshot: code 154
6. Camera smart action: code 191

record_switch | Boolean | "{true,false}"

ipc_smart_action | Enum | {   "range": [     "0",     "1",     "2",     "3"   ] }

doorbell_active | String | {   "maxlen": 255 }

record_switch | Boolean | "{true,false}"

doorbell_pic | Raw | {}

**Comment by make-all** [comment] 2023-03-04 05:06
This is where a manual or link to details comes in handy, as `ipc_smart_action | Enum | { "range": [ "0", "1", "2", "3" ] }` tells nothing about the functionality of that control, which seems quite fundamental to controlling the device.

**Comment by make-all** [comment] 2023-03-04 05:08
Also Raw as a type can be represented in many ways, so a log message as described in the new issue template is important to include.

**Comment by karolzamosc** [comment] 2023-03-04 08:48
@make-all:

{
  "result": {
    "category": "sp",
    "functions": [
      {
        "code": "record_switch",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "ipc_smart_action",
        "type": "Enum",
        "values": "{\"range\":[\"0\",\"1\",\"2\",\"3\"]}"
      }
    ],
    "status": [
      {
        "code": "doorbell_active",
        "type": "String",
        "values": "{\"maxlen\":255}"
      },
      {
        "code": "record_switch",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "doorbell_pic",
        "type": "Raw",
        "values": "{}"
      }
    ]
  },
  "success": true,
  "t": 1677919602041,
  "tid": "15d72d3aba6911ed98e69e0bfac44282"

**Comment by make-all** [comment] 2023-03-04 10:23
This is not from the HA log.  This is from the Tuya developer portal.  I need the message from the HA log when you go through the process of trying to configure this device in tuya-local.

**Comment by karolzamosc** [comment] 2023-03-04 22:00
I tried to configure the device but I got this error and the log is empty...

![tuya](https://user-images.githubusercontent.com/61420368/222930505-e3849d7b-0e25-4c27-96e8-0d2c3c690cd0.png)

**Comment by make-all** [comment] 2023-04-17 14:00
Check #522 for hints on resolving connection issues.

**Comment by make-all** [comment] 2023-06-15 14:27
Closing as unable to gather enough information to make a config

**Comment by karolzamosc** [comment] 2023-07-29 06:02
@make-all I still have problems with connections... But I have a question. If I share my doorbell to your account will you be able to integrate it?

**Comment by make-all** [comment] 2023-07-29 06:10
No. Sharing to my account would give me cloud access but that doesn't really help with local access other than being able to see the info you have already posted above.

**Comment by karolzamosc** [comment] 2023-07-29 06:13
I see, so the only way now is to read the HA log after trying to configure the doorbell?

**Comment by make-all** [comment] 2023-07-29 06:15
What I would need is a local log.   To solve the connection issues, try setting the IP address (to the device's local address on your network) and protocol version (probably to 3.4 or 3.5 if the auto setting is not working).  Also a link to the manual, or your own explanation of what ipc_smart_action is, and what options "0", "1", "2", and "3" are.

**Comment by karolzamosc** [comment] 2023-07-29 07:43
ok, after a little investigation I found that the ipc_smart_action involves a Camera Smart Action service that is doing... nothing 

![camera_action](https://github.com/make-all/tuya-local/assets/61420368/78f6ae69-3560-44e0-a7be-25f78594606d)
![ipc_smart](https://github.com/make-all/tuya-local/assets/61420368/db6e3530-2c62-4865-8968-bb35ae15f56a)

I still can not configure the doorbell because of connection error but I tried to configure it in a Local Tuya and I have this log. 

`2023-07-29 08:35:31.399 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf3...xz2] Sending command 10 (device type: type_0a)
2023-07-29 08:35:31.399 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf3...xz2] Sending payload: b'{"gwId":"bf33302eedb41c2022jxz2","devId":"bf33302eedb41c2022jxz2","uid":"bf33302eedb41c2022jxz2","t":"xxxxxxxxxxxxx"}'
2023-07-29 08:35:31.402 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf3...xz2] Command 10 waiting for seq. number 1
2023-07-29 08:35:31.407 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf3...xz2] Dispatching message CMD 10 TuyaMessage(seqno=1, cmd=10, retcode=1, payload=b'\xe9\xcb)]\x87\xd63W\x98\xd5"\xecn&\xcda\xaf\xc4,\xc7\x03\x8e\r!\xb8\xf1\x83\x8a&w\x9b\xd6', crc=2550442371, crc_good=True)
2023-07-29 08:35:31.410 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf3...xz2] 'data unvalid' error detected: switching to dev_type 'type_0d'
2023-07-29 08:35:31.410 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf3...xz2] Re-send 10 due to device type change (type_0a -> type_0d)
2023-07-29 08:35:31.410 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf3...xz2] Sending command 10 (device type: type_0d)
2023-07-29 08:35:31.411 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf3...xz2] Sending payload: b'{"devId":"bf33302eedb41c2022jxz2","uid":"bf33302eedb41c2022jxz2","t":"xxxxxxxxxxxx","dps":{"1":null,"2":null,"3":null,"4":null,"5":null,"6":null,"7":null,"8":null,"9":null,"10":null}}'
2023-07-29 08:35:31.414 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf3...xz2] Command 13 waiting for seq. number 2
2023-07-29 08:35:31.421 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf3...xz2] Dispatching message CMD 13 TuyaMessage(seqno=2, cmd=13, retcode=0, payload=b'', crc=2380353348, crc_good=True)
2023-07-29 08:35:31.422 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf3...xz2] ACK received for command 13: ignoring it
2023-07-29 08:35:31.422 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf3...xz2] Sending command 10 (device type: type_0d)
2023-07-29 08:35:31.423 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf3...xz2] Sending payload: b'{"devId":"bf33302eedb41c2022jxz2","uid":"bf33302eedb41c2022jxz2","t":"xxxxxxxxxxxxx","dps":{"1":null,"11":null,"12":null,"13":null,"14":null,"15":null,"16":null,"17":null,"18":null,"19":null,"20":null}}'
2023-07-29 08:35:31.426 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf3...xz2] Command 13 waiting for seq. number 3
2023-07-29 08:35:31.444 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf3...xz2] Dispatching message CMD 13 TuyaMessage(seqno=3, cmd=13, retcode=0, payload=b'', crc=1350014657, crc_good=True)
2023-07-29 08:35:31.445 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf3...xz2] ACK received for command 13: ignoring it
2023-07-29 08:35:31.445 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf3...xz2] Sending command 10 (device type: type_0d)
2023-07-29 08:35:31.445 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf3...xz2] Sending payload: b'{"devId":"bf33302eedb41c2022jxz2","uid":"bf33302eedb41c2022jxz2","t":"xxxxxxxxxxxxxxx","dps":{"1":null,"21":null,"22":null,"23":null,"24":null,"25":null,"26":null,"27":null,"28":null,"29":null,"30":null}}'
2023-07-29 08:35:31.449 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf3...xz2] Command 13 waiting for seq. number 4
2023-07-29 08:35:31.456 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf3...xz2] Dispatching message CMD 13 TuyaMessage(seqno=4, cmd=13, retcode=0, payload=b'', crc=755273881, crc_good=True)
2023-07-29 08:35:31.457 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf3...xz2] ACK received for command 13: ignoring it
2023-07-29 08:35:31.458 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf3...xz2] Sending command 10 (device type: type_0d)
2023-07-29 08:35:31.458 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf3...xz2] Sending payload: b'{"devId":"bf33302eedb41c2022jxz2","uid":"bf33302eedb41c2022jxz2","t":"xxxxxxxxxxxxxxx","dps":{"1":null,"100":null,"101":null,"102":null,"103":null,"104":null,"105":null,"106":null,"107":null,"108":null,"109":null,"110":null}}'
2023-07-29 08:35:31.487 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf3...xz2] Command 13 waiting for seq. number 5
2023-07-29 08:35:31.497 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf3...xz2] Dispatching message CMD 13 TuyaMessage(seqno=5, cmd=13, retcode=0, payload=b'', crc=4036118812, crc_good=True)
2023-07-29 08:35:31.508 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf3...xz2] ACK received for command 13: ignoring it
2023-07-29 08:35:31.509 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf3...xz2] Detected dps: {}
2023-07-29 08:35:31.509 DEBUG (MainThread) [custom_components.localtuya.config_flow] Detected DPS: {}
2023-07-29 08:35:31.509 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf3...xz2] Closing connection
2023-07-29 08:35:31.531 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf3...xz2] Connection lost: None`

It looks that there is no data points detected connected with theese ones:

![data_points](https://github.com/make-all/tuya-local/assets/61420368/3055b0e4-24ac-4778-beca-7c4cf58dcc6a)

**Comment by make-all** [comment] 2023-07-29 07:58
It seems like it is the type of device that has to have its dp prised out of it, the problem is that neither localtuya nor tuya-local try 148 and 150, as they are quite rare.  localtuya is trying 1 - 30 and 100 - 110 across 4 poll, tuya-local does a single poll with 1, 20, 101 to catch the more common cases, so we have room for a few more in there.

**Comment by karolzamosc** [comment] 2023-08-01 08:37
@make-all what are the next steps? :⁠-⁠)

**Closed** 2023-08-13 11:00 UTC

**Comment by karolzamosc** [comment] 2023-08-18 06:34
I got an error when adding the doorbell:

![error](https://github.com/make-all/tuya-local/assets/61420368/063dd062-dff0-4eba-acf3-e3e7a59304ff)

**Comment by make-all** [comment] 2023-08-18 06:39
"Unable to connect" means you have a connection issue: see #522, but if this device is battery operated and not via a hub, then you are most likely out of luck.

**Comment by make-all** [comment] 2023-08-18 06:43
Looking at the above, it seems you have never gotten past that point with tuya-local, and have logs from localtuya showing that the device does not return anything for its status.  I did try adding dp 148 to the list of dps that we try to force a report out of during initial connection, but it seems that did not work.  Probably this device is unable to work locally.

**Comment by karolzamosc** [comment] 2023-08-18 08:38
Overall I have problems with all devices after rebooting my router (Netgear Orbi Mesh system). All devices become unavailable and I need to delete and add them again (I need to use IP because "auto" mode doesn't work too) of course IP, token and device ID doesn't change but devices need to be configured again anyway... After that all works fine till the next router reboot or power loss 🤔

**Comment by make-all** [comment] 2023-08-18 08:53
Instead of removing and readding all your devices, have you tried restarting Home Assistant?  I have never had to remove and re-add devices, even though I have some lightbulbs that like to stay offline when someone turns them off and back on at the wall.

Also, if you are using "Auto" protocol detection, this can fail (it may succeed first time because it tries the real protocol version before hitting the one that causes devices to become unresponsive, but when the devices go offline due to the router reboots, the version detection will eventually restart from where it left off and get to the problematic versions).  People find much better recovery reliability when they set to the actual protocol version used by the device.

**Comment by karolzamosc** [comment] 2023-08-18 09:06
I thought that becoming devices offline after power loss issue is connected with no working auto mode... Yes, I tried HA restart but it doesn't solve the problem. All devices has fixed IP, wi-fi signaI is strong and all devices works fine in Tuya app... I don't know how to fix this issue 🙄
