### ISSUE TITLE
homeassistant.components.light

### ISSUE THREAD

**Issue by ops244** [make-all/tuya-local#1489] opened 2024-01-07 21:35 UTC
Logger: homeassistant.components.light
Source: components/light/__init__.py:1194
Integration: Освещение ([documentation](https://www.home-assistant.io/integrations/light), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+light%22))
First occurred: 00:22:22 (1 occurrences)
Last logged: 00:22:22

Entity None (<class 'custom_components.tuya_local.light.TuyaLocalLight'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <LightEntityFeature: 0> and color modes, please create a bug report at https://github.com/make-all/tuya-local/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation

**Comment by make-all** [comment] 2024-01-07 23:33
Duplicate of #1484, which is already fixed

**Closed** 2024-01-08 14:07 UTC
