### ISSUE TITLE
Detected blocking call to sleep inside the event loop

### ISSUE THREAD

**Issue by marcin-gacek** [make-all/tuya-local#597] opened 2023-04-08 07:43 UTC
**Describe the bug**
Logger: homeassistant.util.async_
Source: util/async_.py:159
First occurred: 08:26:49 (7 occurrences)
Last logged: 08:27:20

Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom integration author for tuya_local doing blocking calls at custom_components/tuya_local/device.py, line 66: self._api = tinytuya.Device(dev_id, address, local_key)

**To Reproduce**
Updated to latest version on 08/04/2023
Log info.

**Expected behavior**
Expected no error in log :)

**Comment by make-all** [comment] 2023-04-08 07:51
Duplicate of #407 

You can avoid this issue by setting the IP address correctly

**Closed by make-all** 2023-04-08 07:51 UTC
Labels: bug
