### ISSUE TITLE
Request support for WF-3188 pool ph orp meter

### ISSUE THREAD

**Issue by denveronly** [make-all/tuya-local#977] opened 2023-08-09 18:17 UTC
# Log Message

```
Please paste logs here
```

# Information about DPS mappings

```
{
  "result": {
    "model": "{\"modelId\":\"0000047m9o\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[{\"abilityId\":1,\"accessMode\":\"ro\",\"code\":\"tds_in\",\"description\":\"\",\"extensions\":{\"attribute\":\"1664\"},\"name\":\"TDS\",\"typeSpec\":{\"max\":9999,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"ppm\"}},{\"abilityId\":2,\"accessMode\":\"ro\",\"code\":\"temp_current\",\"description\":\"\",\"extensions\":{\"attribute\":\"1152\"},\"name\":\"Temprt\",\"typeSpec\":{\"max\":800,\"min\":0,\"scale\":1,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"℃\"}},{\"abilityId\":7,\"accessMode\":\"ro\",\"code\":\"battery_percentage\",\"description\":\"\",\"extensions\":{\"attribute\":\"1664\"},\"name\":\"BatteryValue\",\"typeSpec\":{\"max\":100,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"%\"}},{\"abilityId\":10,\"accessMode\":\"ro\",\"code\":\"ph\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-p7\",\"attribute\":\"1152\"},\"name\":\"PH值\",\"typeSpec\":{\"max\":1400,\"min\":0,\"scale\":2,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0}},{\"abilityId\":11,\"accessMode\":\"ro\",\"code\":\"conductivity_value\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_mode\",\"attribute\":\"1152\"},\"name\":\"EC\",\"typeSpec\":{\"max\":200000,\"min\":0,\"scale\":3,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"mS/cm\"}},{\"abilityId\":12,\"accessMode\":\"ro\",\"code\":\"orp_value\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-tongji\",\"attribute\":\"1024\"},\"name\":\"ORP\",\"typeSpec\":{\"max\":1200,\"min\":-1200,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":-1200,\"unit\":\"mV\"}},{\"abilityId\":101,\"accessMode\":\"rw\",\"code\":\"phbuffer\",\"description\":\"\",\"name\":\"pHBuffer\",\"typeSpec\":{\"range\":[\"AsiaStandard\",\"EUStandard\"],\"type\":\"enum\",\"typeDefaultValue\":\"AsiaStandard\"}},{\"abilityId\":102,\"accessMode\":\"rw\",\"code\":\"holdreading\",\"description\":\"\",\"name\":\"HoldReading\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},{\"abilityId\":103,\"accessMode\":\"rw\",\"code\":\"backlight\",\"description\":\"\",\"name\":\"BackLight\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},{\"abilityId\":104,\"accessMode\":\"rw\",\"code\":\"ectempcompenabled\",\"description\":\"\",\"name\":\"EcTempCompEnabled\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},{\"abilityId\":105,\"accessMode\":\"rw\",\"code\":\"ectempcomfactor\",\"description\":\"\",\"name\":\"EcTempCompFactor\",\"typeSpec\":{\"max\":30,\"min\":0,\"scale\":1,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"%/℃\"}},{\"abilityId\":106,\"accessMode\":\"rw\",\"code\":\"buzzerwarning\",\"description\":\"\",\"name\":\"BuzzerWarning\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},{\"abilityId\":107,\"accessMode\":\"rw\",\"code\":\"phmaxlimit\",\"description\":\"\",\"name\":\"pHMaxLimit\",\"typeSpec\":{\"max\":1400,\"min\":0,\"scale\":2,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"\"}},{\"abilityId\":108,\"accessMode\":\"rw\",\"code\":\"phminlimit\",\"description\":\"\",\"name\":\"pHMinLimit\",\"typeSpec\":{\"max\":1400,\"min\":0,\"scale\":2,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"\"}},{\"abilityId\":109,\"accessMode\":\"rw\",\"code\":\"ecmaxlimit\",\"description\":\"\",\"name\":\"EC最大值\",\"typeSpec\":{\"max\":200000,\"min\":0,\"scale\":3,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"mS/cm\"}},{\"abilityId\":110,\"accessMode\":\"rw\",\"code\":\"ecminlimit\",\"description\":\"\",\"name\":\"EC最小值\",\"typeSpec\":{\"max\":200000,\"min\":0,\"scale\":3,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"mS/cm\"}},{\"abilityId\":111,\"accessMode\":\"rw\",\"code\":\"orpmaxlimit\",\"description\":\"\",\"name\":\"OrpMaxLimit\",\"typeSpec\":{\"max\":1200,\"min\":-1200,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":-1200,\"unit\":\"mV\"}},{\"abilityId\":112,\"accessMode\":\"rw\",\"code\":\"orpminlimit\",\"description\":\"\",\"name\":\"OrpMinLimit\",\"typeSpec\":{\"max\":1200,\"min\":-1200,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":-1200,\"unit\":\"mV\"}},{\"abilityId\":113,\"accessMode\":\"ro\",\"code\":\"eccf\",\"description\":\"\",\"name\":\"CF\",\"typeSpec\":{\"max\":20000,\"min\":0,\"scale\":1,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"\"}},{\"abilityId\":114,\"accessMode\":\"ro\",\"code\":\"humidity\",\"description\":\"\",\"name\":\"Humidity\",\"typeSpec\":{\"max\":100,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"%\"}},{\"abilityId\":115,\"accessMode\":\"rw\",\"code\":\"humiditymaxlimit\",\"description\":\"\",\"name\":\"HumidityMaxLimit\",\"typeSpec\":{\"max\":100,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"%\"}},{\"abilityId\":116,\"accessMode\":\"rw\",\"code\":\"humidityminlimit\",\"description\":\"\",\"name\":\"HumidityMinLimit\",\"typeSpec\":{\"max\":100,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"%\"}}]}]}"
  },
  "success": true,
  "t": 1691604899488,
  "tid": "a6cb02aa36e011eeb3f09e6a0abc163a"
}
```

# Product ID

{
  "result": [
    {
      "active_time": 1691510661,
      "category": "szjcy",
      "create_time": 1691510661,
      "custom_name": "Yueryi PH pool",
      "icon": "smart/icon/bay164497620449560Pe/3c680798e8af1b8ed29218a14427936d.jpg",
      "id": "xxx
      "ip": "178.54.78.230",
      "is_online": true,
      "lat": "xxx
      "local_key": "xxx
      "lon": "30.5264",
      "model": "WF-3188",
      "name": "YINMIK Water Quality Tester",
      "product_id": "u5xgcpcngk3pfxb4",
      "product_name": "YINMIK水质检测仪",
      "sub": false,
      "time_zone": "+03:00",
      "update_time": 1691510682,
      "uuid": "e4d56e432a0732c6"
    }
  ],
  "success": true,
  "t": 1691604987402,
  "tid": "db3a61bd36e011ee8298eeefa7b3467e"
}

**Comment by denveronly** [comment] 2023-08-09 18:19
hello, i purchased tuya ph orp pool meter, and it shows as not supported, i cant add it

**Comment by make-all** [comment] 2023-08-09 21:57
Duplicate of #880

**Closed by make-all** 2023-08-09 21:57 UTC
