### ISSUE TITLE
Looses connection to pool heatpump repeatedly. HA restart required

### ISSUE THREAD

**Issue by AminShAT** [make-all/tuya-local#837] opened 2023-06-25 06:48 UTC
I use the Tuya integration for my pool heatpump. It works okay, but looses connection multiple times a day and requires a HA restart. After restarting it is immediately connected again and shows proper data.

**Comment by make-all** [comment] 2023-06-25 07:33
Se discussion #522 for ideas, especially setting the protocol version and IP address in the config can help a lot with reconnection if your WiFi to the device is a bit flakey, which is likely the root issue for an outdoor swimming pool pump using a standard Tuya module with PCB printed WiFi antenna.

**Comment by make-all** [comment] 2023-06-25 07:34
In the absence of logs showing that the issue is caused by this integration rather than the WiFi environment, I am closing this as not a bug.

**Closed** 2023-06-25 07:34 UTC
